// Package git is the merge queue's git side: [StagingRepo] for planning and validation,
// [MergingRepo] for applying, each over one checkout's object store.
//
// The two are separate types on purpose. Only a StagingRepo takes a regeneration hook,
// which runs the changes' code; a MergingRepo cannot be handed one, so the job holding
// the write credential runs plumbing only (merge-tree, commit-tree, push) and never
// checks out or executes a change's code.
//
// Stages are linked worktrees under a scratch directory, so speculative stages build and
// validate side by side while sharing every object.
//
// A file is derived when the base commit's .gitattributes set the configured attribute
// on it (linguist-generated by default, the attribute GitHub already reads). Attributes
// are read from the base, never from a change, so a change cannot declare its own
// sources derived and have the queue settle their conflicts.
package git

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"slices"
	"strings"

	"github.com/egladman/magus/libs/mergequeue"
)

// DefaultAttribute marks derived files when [Config.Attribute] is empty.
const DefaultAttribute = "linguist-generated"

// Config names the checkout both repos work in.
type Config struct {
	Root   string // the checkout whose object store backs every stage
	Remote string // remote name or URL changes and the base are fetched from
	// Attribute marks derived files; empty means DefaultAttribute.
	Attribute string
	Env       []string // extra environment for every git call
}

func (c Config) check() error {
	if c.Root == "" || c.Remote == "" {
		return errors.New("git: a repo needs a Root and a Remote")
	}
	return nil
}

// repo is what both sides share: reads, fetches and merges without a checkout.
type repo struct{ Config }

// tipRef is where FetchTip parks a branch's tip. A ref of the queue's own, so a fetch
// never writes FETCH_HEAD, which concurrent fetches would race on.
const tipRef = "refs/mergequeue/tips/"

// run runs git and returns its trimmed stdout; any non-zero exit is an error.
func (r *repo) run(ctx context.Context, dir string, env []string, stdin []byte, args ...string) (string, error) {
	raw, err := r.exec(ctx, dir, env, stdin, args...)
	if err != nil {
		return "", err
	}
	return trim(args, raw), nil
}

func (r *repo) exec(ctx context.Context, dir string, env []string, stdin []byte, args ...string) ([]byte, error) {
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = dir
	cmd.Env = append(append(os.Environ(), r.Env...), env...)
	if stdin != nil {
		cmd.Stdin = bytes.NewReader(stdin)
	}
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	raw, err := cmd.Output()
	if err != nil {
		return raw, &gitError{args: args, err: err, stderr: strings.TrimSpace(stderr.String())}
	}
	return raw, nil
}

type gitError struct {
	args   []string
	err    error
	stderr string
}

func (e *gitError) Error() string {
	return fmt.Sprintf("git %s: %v: %s", strings.Join(e.args, " "), e.err, e.stderr)
}

func (e *gitError) Unwrap() error { return e.err }

// exitCode is err's git exit status, or -1 when git did not exit normally.
func exitCode(err error) int {
	var exit *exec.ExitError
	if errors.As(err, &exit) {
		return exit.ExitCode()
	}
	return -1
}

// trim drops surrounding whitespace, except from -z output, where a leading space is a
// status column rather than padding.
func trim(args []string, raw []byte) string {
	if slices.Contains(args, "-z") {
		return strings.TrimRight(string(raw), "\n")
	}
	return strings.TrimSpace(string(raw))
}

func splitNUL(s string) []string {
	var out []string
	for p := range strings.SplitSeq(s, "\x00") {
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

func (r *repo) attribute() string {
	if r.Attribute == "" {
		return DefaultAttribute
	}
	return r.Attribute
}

// derived returns the subset of paths whose attributes at commit mark them derived.
func (r *repo) derived(ctx context.Context, commit string, paths []string) (map[string]bool, error) {
	out := map[string]bool{}
	if len(paths) == 0 {
		return out, nil
	}
	stdin := []byte(strings.Join(paths, "\x00") + "\x00")
	raw, err := r.run(ctx, r.Root, nil, stdin, "check-attr", "--source="+commit, "-z", "--stdin", r.attribute())
	if err != nil {
		return nil, err
	}
	// Records are <path> NUL <attribute> NUL <value> NUL.
	f := strings.Split(raw, "\x00")
	for i := 0; i+2 < len(f); i += 3 {
		if v := f[i+2]; v == "set" || v == "true" {
			out[f[i]] = true
		}
	}
	return out, nil
}

// sources returns the paths commit's attributes do not mark derived, in order.
func (r *repo) sources(ctx context.Context, commit string, paths []string) ([]string, error) {
	d, err := r.derived(ctx, commit, paths)
	if err != nil {
		return nil, err
	}
	var src []string
	for _, p := range paths {
		if !d[p] {
			src = append(src, p)
		}
	}
	return src, nil
}

// FetchTip fetches branch into a ref of the queue's own and returns its tip.
func (r *repo) FetchTip(ctx context.Context, branch string) (string, error) {
	if err := mergequeue.CheckBranch(branch); err != nil {
		return "", err
	}
	ref := tipRef + branch
	if _, err := r.run(ctx, r.Root, nil, nil, "fetch", "--quiet", "--no-write-fetch-head", r.Remote, "+refs/heads/"+branch+":"+ref); err != nil {
		return "", err
	}
	return r.run(ctx, r.Root, nil, nil, "rev-parse", "--verify", "--end-of-options", ref+"^{commit}")
}

// FetchHead makes c.Head available locally, through c.Ref when it has one.
func (r *repo) FetchHead(ctx context.Context, c mergequeue.Change) error {
	if err := c.Check(); err != nil {
		return err
	}
	if r.has(ctx, c.Head) {
		return nil
	}
	if c.Ref != "" {
		if _, err := r.run(ctx, r.Root, nil, nil, "fetch", "--quiet", "--no-write-fetch-head", r.Remote, c.Ref); err == nil && r.has(ctx, c.Head) {
			return nil
		}
	}
	// No ref, a ref moved past the listed head, or one deleted since listing: fetch the
	// head itself.
	_, err := r.run(ctx, r.Root, nil, nil, "fetch", "--quiet", "--no-write-fetch-head", r.Remote, c.Head)
	return err
}

func (r *repo) has(ctx context.Context, commit string) bool {
	_, err := r.run(ctx, r.Root, nil, nil, "cat-file", "-e", commit+"^{commit}")
	return err == nil
}

// mergeTree merges b onto a without a checkout, returning the (possibly marker-bearing)
// tree and the conflicted paths. Exit status 1 is how merge-tree says "conflicts" as
// opposed to "could not run", so this is the one caller that reads it as a result.
func (r *repo) mergeTree(ctx context.Context, extra []string, a, b string) (tree string, conflicts []string, err error) {
	args := append(append([]string{"merge-tree", "--write-tree", "--name-only", "--no-messages", "-z"}, extra...), a, b)
	raw, err := r.exec(ctx, r.Root, nil, nil, args...)
	if err != nil && (exitCode(err) != 1 || len(raw) == 0) {
		return "", nil, err
	}
	fields := splitNUL(trim(args, raw))
	if len(fields) == 0 {
		return "", nil, fmt.Errorf("git merge-tree %s %s printed no tree", a, b)
	}
	return fields[0], fields[1:], nil
}

// changedBetween lists the paths whose content differs between two commits' trees.
func (r *repo) changedBetween(ctx context.Context, a, b string) ([]string, error) {
	out, err := r.run(ctx, r.Root, nil, nil, "diff-tree", "-r", "--name-only", "-z", a, b)
	if err != nil {
		return nil, err
	}
	return splitNUL(out), nil
}

// reviewDepth bounds how many update commits ReviewTarget looks through.
const reviewDepth = 8

// ReviewTarget is the commit a review of head covers. A head with two parents, the
// second already on the base branch at tip, whose tree differs from the merge of its
// parents only in files tip marks derived, adds nothing a reviewer did not see: it is a
// update commit the queue pushed, or the base branch merged into the change by its
// author. A review of its first parent covers it, and so on down.
func (r *repo) ReviewTarget(ctx context.Context, tip, head string) (string, error) {
	for range reviewDepth {
		out, err := r.run(ctx, r.Root, nil, nil, "rev-list", "--parents", "-n", "1", head)
		if err != nil {
			return "", err
		}
		ids := strings.Fields(out)
		if len(ids) != 3 {
			return head, nil
		}
		first, second := ids[1], ids[2]
		if _, err := r.run(ctx, r.Root, nil, nil, "merge-base", "--is-ancestor", second, tip); err != nil {
			if exitCode(err) == 1 {
				return head, nil
			}
			return "", err
		}
		merged, _, err := r.mergeTree(ctx, nil, second, first)
		if err != nil {
			return "", err
		}
		diff, err := r.changedBetween(ctx, merged, head)
		if err != nil {
			return "", err
		}
		src, err := r.sources(ctx, tip, diff)
		if err != nil {
			return "", err
		}
		if len(src) > 0 {
			return head, nil
		}
		head = first
	}
	return head, nil
}

// TreeOf returns rev's tree.
func (r *repo) TreeOf(ctx context.Context, rev string) (string, error) {
	return r.run(ctx, r.Root, nil, nil, "rev-parse", "--verify", "--end-of-options", rev+"^{tree}")
}
