// Command langservice-manifest regenerates internal/langservice/manifest_data.go:
// a build-time snapshot of the magus host module surface (every module, with its
// fields and methods and rendered Buzz signatures) that the browser playground's
// completion and hover read. It is the same data `magus describe modules` prints,
// frozen into Go literals so the playground wasm carries it without linking the
// heavy host package (which pulls in os/exec, net, and the git libraries).
//
// Regenerate after adding or changing a host module, then commit the result -
// manifest_data.go is a committed artifact, like the playground wasm:
//
//	go run ./cmd/langservice-manifest
//
// The blank import of std is what registers the modules; host.ModulesOutput reads
// that registry.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/egladman/magus/host"

	_ "github.com/egladman/magus/std" // registers every host module via init()
)

const outFile = "internal/langservice/manifest_data.go"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "langservice-manifest:", err)
		os.Exit(1)
	}
}

func run() error {
	// The list view names every module; the detail view (per name) is the only one
	// that populates fields and methods, so fetch each module individually.
	list := host.ModulesOutput("")

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/langservice-manifest; DO NOT EDIT.\n")
	b.WriteString("// Regenerate with: go run ./cmd/langservice-manifest\n\n")
	b.WriteString("package langservice\n\n")
	b.WriteString("// modules is the snapshot of the magus host module surface used by completion\n")
	b.WriteString("// and hover. See cmd/langservice-manifest.\n")
	b.WriteString("var modules = []Module{\n")

	for _, summary := range list.Modules {
		m := host.ModulesOutput(summary.Name)
		if len(m.Modules) == 0 {
			continue
		}
		mod := m.Modules[0]
		fmt.Fprintf(&b, "\t{\n\t\tName: %q,\n\t\tDoc: %q,\n", mod.Name, mod.Doc)

		if len(mod.Fields) > 0 {
			b.WriteString("\t\tFields: []Field{\n")
			for _, f := range mod.Fields {
				fmt.Fprintf(&b, "\t\t\t{Name: %q, Type: %q, Doc: %q},\n", f.Name, f.Type, f.Doc)
			}
			b.WriteString("\t\t},\n")
		}
		if len(mod.Methods) > 0 {
			b.WriteString("\t\tMethods: []Method{\n")
			for _, meth := range mod.Methods {
				fmt.Fprintf(&b, "\t\t\t{Name: %q, Doc: %q, Sig: %q},\n", meth.Name, meth.Doc, meth.Buzz)
			}
			b.WriteString("\t\t},\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w", err)
	}
	if err := os.WriteFile(filepath.FromSlash(outFile), src, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outFile, err)
	}
	fmt.Printf("wrote %s (%d modules)\n", outFile, len(list.Modules))
	return nil
}
