package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/egladman/magus/internal/docs"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestEmbeddedSkillIsWellFormed guards that the shipped SKILL.md carries the Agent
// Skills frontmatter (name + description) an agent host requires - a broken skill
// would install silently and never trigger.
func TestEmbeddedSkillIsWellFormed(t *testing.T) {
	b, err := skillFS.ReadFile("skills/magus/SKILL.md")
	require.NoError(t, err)
	fm, ok := docs.ParseFrontmatter(string(b))
	require.True(t, ok, "SKILL.md must open with YAML frontmatter")
	assert.NotEmpty(t, fm.Description, "skill needs a description")
	// name: is required by the Agent Skills spec but is not a docs-frontmatter field,
	// so check the block carries it directly.
	assert.Contains(t, string(b), "\nname: ", "skill needs a name")
}

func TestInstallClaudeSkillWritesStampedFiles(t *testing.T) {
	dir := t.TempDir()
	written, err := installClaudeSkill(dir, false)
	require.NoError(t, err)
	require.NotEmpty(t, written)

	skillPath := filepath.Join(dir, ".claude/skills/magus/SKILL.md")
	assert.Contains(t, written, ".claude/skills/magus/SKILL.md")

	body, err := os.ReadFile(skillPath)
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(string(body), "---\n"), "frontmatter still leads the file")
	assert.Contains(t, string(body), "agent-skill-version: 1", "install stamps the drift footer")
	assert.Contains(t, string(body), "knowledge-schema-version:")
}

func TestInstallClaudeSkillRefusesThenForces(t *testing.T) {
	dir := t.TempDir()
	_, err := installClaudeSkill(dir, false)
	require.NoError(t, err)

	_, err = installClaudeSkill(dir, false)
	require.Error(t, err, "a second install without --force must refuse")
	assert.Contains(t, err.Error(), "already exists")

	_, err = installClaudeSkill(dir, true)
	assert.NoError(t, err, "--force overwrites")
}

func TestStampSkillAppendsExactlyOneFooter(t *testing.T) {
	out := string(stampSkill([]byte("---\nname: x\n---\nbody\n")))
	assert.Equal(t, 1, strings.Count(out, "generated by: magus agent install"))
	assert.True(t, strings.HasSuffix(out, "-->\n"), "footer is the last line")
}
