package main

import (
	"context"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"

	"github.com/bmatcuk/doublestar/v4"
	"github.com/egladman/magus"
	"github.com/egladman/magus/internal/agent"
	"github.com/egladman/magus/internal/config"
	"github.com/egladman/magus/internal/ledger"
	"github.com/egladman/magus/internal/notes"
	"github.com/egladman/magus/internal/trail"
	"github.com/egladman/magus/types"
)

// The path surface of `magus session hook`: every rule that judges a file an edit is
// about to write. The order they speak in is hookCmd's, not theirs, so each answers
// only about the path it was handed and returns "" when it has nothing to say. The
// command surface is guard_shell.go.

// adviseGeneratedWrite explains why editing path is wasted effort, or "" when
// there is nothing to say. Not a heuristic: magus knows every target's declared
// outputs, so a role=output path is generated by definition.
//
// It teaches rather than blocks - a hand-edited generated file is wasteful, not
// destructive. Silent on every uncertainty, because an advisory fired on a guess
// trains the reader to ignore it.
func adviseGeneratedWrite(ctx context.Context, path string) string {
	path = strings.TrimSpace(path)
	if path == "" {
		return ""
	}
	// No root override: FindRoot walks up from the CWD, which is where the hook
	// runs, so a nested project resolves to its own workspace.
	ws, err := inspectWorkspace(ctx, "")
	if err != nil || ws == nil {
		return ""
	}
	// A cancelled ctx folds into the same silent-on-uncertainty contract as the
	// error above: this advisory has no error path of its own.
	files, err := ws.ClassifyFiles(ctx, []string{path})
	if err != nil || len(files) != 1 || files[0].Role != "output" {
		return ""
	}
	f := files[0]
	owner := f.Project
	if owner == "" {
		owner = "."
	}
	return fmt.Sprintf("magus workspace: edit the SOURCE instead, then %s and commit the regenerated file with your source change.\n"+
		"%s is a DECLARED OUTPUT of project %s. magus read the target's declared globs, so the next run overwrites whatever you write there.\n"+
		"`magus describe file <path>` classifies any path. Load the magus-vcs-hygiene skill if not already loaded.", regenerateAdvice(f, owner), f.Path, owner)
}

// regenerateAdvice names the target that rewrites the path, resolved from the
// declaration that claimed it.
//
// Never a canonical name: a target called "generate" is this repository's
// convention, and the guard ships in a binary that judges workspaces which name
// their codegen anything at all. A project-wide or spell-supplied output glob
// carries no target (FileClaim.Target is empty there), so that case routes to
// discovery rather than guessing.
//
// The CLAIM's project, not the owner: a cross-project write is attributed to the
// tree it lands in by FileEntry.Project and to the declarer by FileClaim.Project,
// and only the declarer can regenerate it.
//
// Several targets may declare the same output glob, and the order the claims arrive in
// is the extractor's. The pick is sorted by project then target so the same path always
// advises the same command - WHICH of them is named does not matter, since any of them
// regenerates the file, but an answer that changes between two runs of the same guard
// does.
func regenerateAdvice(f types.FileEntry, owner string) string {
	producers := make([]types.FileClaim, 0, len(f.Claims))
	for _, c := range f.Claims {
		if c.Role == "output" && c.Target != "" {
			producers = append(producers, c)
		}
	}
	if len(producers) == 0 {
		return "run the target that produces it: `magus describe targets` lists what this workspace defines"
	}
	slices.SortFunc(producers, func(a, b types.FileClaim) int {
		if n := strings.Compare(a.Project, b.Project); n != 0 {
			return n
		}
		return strings.Compare(a.Target, b.Target)
	})
	producer := producers[0].Project
	if producer == "" {
		producer = owner
	}
	return fmt.Sprintf("run `magus run %s %s`", producers[0].Target, producer)
}

// denyNotesWrite blocks a write into the workspace's declared notes store, or returns ""
// for every other path.
//
// This is the only DENY on the path surface, and it does not fit either of the guard's two
// standing triggers, so it is worth saying plainly why it is here. It is not irreversible:
// a note in git is recoverable. It does not have an exact equivalent either: `magus memory
// put` is where an agent's thought belongs, but memory is user-local while notes are
// shared, so the substitute is not equal for something meant for the team.
//
// The trigger is a third one - the artifact's value depends on a guarantee about WHO wrote
// it, and undoing the write does not restore the guarantee. A note is the one thing in the
// graph that is not derived from the workspace: nothing in the repo corroborates it, now or
// in a year, so its only provenance is the person who wrote it. One agent-written note does
// not damage that note, it damages a reader's ability to trust ANY note without checking
// blame - and a note of uncertain authorship is not degraded, it is worthless.
//
// Two honest limits. The guard is not a security boundary (see TestGuardKnownHoles): this
// is a habit rail, and the gate that holds is a check on the pull-request path. And on a
// host with no pre-write file hook - Cursor - the deny arrives after the write has landed,
// which its template records as deny=human rather than papering over.
//
// Silent unless the store is DECLARED. A deny fired on a guessed location would block work
// in a workspace that never opted in, which is far worse than an advisory fired on a guess.
// workspaceDeclaresNotes reports whether THIS repository's own magus.yaml declares a shared
// notes store. A read failure reports false, degrading to the on-disk check rather than
// denying writes in a workspace whose intent cannot be read.
func workspaceDeclaresNotes(root string) bool {
	cfg, err := config.LoadWorkspaceOnly(root)
	if err != nil {
		return false
	}
	return strings.TrimSpace(cfg.Knowledge.Notes.Shared) != ""
}

func denyNotesWrite(path string) string {
	path = strings.TrimSpace(path)
	if path == "" {
		return ""
	}
	declared := strings.TrimSpace(globalCfg.Knowledge.Notes.Shared)
	if declared == "" {
		return ""
	}
	root, err := magus.FindRoot("")
	if err != nil {
		return ""
	}
	dir, err := notes.Dir(root, notes.ScopeShared, declared)
	if err != nil {
		return ""
	}
	// The opt-in is the repository's OWN magus.yaml, and it holds from the moment the key is
	// committed. Gating on the directory existing instead let an agent author the store's
	// FIRST note - measured 2026-08-13, a write to notes/<name>.md passed - after which the
	// deny switched on and protected the forgery it had just admitted.
	//
	// A declaration from anywhere else (an explicit --config, user-global) is in effect in
	// every workspace on the machine, so that one still needs the store to exist, or one
	// setting would deny writes in repos that never opted in.
	if !workspaceDeclaresNotes(root) {
		if st, err := os.Stat(dir); err != nil || !st.IsDir() {
			return ""
		}
	}
	abs := path
	if !filepath.IsAbs(abs) {
		abs = filepath.Join(root, abs)
	}
	// Compare REAL paths. A host hands over whatever path its editor tool used, and on
	// macOS /var is a symlink to /private/var, so a tmpdir-rooted workspace yields a
	// declared store under one spelling and an incoming write under the other. Comparing
	// them literally makes the rule silently pass - a deny that fails open is worse than
	// no deny, because it looks enforced.
	rel, err := filepath.Rel(resolveSymlinks(dir), resolveSymlinks(filepath.Clean(abs)))
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return ""
	}
	return fmt.Sprintf("magus workspace: recording a DECISION ABOUT THIS WORKSPACE? Use `magus memory put <name>`, the agent-writable store. If it genuinely belongs in the notes, say so and let the person run `magus notes edit %s`.\n"+
		"%s is in this workspace's NOTES store, which only a person may write: a note is the one thing in the graph the repository cannot corroborate later, so its only provenance is the human who signed the commit.\n"+
		"Read the store with `magus notes ls` and `magus notes get <name>`.", strings.TrimSuffix(filepath.Base(path), ".md"), path)
}

// resolveSymlinks canonicalizes as much of path as exists, returning it unchanged when
// nothing can be resolved. The file being judged has not been written yet, so the deepest
// EXISTING ancestor is what can be resolved; the remainder is appended verbatim.
func resolveSymlinks(path string) string {
	rest := ""
	for cur := path; ; {
		if real, err := filepath.EvalSymlinks(cur); err == nil {
			return filepath.Join(real, rest)
		}
		parent := filepath.Dir(cur)
		if parent == cur {
			return path // nothing along the way exists; compare what we were given
		}
		rest = filepath.Join(filepath.Base(cur), rest)
		cur = parent
	}
}

// Where the acting delegation's identity comes from. Both spellings name the same thing so a
// harness can pick whichever it can set: a wrapper that builds an argv passes the flag, and a
// worker that only inherits an environment exports the W3C baggage member.
//
// envHookDelegation is the ASSIGNMENT a person would type, not a variable name, because that
// is what the advisories below hand them: BAGGAGE carries a list, so naming the variable alone
// would tell a reader to set it to a bare id and produce a value no baggage parser accepts.
const (
	flagHookDelegation = "delegation"
	envHookDelegation  = trail.EnvBaggage + "=" + trail.BaggageDelegation
)

// writeGrade is what the delegation ledger has to say about one write. Separate from
// guardVerdict because the empty Decision means "no opinion", which the wire's "pass"
// does not: a rule that stayed silent and a rule that cleared the write are different
// facts, and only the first may be overridden by a later rule.
type writeGrade struct {
	Decision string // "", "deny", or "advise"
	Reason   string
	Context  string
}

// gradeDelegatedWrite judges a file write against the delegation ledger's declared write
// boundaries, and says nothing at all when no fleet is running.
//
// The ledger RECORDS and the guard ENFORCES. That split is deliberate (internal/ledger's
// package doc argues it): a store that quietly gated writes would become something agents
// route around, while a guard denial is loud, names the owning delegation, and teaches. This is
// the reader that turns those declared facts into a verdict, and the only one.
//
// The delegation id is the ONLY thing here that reads any of the propagation channels. The
// trace context a spawning tool claims alongside it is attribution and never a verdict's input.
//
// It is a SEATBELT FOR COOPERATING HARNESSES, NOT A SANDBOX. An un-enrolled writer - a
// person editing their own repo with no baggage set - is advised and never blocked.
// magus cannot tell "not part of the fleet" from "part of it and not saying so", and of
// the two ways to be wrong, blocking a human in their own checkout is the one that must
// not happen.
//
// Every uncertainty fails OPEN with at most an advisory: no ledger, no live delegations, a file
// that will not parse, a path outside the workspace. A rule the guard cannot evaluate must
// not block a tool call.
func gradeDelegatedWrite(ctx context.Context, actingDelegation, writePath string) writeGrade {
	writePath = strings.TrimSpace(writePath)
	if writePath == "" {
		return writeGrade{}
	}
	location := hookActivityTrail(ctx)
	if location.base == "" {
		return writeGrade{}
	}
	store := ledger.NewStore(ledger.Location{CacheDir: location.base, Root: location.workspace})
	delegations, err := store.List()
	if err != nil {
		// An ABSENT ledger is not this branch: the store reads it as an empty one, which
		// falls through to the no-live-delegations return below and costs a stat. Only a file
		// that exists and will not parse arrives here, and it is worth a word, because a
		// delegation whose boundary silently stopped being checked looks exactly like one
		// nobody declared.
		return writeGrade{Decision: "advise", Context: fmt.Sprintf(
			"magus workspace: no delegation boundary was checked for this write. Re-declare the plan with the magus_ledger tool if delegated work is meant to be running.\n"+
				"This workspace's delegation ledger could not be read: %v. The guard fails open rather than blocking on a file it cannot parse, so an owned-path collision would pass unnoticed until someone reads the diff.", err)}
	}
	live := liveDelegations(delegations)
	if len(live) == 0 {
		return writeGrade{}
	}
	rel, inside := workspaceRelative(location.workspace, writePath)
	if !inside {
		// The ledger's paths are workspace-relative, so a write outside the workspace has
		// nothing to be graded against.
		return writeGrade{}
	}

	notice := ""
	if actingDelegation != "" && !types.ValidDelegationID(actingDelegation) {
		// Treated as absent rather than rejected: an id magus cannot parse is an id it
		// cannot look up either, and erroring would block the tool call over metadata. The
		// notice is what keeps a typo from silently buying un-enrolled treatment.
		notice = fmt.Sprintf(
			"magus workspace: fix the delegation id and re-run, so the guard can grade this write against your delegation's declared boundary.\n"+
				"%s=%q is not a valid delegation id (at most %d characters of A-Za-z0-9-_./:), so this call was graded as if it named no delegation.\n",
			envHookDelegation, actingDelegation, types.MaxDelegationIDLen)
		actingDelegation = ""
	}

	if me, enrolled := liveDelegation(live, actingDelegation); enrolled {
		return gradeAgainstOwnDelegation(me, live, rel)
	}
	// An id that is valid but names no LIVE row lands here too, and that is the intent: a
	// delegation whose plan already ended has no boundary left to grade against, and denying on
	// one would block work whose ledger row is simply stale.
	if owner, owned := ownerOf(live, rel, ""); owned {
		// Recorded as well as reported, so the delegation whose file just moved can find out by
		// asking the ledger. Telling only the writer left the one party who needed it - the agent
		// still holding a stale read of this path - as the only party never informed.
		//
		// Best-effort by construction: a failure here is swallowed, because this whole function
		// fails open and a ledger that would not accept a note must not cost somebody a save.
		_ = store.RecordUnattributedWrite(ctx, owner.ID, rel)
		return writeGrade{Decision: "advise", Context: notice + fmt.Sprintf(
			"magus workspace: if you are delegation %s, set %s=%s (or pass --delegation %s) so the guard grades your writes; if you are not, expect a concurrent agent to be editing this file and coordinate before you save.\n"+
				"%s is inside the paths delegation %s (%s) declared it owns, and that delegation is %s. This is an advisory and not a deny: the guard is a seatbelt for harnesses that opt in, not a sandbox, so an editor magus cannot attribute is never stopped from writing its own repository.",
			owner.ID, envHookDelegation, owner.ID, owner.ID, rel, owner.ID, goalLine(owner), owner.State)}
	}
	if notice != "" {
		return writeGrade{Decision: "advise", Context: strings.TrimRight(notice, "\n")}
	}
	return writeGrade{}
}

// gradeAgainstOwnDelegation judges a write made by a delegation that IS in the live set.
//
// Forbidden beats owned, because a forbidden entry inside an owned tree is the more
// specific of two declarations the same orchestrator wrote. A write that no live delegation
// claims passes: an orchestrator's owned set is a plan, not a census, and denying on
// unclaimed ground would block a delegation from a file nobody is competing for.
func gradeAgainstOwnDelegation(me types.Delegation, live []types.Delegation, rel string) writeGrade {
	// BEFORE the path checks, because an unregistered delegation should not be writing anywhere -
	// not merely outside its lane. A checkpoint is what makes its work recoverable and what says
	// which base the work applies to, and both facts are worth nothing recorded afterwards.
	//
	// This is the one rule here that enforces a PROCEDURE rather than a boundary, and it is a deny
	// rather than an advisory for the reason the skill was not enough: an instruction an agent can
	// skip is an instruction that gets skipped, and the record it was meant to leave is missing
	// exactly when somebody needs to recover from it. A human is unaffected - they never name a
	// delegation, so they never reach this function at all.
	if me.Registered == 0 {
		return writeGrade{Decision: "deny", Reason: fmt.Sprintf(
			"magus workspace: run `magus vcs checkpoint -o name` in this tree and register what it prints with the magus_ledger tool (op register, delegation %s), then retry this write.\n"+
				"Delegation %s (%s) has not registered the base it landed on, so nothing records which revision your work applies to. Without it a reviewer cannot tell your changes from the ones already there, and a recovery cannot tell where to start.",
			me.ID, me.ID, goalLine(me))}
	}
	if decl, forbidden := declarationCovering(me.ForbiddenPaths, rel); forbidden {
		return writeGrade{Decision: "deny", Reason: fmt.Sprintf(
			"magus workspace: work inside your own owned paths, or report a checkpoint to the orchestrator and ask for the boundary to be widened before you touch this.\n"+
				"%s is covered by %q, which your delegation %s (%s) declared FORBIDDEN. The declaration is the orchestrator's, recorded in this workspace's ledger; magus is reading it back, not inventing a rule.",
			rel, decl, me.ID, goalLine(me))}
	}
	if _, mine := declarationCovering(me.OwnedPaths, rel); mine {
		// Advisory rather than a block: an orchestrator may have rebased the plan deliberately,
		// and magus cannot tell that from a worker that wandered. What it can do is refuse to let
		// the divergence stay silent until the merge finds it.
		if me.BaseVerdict == types.BaseDiverged {
			return writeGrade{Decision: "advise", Context: fmt.Sprintf(
				"magus workspace: re-checkpoint and re-register if you moved on purpose; otherwise reconcile with the orchestrator before writing more.\n"+
					"Delegation %s registered on %s, which is not the checkpoint it was handed (%s). You are working from a different base than the plan assumes, so your changes may not apply where it expects them.",
				me.ID, me.ReportedBase, me.Checkpoint)}
		}
		return writeGrade{}
	}
	if owner, owned := ownerOf(live, rel, me.ID); owned {
		return writeGrade{Decision: "deny", Reason: fmt.Sprintf(
			"magus workspace: edit inside your own owned paths, or ask the orchestrator to re-partition the plan. If delegation %s has finished with this file, have it release the path by shrinking its owned_paths with the magus_ledger tool, then retry.\n"+
				"%s is owned by delegation %s (%s), which is %s right now, and you are delegation %s. Two agents editing one path is the collision the delegation ledger exists to make visible; this guard is where the declaration gets read.",
			owner.ID, rel, owner.ID, goalLine(owner), owner.State, me.ID)}
	}
	return writeGrade{}
}

// liveDelegations are the rows a write can still collide with: declared and running.
// A terminal row has stopped competing for its paths, which is the same rule
// types.delegationOverlaps applies when it decides which pairs to report. A row with no
// state at all is not live either - it has not said it is.
func liveDelegations(delegations []types.Delegation) []types.Delegation {
	live := make([]types.Delegation, 0, len(delegations))
	for _, u := range delegations {
		if u.State == types.StateDeclared || u.State == types.StateRunning {
			live = append(live, u)
		}
	}
	return live
}

// liveDelegation finds the acting delegation's own row. An empty id matches nothing, so an
// un-enrolled caller cannot collide with a row whose id was never written.
func liveDelegation(live []types.Delegation, id string) (types.Delegation, bool) {
	if id == "" {
		return types.Delegation{}, false
	}
	i := slices.IndexFunc(live, func(u types.Delegation) bool { return u.ID == id })
	if i < 0 {
		return types.Delegation{}, false
	}
	return live[i], true
}

// ownerOf finds the live delegation whose owned paths cover rel, skipping the id in exclude.
//
// Ledger order breaks ties. Two delegations declaring one path is an overlap the ledger already
// reports as a fact, and naming the first-recorded one keeps the guard's answer stable
// between two runs over the same file - an answer that changes run to run is one nobody
// can act on.
func ownerOf(live []types.Delegation, rel, exclude string) (types.Delegation, bool) {
	for _, u := range live {
		if u.ID == exclude {
			continue
		}
		if _, ok := declarationCovering(u.OwnedPaths, rel); ok {
			return u, true
		}
	}
	return types.Delegation{}, false
}

// declarationCovering reports which declaration covers rel, and whether any did. rel is
// workspace-relative and slash-separated, as the ledger's declarations are.
//
// A declaration covers the SUBTREE beneath what it names, which is what an orchestrator
// means by writing "internal/ledger" into a plan. That is the second Match call: appending
// "/**" is the same trick internal/file/watch uses to reach a glob's descendants.
//
// Deliberately NOT types.pathsIntersect. That one compares two DECLARATIONS and
// over-reports on purpose, truncating each to its literal prefix, so "console/src/**/*.ts"
// and "console/src/**/*.css" read as overlapping. Over-reporting is right for a fact a
// human reads and wrong here, where the answer denies a write: a guard that blocks
// legitimate edits is one agents learn to route around, and routing around it is the
// failure the whole ledger design is built to avoid.
func declarationCovering(decls []string, rel string) (string, bool) {
	for _, raw := range decls {
		decl := path.Clean(strings.TrimSpace(raw))
		if decl == "." || decl == "/" {
			// A blank entry, or one that names the whole tree by naming nothing, would put
			// its delegation on every path in the plan. types.pathsIntersect refuses the same
			// entry for the same reason. An explicit "**" is a different thing and stands.
			continue
		}
		if ok, _ := doublestar.Match(decl, rel); ok {
			return raw, true
		}
		if ok, _ := doublestar.Match(decl+"/**", rel); ok {
			return raw, true
		}
	}
	return "", false
}

// workspaceRelative resolves an incoming path to a workspace-relative, slash-separated
// one, reporting false when it lands outside the workspace.
//
// Symlinks are resolved on BOTH sides, for the reason denyNotesWrite records: a host hands
// over whatever path its editor tool used, and on macOS a tmpdir-rooted workspace yields
// the root under one spelling and the write under another. Comparing them literally makes
// the rule silently pass, and a deny that fails open is worse than no deny, because it
// looks enforced.
func workspaceRelative(root, p string) (string, bool) {
	if root == "" {
		return "", false
	}
	abs := p
	if !filepath.IsAbs(abs) {
		abs = filepath.Join(root, abs)
	}
	rel, err := filepath.Rel(resolveSymlinks(root), resolveSymlinks(filepath.Clean(abs)))
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return "", false
	}
	return filepath.ToSlash(rel), true
}

// goalLine is the delegation's goal reduced to its first line. Goal holds the goal AND its
// acceptance criteria as one block (see types.Delegation), and pasting all of that
// into a denial would bury the next step under it.
func goalLine(u types.Delegation) string {
	line, _, _ := strings.Cut(strings.TrimSpace(u.Goal), "\n")
	if line == "" {
		return "no goal recorded"
	}
	return line
}

// adviseMemoryWrite nudges a magus-domain decision toward `magus memory put`
// when the write lands in a cross-host instruction file, or "" otherwise.
//
// Capture, not replication: host instructions belong in the file. The point is
// that a decision ABOUT THE WORKSPACE outlives a per-checkout, per-host file, so
// the advisory names both destinations rather than arguing against one.
func adviseMemoryWrite(path string) string {
	// Matched as a bare filename stem, which is the sanctioned form: these name
	// well-known files on disk rather than branching on which host is running.
	// The .md check keeps a template or a sibling extension (agents.md.tmpl,
	// agents.mdx) out of it.
	base := strings.ToLower(filepath.Base(strings.TrimSpace(path)))
	if filepath.Ext(base) != ".md" {
		return ""
	}
	switch strings.TrimSuffix(base, ".md") {
	case "agents", "claude":
	default:
		return ""
	}
	return "magus workspace: recording a DECISION ABOUT THIS WORKSPACE (a target, a saved query, an output ref, a doc)? Put it in the handoff journal too: `magus memory put <name>`.\n" +
		"This file is per-host and per-checkout, so a second worktree or a different agent host never sees it. Host instructions belong right where you are writing them; workspace decisions outlive the file. Load the magus-handoff-journal skill if not already loaded."
}

// adviseInstalledSkillWrite explains that an installed skill is generated, or
// "" when the path is not one. The other path advisories catch a write that is
// wasted; this one catches a write that DISAPPEARS - `magus doctor` reports it
// as drift and the next `install --force` erases it.
//
// The STAMP is the discriminator, not the path: a workspace's own skill sits in
// the same directory, and telling an author their file is generated would be
// worse than saying nothing.
//
// Unreachable in magus's own tree, which is worth knowing before hunting a bug:
// this repo declares its installed skills as outputs, so adviseGeneratedWrite
// claims the path first and can name the producing target.
func adviseInstalledSkillWrite(path string) string {
	clean := filepath.ToSlash(strings.TrimSpace(path))
	if filepath.Base(clean) != "SKILL.md" {
		return ""
	}
	installed := false
	for _, dir := range agent.WellKnownSkillDirs() {
		if strings.Contains(clean, dir+"/") {
			installed = true
			break
		}
	}
	if !installed {
		return ""
	}
	body, err := os.ReadFile(path)
	if err != nil || !strings.Contains(string(body), "source: magus") {
		return ""
	}
	return "magus workspace: put rules that belong to THIS workspace in a local skill beside the installed ones, in a directory magus does not ship (conventionally magus-local-development), which install and verify both leave alone.\n" +
		"That file is an INSTALLED skill, generated from magus's embedded sources and stamped with a content digest: `magus doctor` reports your edit as stale rather than reading it, and the next `magus agent install <dir> --force` overwrites it.\n" +
		"Stamp each rule with its evidence and the condition that retires it. Load the magus-workspace-rules skill for the format."
}
