package magus_test

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// bearerRe matches a `token=` carrying something long enough to be a real bearer
// rather than a placeholder. auth.Generate mints 256 bits base64url-encoded, so a
// live token is 43 characters; the documented forms (`token=...`, `token=<bearer>`)
// are far shorter and contain characters this class excludes.
var bearerRe = regexp.MustCompile(`token=[A-Za-z0-9_-]{20,}`)

// TestDocsCarryNoBearerToken keeps a live daemon token out of committed documentation.
//
// docs/concepts/knowledge.md is generated by cmd/magus-examples, which captures the
// real stdout of `magus explain`. That output ends with a Graph Explorer deep-link,
// and the link carries the daemon auth token - auth.Load reads it from a file in the
// state dir whether or not a daemon is running. So the page committed a real token
// from whichever machine last regenerated it, and the docs site published it.
//
// It also made the page machine-dependent, which is how it was found: a runner has no
// token file, regenerated the link without one, and the drift gate failed on CI while
// passing on every developer machine. The capture now runs with XDG_STATE_HOME pointed
// into its own fixture, so there is no token to find.
//
// Documented placeholders stay legal - docs/reference/console.md explains the scheme
// with `#token=<bearer>`, which is the useful thing to write.
func TestDocsCarryNoBearerToken(t *testing.T) {
	var findings []string

	err := filepath.WalkDir("docs", func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil //nolint:nilerr // an unreadable subtree is skipped, not fatal
		}
		if d.IsDir() {
			// gen/ is rendered output, not committed (see the publish workflow).
			if d.Name() == "gen" || d.Name() == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		if filepath.Ext(path) != ".md" {
			return nil
		}
		body, err := os.ReadFile(path)
		if err != nil {
			return nil //nolint:nilerr // same
		}
		for i, line := range strings.Split(string(body), "\n") {
			if m := bearerRe.FindString(line); m != "" {
				findings = append(findings, path+":"+itoa(i+1)+": "+m)
			}
		}
		return nil
	})
	require.NoError(t, err)

	assert.Emptyf(t, findings,
		"committed documentation carries what looks like a live bearer token:\n  %s\n\n"+
			"Regenerate the page rather than editing it, and rotate the token - a doc site is\n"+
			"public. Write a placeholder (`token=<bearer>`) when documenting the scheme.",
		strings.Join(findings, "\n  "))
}
