package guard

import (
	"context"
	"slices"
	"strings"

	"github.com/egladman/magus/internal/hint"
	"github.com/egladman/magus/internal/trail"
)

// How a catalogued deny is worded.
//
// Inline, a deny prints the verdict, one sentence naming the actual problem, then at most
// one next command and the ref holding the full verdict. The rationale and the rule's page
// live only in that stored verdict: the reader who declined the argument once is not
// persuaded by reading it again, and the ref is there for the reader who wants it, where
// its uptake is counted. A repeat within a session swaps the verdict for one line naming
// the rule and what it catches.
//
// "nothing ran" survives on both forms. Chained edits ahead of a denied command were
// re-run on the assumption that they had happened, and a repeat is exactly where a reader
// skims.

// ruleDocsBase is where every catalogued rule has a page, generated by hack/magusfile/ruledocs.buzz.
const ruleDocsBase = "https://eli.gladman.cc/magus/reference/rules/"

// verdictRefPrefix names a stored guard verdict in the shared ref namespace, beside out
// (a run's output) and mcp (an MCP payload).
const verdictRefPrefix = "grd"

// denyMarker keys a rule's first firing in the advisory gate. Prefixed so a deny can never
// share a marker with an advisory kind of the same name.
func denyMarker(rule string) hint.MarkerKind {
	return hint.MarkerKind("deny-" + rule)
}

// denial is a refusal in the two parts a rule words it in.
type denial struct {
	// Say is the verdict printed inline: one sentence naming the problem, carrying at
	// most one command.
	Say string
	// Why is the rationale, kept only in the stored full verdict.
	Why string
}

// refused reports whether the rule refused at all.
func (d denial) refused() bool { return d.Say != "" }

// full is the whole refusal, for a caller with nowhere to store the rationale.
func (d denial) full() string {
	if d.Why == "" {
		return d.Say
	}
	return d.Say + "\n" + d.Why
}

// verdictParts splits a reason into its verdict and its rationale. A rule that words its
// refusal as one string puts the verdict on its first line and the rationale after it, so
// that line is the verdict; a rule that sets why has already split it.
func verdictParts(reason, why string) denial {
	if why != "" {
		return denial{Say: reason, Why: why}
	}
	say, rest, _ := strings.Cut(reason, "\n")
	return denial{Say: say, Why: strings.TrimLeft(rest, "\n")}
}

// shapeDeny words a deny from rule for this session, returning the reason to show and the
// grd ref the full verdict is stored under. Every firing stores and cites one, the first
// included, so a reader can reopen any refusal it was shown, not only a repeated one.
//
// reason and why are the rule's verdict and rationale (see verdictParts). note is the
// nothing-ran line for the command, shown when the verdict did not already carry it. An
// advisory rule, or one the catalog does not list, keeps its whole reason inline: it has
// no page to cite and no one-line summary to repeat.
//
// Every failure speaks in full. A firing that cannot store the verdict it points at would
// cite a ref that resolves to nothing, and a long reason beats a dead end. A preview, the
// dry run of a call, stores nothing by design: it shows what the call would, less the ref.
//
// remedy is the rule's own next, already graded for the acting lease. The stored verdict
// carries all of it with each command's why, and the inline text its first command alone,
// on every firing, since the command is what a reader acts on. It is returned as served,
// and nil for a rule with no page.
func shapeDeny(ctx context.Context, markers hint.Gate, rule, reason, why, note string, remedy []hint.Next, preview bool) (shown, ref string, served []hint.Next) {
	// The tier, not the compiled default: a recoverable rule a workspace sets to deny
	// refuses with its page and remedy like any other deny.
	doc, ok := Rule(rule)
	if !ok || advisoryRule()[rule] {
		return denial{Say: reason, Why: why}.full(), "", nil
	}
	d := verdictParts(reason, why)
	// A rule that already carried the note shows it once, after the verdict.
	if line := strings.TrimPrefix(note, "\n"); line != "" {
		d.Say = strings.TrimSpace(strings.Replace(d.Say, line, "", 1))
		d.Why = strings.TrimSpace(strings.Replace(d.Why, line, "", 1))
	}
	see := "\nsee: " + ruleDocsBase + rule + "/"
	stored := d.Say + note
	if d.Why != "" {
		stored += "\n" + d.Why
	}
	stored += strings.TrimSuffix(hint.Render(remedy, func(n hint.Next) string { return n.Why }), "\n") + see
	command := ""
	if len(remedy) > 0 {
		command = strings.TrimSuffix(hint.Render(remedy[:1], func(hint.Next) string { return "" }), "\n")
	}
	if preview {
		return d.Say + note + command, "", remedy
	}
	first := !markers.MarkFired(denyMarker(rule))
	ref, _ = trail.WriteBlob(ctx, markers.CacheDir(), verdictRefPrefix, []byte(stored))
	if ref == "" {
		hint.AppendServedNext(markers.CacheDir(), remedy)
		return stored, "", remedy
	}
	next := hint.NextForDenial(ref)
	hint.AppendServedNext(markers.CacheDir(), append(slices.Clone(remedy), next))
	lead := d.Say
	if !first {
		lead = "denied again [" + rule + "]: " + doc.Catches
	}
	return lead + note + command + "\nfull verdict: " + next.Run, ref, remedy
}
