package guard

import (
	"context"
	"strings"

	"github.com/egladman/magus/internal/hint"
	"github.com/egladman/magus/internal/trail"
)

// How a catalogued deny is worded the second time it fires in a session.
//
// A refusal still explains itself every time, but not in full every time. The first
// firing of a rule carries its whole reason; a repeat carries one line naming the rule and
// what it catches, plus a ref holding the full text. The reader who declined the argument
// once is not persuaded by reading it again, and a repeat nobody reads around is the
// point: the ref is there for the reader who wants it, and its uptake is counted.
//
// "nothing ran" survives on both forms. Chained edits ahead of a denied command were
// re-run on the assumption that they had happened, and a repeat is exactly where a reader
// skims.

// ruleDocsBase is where every catalogued rule has a page, generated by cmd/magus-ruledocs.
const ruleDocsBase = "https://eli.gladman.cc/magus/reference/rules/"

// verdictRefPrefix names a stored guard verdict in the shared ref namespace, beside out
// (a run's output) and mcp (an MCP payload).
const verdictRefPrefix = "grd"

// denyMarker keys a rule's first firing in the advisory gate. Prefixed so a deny can never
// share a marker with an advisory kind of the same name.
func denyMarker(rule string) hint.MarkerKind {
	return hint.MarkerKind("deny-" + rule)
}

// shapeDeny words a deny from rule for this session, returning the reason to show and the
// grd ref of the full verdict when the short form was chosen.
//
// note is the nothing-ran line for the command, appended to the full form when the rule
// that refused did not already carry it. A rule the catalog does not list as a deny keeps
// its reason untouched: it has no page to cite and no one-line summary to repeat.
//
// Every failure speaks in full. A repeat that cannot store the verdict it points at would
// cite a ref that resolves to nothing, and a long reason beats a dead end.
func shapeDeny(ctx context.Context, markers hint.Gate, rule, reason, note string) (shown, ref string) {
	doc, ok := Rule(rule)
	if !ok || doc.Decision != "deny" {
		return reason, ""
	}
	see := "\nsee: " + ruleDocsBase + rule + "/"
	full := reason
	if note != "" && !strings.Contains(full, note) {
		full += note
	}
	full += see
	if !markers.MarkFired(denyMarker(rule)) {
		return full, ""
	}
	ref, _ = trail.WriteBlob(ctx, markers.CacheDir(), verdictRefPrefix, []byte(full))
	if ref == "" {
		return full, ""
	}
	next := hint.NextForDenial(ref)
	hint.AppendServedNext(markers.CacheDir(), []hint.Next{next})
	return "denied again [" + rule + "]: " + doc.Catches + note + "\nfull verdict: " + next.Run + see, ref
}
