package guard

import (
	"context"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"

	"github.com/bmatcuk/doublestar/v4"
	"github.com/egladman/magus"
	"github.com/egladman/magus/internal/agent"
	"github.com/egladman/magus/internal/config"
	"github.com/egladman/magus/internal/hint"
	"github.com/egladman/magus/internal/job"
	"github.com/egladman/magus/internal/notes"
	"github.com/egladman/magus/internal/trail"
	"github.com/egladman/magus/types"
)

// The path surface of `magus session hook`: every rule that judges a file an edit is
// about to write. The order they speak in is Judge's, not theirs, so each answers
// only about the path it was handed and returns "" when it has nothing to say. The
// command surface is internal/guard/shell.go.

// adviseGeneratedWrite explains why editing path is wasted effort, or "" when
// there is nothing to say. Not a heuristic: magus knows every target's declared
// outputs, so a role=output path is generated by definition.
//
// It teaches rather than blocks: a hand-edited generated file is wasteful, not
// destructive. Silent on every uncertainty, because an advisory fired on a guess
// trains the reader to ignore it.
func adviseGeneratedWrite(ctx context.Context, deps Dependencies, path string) string {
	path = strings.TrimSpace(path)
	if path == "" {
		return ""
	}
	// No root override: FindRoot walks up from the CWD, which is where the hook
	// runs, so a nested project resolves to its own workspace.
	ws, err := deps.inspect(ctx, "")
	if err != nil || ws == nil {
		return ""
	}
	// A cancelled ctx folds into the same silent-on-uncertainty contract as the
	// error above: this advisory has no error path of its own.
	files, err := ws.ClassifyFiles(ctx, []string{path})
	if err != nil || len(files) != 1 || files[0].Role != "output" {
		return ""
	}
	f := files[0]
	owner := f.Project
	if owner == "" {
		owner = "."
	}
	return fmt.Sprintf("magus workspace: edit the SOURCE instead, then %s and commit the regenerated file with your source change.\n"+
		"%s is a DECLARED OUTPUT of project %s. magus read the target's declared globs, so the next run overwrites whatever you write there.\n"+
		"`"+hint.DescribeFile.With("<path>")+"` classifies any path. Load the magus-vcs-hygiene skill if not already loaded.", regenerateAdvice(f, owner), f.Path, owner)
}

// regenerateAdvice names the target that rewrites the path, resolved from the
// declaration that claimed it.
//
// Never a canonical name: a target called "generate" is this repository's
// convention, and the guard ships in a binary that judges workspaces which name
// their codegen anything at all. A project-wide or spell-supplied output glob
// carries no target (FileClaim.Target is empty there), so that case routes to
// discovery rather than guessing.
//
// The CLAIM's project, not the owner: a cross-project write is attributed to the
// tree it lands in by FileEntry.Project and to the declarer by FileClaim.Project,
// and only the declarer can regenerate it.
//
// Several targets may declare the same output glob, and the order the claims arrive in
// is the extractor's. The pick is sorted by project then target so the same path always
// advises the same command: WHICH of them is named does not matter, since any of them
// regenerates the file, but an answer that changes between two runs of the same guard
// does.
func regenerateAdvice(f types.FileEntry, owner string) string {
	producers := make([]types.FileClaim, 0, len(f.Claims))
	for _, c := range f.Claims {
		if c.Role == "output" && c.Target != "" {
			producers = append(producers, c)
		}
	}
	if len(producers) == 0 {
		return "run the target that produces it: `" + hint.DescribeTargets.String() + "` lists what this workspace defines"
	}
	slices.SortFunc(producers, func(a, b types.FileClaim) int {
		if n := strings.Compare(a.Project, b.Project); n != 0 {
			return n
		}
		return strings.Compare(a.Target, b.Target)
	})
	producer := producers[0].Project
	if producer == "" {
		producer = owner
	}
	return "run `" + hint.Run.With(producers[0].Target, producer) + "`"
}

// workspaceDeclaresNotes reports whether THIS repository's own magus.yaml declares a shared
// notes store. A read failure reports false, degrading to the on-disk check rather than
// denying writes in a workspace whose intent cannot be read.
func workspaceDeclaresNotes(root string) bool {
	cfg, err := config.LoadWorkspaceOnly(root)
	if err != nil {
		return false
	}
	return strings.TrimSpace(cfg.Knowledge.Notes.Shared) != ""
}

// denyNotesWrite blocks a write into the workspace's declared notes store, or returns ""
// for every other path.
//
// The only DENY on the path surface, and it fits neither standing trigger: a note in git is
// recoverable, and `magus memory put` is not an equal substitute, since memory is user-local
// while notes are shared. The trigger is a third one: a note is the one thing in the graph
// nothing in the repository corroborates, so its only provenance is the person who wrote it,
// and one agent-written note costs a reader the ability to trust ANY note without checking
// blame.
//
// Silent unless the store is DECLARED, and on a host with no pre-write file hook the deny
// arrives after the write has landed, which its template records as deny=human.
func denyNotesWrite(deps Dependencies, writePath string) string {
	path := strings.TrimSpace(writePath)
	if path == "" {
		return ""
	}
	declared := strings.TrimSpace(deps.NotesShared)
	if declared == "" {
		return ""
	}
	root, err := magus.FindRoot("")
	if err != nil {
		return ""
	}
	dir, err := notes.Dir(root, notes.ScopeShared, declared)
	if err != nil {
		return ""
	}
	// The opt-in is the repository's OWN magus.yaml, and it holds from the moment the key is
	// committed. Gating on the directory existing instead let an agent author the store's
	// FIRST note (measured 2026-08-13, a write to notes/<name>.md passed), after which the
	// deny switched on and protected the forgery it had just admitted.
	//
	// A declaration from anywhere else (an explicit --config, user-global) is in effect in
	// every workspace on the machine, so that one still needs the store to exist, or one
	// setting would deny writes in repos that never opted in.
	if !workspaceDeclaresNotes(root) {
		if st, err := os.Stat(dir); err != nil || !st.IsDir() {
			return ""
		}
	}
	abs := path
	if !filepath.IsAbs(abs) {
		abs = filepath.Join(root, abs)
	}
	// Compare REAL paths. A host hands over whatever path its editor tool used, and on
	// macOS /var is a symlink to /private/var, so a tmpdir-rooted workspace yields a
	// declared store under one spelling and an incoming write under the other. Comparing
	// them literally makes the rule silently pass: a deny that fails open is worse than
	// no deny, because it looks enforced.
	rel, err := filepath.Rel(resolveSymlinks(dir), resolveSymlinks(filepath.Clean(abs)))
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return ""
	}
	return fmt.Sprintf("magus workspace: recording a DECISION ABOUT THIS WORKSPACE? Use `"+hint.MemoryPut.With("<name>")+"`, the agent-writable store. If it genuinely belongs in the notes, say so and let the person run `"+hint.NotesEdit.String()+" %s`.\n"+
		"%s is in this workspace's NOTES store, which only a person may write: a note is the one thing in the graph the repository cannot corroborate later, so its only provenance is the human who signed the commit.\n"+
		"Read the store with `"+hint.NotesLs.String()+"` and `"+hint.NotesGet.With("<name>")+"`.", strings.TrimSuffix(filepath.Base(path), ".md"), path)
}

// resolveSymlinks canonicalizes as much of path as exists, returning it unchanged when
// nothing can be resolved. The file being judged has not been written yet, so the deepest
// EXISTING ancestor is what can be resolved; the remainder is appended verbatim.
func resolveSymlinks(path string) string {
	rest := ""
	for cur := path; ; {
		if real, err := filepath.EvalSymlinks(cur); err == nil {
			return filepath.Join(real, rest)
		}
		parent := filepath.Dir(cur)
		if parent == cur {
			return path // nothing along the way exists; compare what we were given
		}
		rest = filepath.Join(filepath.Base(cur), rest)
		cur = parent
	}
}

// Where the acting lease's identity comes from. Both spellings name the same thing so a
// harness can pick whichever it can set: a wrapper that builds an argv passes the flag, and a
// worker that only inherits an environment exports the W3C baggage member.
//
// envHookLease is the ASSIGNMENT a person would type, not a variable name, because that
// is what the advisories below hand them: BAGGAGE carries a list, so naming the variable alone
// would tell a reader to set it to a bare id and produce a value no baggage parser accepts.
const (
	flagHookLease = "lease"
	envHookLease  = trail.EnvBaggage + "=" + trail.BaggageLease
)

// writeGrade is what the lease ledger has to say about one write. Separate from
// Verdict because the empty Decision means "no opinion", which the wire's "pass"
// does not: a rule that stayed silent and a rule that cleared the write are different
// facts, and only the first may be overridden by a later rule.
type writeGrade struct {
	Decision string // "", "deny", or "advise"
	Reason   string
	Context  string
	// Kind names an advisory held to one firing per session (internal/guard/advisory.go), and is
	// empty for the ledger advisories that report a live collision: those describe THIS
	// write against a boundary that moves, so the second one is a second fact.
	Kind hint.MarkerKind
}

// gradeLeasedWrite judges a file write against the lease ledger's declared write
// boundaries, and says nothing at all when no fleet is running.
//
// The ledger RECORDS and the guard ENFORCES. That split is deliberate (internal/ledger's
// package doc argues it): a store that quietly gated writes would become something agents
// route around, while a guard denial is loud, names the owning lease, and teaches. This is
// the reader that turns those declared facts into a verdict, and the only one.
//
// The lease id is the ONLY thing here that reads any of the propagation channels. The
// trace context a spawning tool claims alongside it is attribution and never a verdict's input.
//
// It is a SEATBELT FOR COOPERATING HARNESSES, NOT A SANDBOX. An un-enrolled writer (a
// person editing their own repo with no baggage set) is advised and never blocked.
// magus cannot tell "not part of the fleet" from "part of it and not saying so", and of
// the two ways to be wrong, blocking a human in their own checkout is the one that must
// not happen.
//
// Every uncertainty fails OPEN with at most an advisory: no ledger, no live leases, a file
// that will not parse, a path outside the workspace. A rule the guard cannot evaluate must
// not block a tool call.
func gradeLeasedWrite(ctx context.Context, deps Dependencies, actingLease, writePath string) writeGrade {
	writePath = strings.TrimSpace(writePath)
	if writePath == "" {
		return writeGrade{}
	}
	location := hookLocation(ctx, deps)
	if location.cacheDir == "" {
		return writeGrade{}
	}
	leases, err := leaseRows(ctx, location)
	if err != nil {
		// An ABSENT ledger is not this branch: the store reads it as an empty one, which
		// falls through to the no-live-leases return below and costs a stat. Only a file
		// that exists and will not parse arrives here, and it is worth a word, because a
		// lease whose boundary silently stopped being checked looks exactly like one
		// nobody declared.
		return writeGrade{Decision: "advise", Context: fmt.Sprintf(
			"magus workspace: no lease boundary was checked for this write. Re-declare the plan with the "+hint.ToolLedger.String()+" tool if leased work is meant to be running.\n"+
				"This workspace's lease ledger could not be read: %v. The guard fails open rather than blocking on a file it cannot parse, so an owned-path collision would pass unnoticed until someone reads the diff.", err)}
	}
	live := liveLeases(leases)
	if len(live) == 0 {
		return adviseUnleasedWorker(actingLease)
	}
	rel, inside := workspaceRelative(location.workspace, writePath)
	if !inside {
		// The ledger's paths are workspace-relative, so a write outside the workspace has
		// nothing to be graded against.
		return writeGrade{}
	}

	// An id magus cannot parse is one it cannot look up either, so it is graded as absent.
	// The notice that says so is adviseInvalidLease, fired from Judge so both surfaces
	// get it.
	if !types.ValidJobID(actingLease) {
		actingLease = ""
	}

	if me, enrolled := liveLease(live, actingLease); enrolled {
		return gradeAgainstOwnLease(me, live, rel)
	}
	// An id that is valid but names no LIVE row lands here too, and that is the intent: a
	// lease whose plan already ended has no boundary left to grade against, and denying on
	// one would block work whose ledger row is simply stale.
	owner, owned, err := ownerOf(live, rel, "")
	if err != nil {
		return adviseMalformedDeclaration(err)
	}
	if owned {
		// Recorded as well as reported, so the lease whose file just moved can find out by
		// asking the ledger. Telling only the writer left the one party who needed it (the agent
		// still holding a stale read of this path) as the only party never informed.
		//
		// Best-effort by construction: a failure here is swallowed, because this whole function
		// fails open and a ledger that would not accept a note must not cost somebody a save.
		_ = job.NewStore(job.Location{CacheDir: location.cacheDir, Root: location.workspace}).
			RecordUnattributedWrite(ctx, owner.ID, rel)
		return writeGrade{Decision: "advise", Context: fmt.Sprintf(
			"magus workspace: if you are lease %s, set %s=%s (or pass --lease %s) so the guard grades your writes; if you are not, expect a concurrent agent to be editing this file and coordinate before you save.\n"+
				"%s is inside the paths lease %s (%s) declared it owns, and that lease is %s. This is an advisory and not a deny: the guard is a seatbelt for harnesses that opt in, not a sandbox, so an editor magus cannot attribute is never stopped from writing its own repository.",
			owner.ID, envHookLease, owner.ID, owner.ID, rel, owner.ID, goalLine(owner), owner.State)}
	}
	return writeGrade{}
}

// adviseUnleasedWorker teaches a spawned worker how to enroll, and says nothing to
// anybody else.
//
// The trigger is a process that carries SPAWN ANCESTRY (a parent span id in TRACEPARENT,
// meaning some tool started it deliberately) writing a file while naming no lease, in a
// workspace whose ledger holds no live row to grade it against. That is the fleet running
// unrecorded: the orchestrator's plan exists nowhere, so no boundary can be checked, no
// collision can be reported, and nothing says which base the work applies to.
//
// The ancestry is a CLAIM, and internal/trail's Spawn doc is the rule it obeys: no verdict
// may key on any of it. This one does not. It can only ever turn SILENCE into an advisory,
// it can never deny, and it can never clear or change what another rule decided: the
// caller reaches this line only after every grading path has already declined to speak. A
// process that lies about its ancestry buys itself one paragraph of teaching.
//
// A person editing their own repository carries no traceparent, which is what keeps this
// off a human's screen. So does an already-enrolled worker: naming a lease is the whole
// thing being asked for.
func adviseUnleasedWorker(actingLease string) writeGrade {
	if actingLease != "" || trail.SpawnFromEnv().ParentSpanID == "" {
		return writeGrade{}
	}
	return writeGrade{Decision: "advise", Kind: advisoryUnleasedWrite, Context: fmt.Sprintf(
		"magus workspace: declare the plan with the "+hint.ToolLedger.String()+" tool and export %s=<lease id> in each worker, so the guard can grade these writes against a declared boundary.\n"+
			"This process reports a spawner but names no lease, and this workspace's ledger holds no live one. Nothing records who owns which paths, so two workers editing one file is invisible until somebody reads the diff, and no checkpoint says which revision the work applies to.\n"+
			"This is an advisory and never a block: the spawn chain is a claim the environment makes, so it may teach and may not judge. Load the magus-multi-agent skill for how a plan is partitioned.", envHookLease)}
}

// gradeAgainstOwnLease judges a write made by a lease that IS in the live set.
//
// A deny path beats a write path, because a denied entry inside a leased tree is the more
// specific of two declarations the same orchestrator wrote. A write outside a DECLARED
// write set is denied whether or not another lease claims the path: the set is the lane
// the orchestrator handed out, and a worker that widens its own lane is the failure the
// declaration exists to catch. An EMPTY write set is not a lane of size zero, it is a
// boundary nobody declared, so it scopes nothing.
func gradeAgainstOwnLease(me types.Job, live []types.Job, rel string) writeGrade {
	// Ahead of the registration rule below: a read-only lease has no base to register for
	// a write it is not supposed to be making, so asking it to checkpoint first and then
	// denying the write anyway would be two refusals for one mistake.
	if me.ReadOnly {
		return writeGrade{Decision: "deny", Reason: fmt.Sprintf(
			"magus workspace: put what you found in your report instead of writing it. "+leaseActorClause("clear read_only and declare write_paths for lease "+me.ID)+"\n"+
				"Lease %s (%s) is declared read_only, so it has no write boundary at all and %s is outside it. The declaration is the orchestrator's, recorded in this workspace's ledger; magus is reading it back, not inventing a rule.",
			me.ID, goalLine(me), rel)}
	}
	// BEFORE the path checks, because an unregistered lease should not be writing anywhere,
	// not merely outside its lane. A checkpoint is what says which base the work applies to and
	// what makes its diff locatable afterwards (it records a revision and a patch DIGEST, so it
	// never makes the work recoverable), and both facts are worth nothing recorded afterwards.
	//
	// This is the one rule here that enforces a PROCEDURE rather than a boundary, and it is a deny
	// rather than an advisory for the reason the skill was not enough: an instruction an agent can
	// skip is an instruction that gets skipped, and the record it was meant to leave is missing
	// exactly when somebody needs to recover from it. A human is unaffected: they never name a
	// lease, so they never reach this function at all.
	if me.Registered == 0 {
		return writeGrade{Decision: "deny", Reason: fmt.Sprintf(
			"magus workspace: run `"+hint.VCSCheckpoint.With("-o", "name")+"` in this tree and register what it prints with the "+hint.ToolLedger.String()+" tool (op register, lease %s), then retry this write.\n"+
				"Lease %s (%s) has not registered the base it landed on, so nothing records which revision your work applies to. Without it a reviewer cannot tell your changes from the ones already there, and a recovery cannot tell where to start.",
			me.ID, me.ID, goalLine(me))}
	}
	decl, denied, err := declarationCovering(me.DenyPaths, rel)
	if err != nil {
		return adviseMalformedDeclaration(fmt.Errorf("lease %s: %w", me.ID, err))
	}
	if denied {
		return writeGrade{Decision: "deny", Reason: fmt.Sprintf(
			"magus workspace: work inside your own write paths, or report a checkpoint to the orchestrator and ask for the boundary to be widened before you touch this.\n"+
				"%s is covered by %q, which your lease %s (%s) declared DENIED. The declaration is the orchestrator's, recorded in this workspace's ledger; magus is reading it back, not inventing a rule.",
			rel, decl, me.ID, goalLine(me))}
	}
	_, mine, err := declarationCovering(me.WritePaths, rel)
	if err != nil {
		return adviseMalformedDeclaration(fmt.Errorf("lease %s: %w", me.ID, err))
	}
	if mine {
		// Advisory rather than a block: an orchestrator may have rebased the plan deliberately,
		// and magus cannot tell that from a worker that wandered. What it can do is refuse to let
		// the divergence stay silent until the merge finds it.
		if me.BaseVerdict == types.BaseDiverged {
			return writeGrade{Decision: "advise", Context: fmt.Sprintf(
				"magus workspace: re-checkpoint and re-register if you moved on purpose; otherwise reconcile with the orchestrator before writing more.\n"+
					"Lease %s registered on %s, which is not the checkpoint it was handed (%s). You are working from a different base than the plan assumes, so your changes may not apply where it expects them.",
				me.ID, me.ReportedBase, me.Checkpoint)}
		}
		return writeGrade{}
	}
	owner, owned, err := ownerOf(live, rel, me.ID)
	if err != nil {
		return adviseMalformedDeclaration(err)
	}
	if owned {
		return writeGrade{Decision: "deny", Reason: fmt.Sprintf(
			"magus workspace: edit inside your own write paths. "+leaseActorClause("re-partition the plan, or release the path once lease "+owner.ID+" has finished with it")+"\n"+
				"%s is owned by lease %s (%s), which is %s right now, and you are lease %s. Two agents editing one path is the collision the lease ledger exists to make visible; this guard is where the declaration gets read.",
			rel, owner.ID, goalLine(owner), owner.State, me.ID)}
	}
	if len(me.WritePaths) == 0 {
		return writeGrade{}
	}
	return writeGrade{Decision: "deny", Reason: fmt.Sprintf(
		"magus workspace: write inside the paths lease %s was given (%s). "+leaseActorClause("widen this lane")+"\n"+
			"%s is outside every entry in the write_paths lease %s (%s) declared. The declaration is the orchestrator's, recorded in this workspace's ledger; magus is reading it back, not inventing a rule.",
		me.ID, strings.Join(me.WritePaths, ", "), rel, me.ID, goalLine(me))}
}

// liveLeases are the rows a write can still collide with: declared and running.
// A terminal row has stopped competing for its paths, which is the same rule
// types.leaseOverlaps applies when it decides which pairs to report. A row with no
// state at all is not live either: it has not said it is.
func liveLeases(leases []types.Job) []types.Job {
	live := make([]types.Job, 0, len(leases))
	for _, u := range leases {
		if u.State == types.StateDeclared || u.State == types.StateRunning {
			live = append(live, u)
		}
	}
	return live
}

// liveLease finds the acting lease's own row. An empty id matches nothing, so an
// un-enrolled caller cannot collide with a row whose id was never written.
func liveLease(live []types.Job, id string) (types.Job, bool) {
	if id == "" {
		return types.Job{}, false
	}
	i := slices.IndexFunc(live, func(u types.Job) bool { return u.ID == id })
	if i < 0 {
		return types.Job{}, false
	}
	return live[i], true
}

// ownerOf finds the live lease whose write paths cover rel, skipping the id in exclude.
//
// Ledger order breaks ties. Two leases declaring one path is an overlap the ledger already
// reports as a fact, and naming the first-recorded one keeps the guard's answer stable
// between two runs over the same file: an answer that changes run to run is one nobody
// can act on.
func ownerOf(live []types.Job, rel, exclude string) (types.Job, bool, error) {
	for _, u := range live {
		if u.ID == exclude {
			continue
		}
		_, ok, err := declarationCovering(u.WritePaths, rel)
		if err != nil {
			return types.Job{}, false, fmt.Errorf("lease %s: %w", u.ID, err)
		}
		if ok {
			return u, true, nil
		}
	}
	return types.Job{}, false, nil
}

// declarationCovering reports which declaration covers rel, and whether any did. rel is
// workspace-relative and slash-separated, as the ledger's declarations are.
//
// A declaration covers the SUBTREE beneath what it names, which is what an orchestrator
// means by writing "internal/ledger" into a plan. That is the second Match call: appending
// "/**" is the same trick internal/file/watch uses to reach a glob's descendants.
//
// Deliberately NOT types.pathsIntersect. That one compares two DECLARATIONS and
// over-reports on purpose, truncating each to its literal prefix, so "console/src/**/*.ts"
// and "console/src/**/*.css" read as overlapping. Over-reporting is right for a fact a
// human reads and wrong here, where the answer denies a write: a guard that blocks
// legitimate edits is one agents learn to route around, and routing around it is the
// failure the whole ledger design is built to avoid.
// A declaration the matcher cannot read is surfaced only when nothing else matched, never
// in place of a real match: a valid "src/**" that covers rel still denies even if an earlier
// entry was a malformed pattern. Swallowing the error entirely let a deny path spelled
// with a stray bracket stop denying; short-circuiting on the first error would let one bad
// entry mask a valid sibling that should deny. So a match wins, and an unreadable pattern is
// reported as the residual uncertainty only when no declaration covered the path.
func declarationCovering(decls []string, rel string) (string, bool, error) {
	var firstErr error
	for _, raw := range decls {
		decl := path.Clean(strings.TrimSpace(raw))
		if decl == "." || decl == "/" {
			// A blank entry, or one that names the whole tree by naming nothing, would put
			// its lease on every path in the plan. types.pathsIntersect refuses the same
			// entry for the same reason. An explicit "**" is a different thing and stands.
			continue
		}
		ok, err := doublestar.Match(decl, rel)
		if err != nil {
			if firstErr == nil {
				firstErr = fmt.Errorf("%q: %w", raw, err)
			}
			continue
		}
		if ok {
			return raw, true, nil
		}
		ok, err = doublestar.Match(decl+"/**", rel)
		if err != nil {
			if firstErr == nil {
				firstErr = fmt.Errorf("%q: %w", raw, err)
			}
			continue
		}
		if ok {
			return raw, true, nil
		}
	}
	return "", false, firstErr
}

// adviseMalformedDeclaration reports a boundary the guard could not check. An advisory
// rather than a deny, like every other uncertainty here: a pattern magus cannot read says
// nothing about whether this write is legitimate, only that nothing graded it.
func adviseMalformedDeclaration(err error) writeGrade {
	return writeGrade{Decision: "advise", Context: fmt.Sprintf(
		"magus workspace: fix the path pattern with the "+hint.ToolLedger.String()+" tool, then retry this write.\n"+
			"A declared lease path could not be matched (%v), so that boundary was not checked. The guard fails open on a pattern it cannot read, which means a write or deny path spelled this way is not being enforced at all.", err)}
}

// workspaceRelative resolves an incoming path to a workspace-relative, slash-separated
// one, reporting false when it lands outside the workspace.
//
// Symlinks are resolved on BOTH sides, for the reason denyNotesWrite records: a host hands
// over whatever path its editor tool used, and on macOS a tmpdir-rooted workspace yields
// the root under one spelling and the write under another. Comparing them literally makes
// the rule silently pass, and a deny that fails open is worse than no deny, because it
// looks enforced.
func workspaceRelative(root, p string) (string, bool) {
	if root == "" {
		return "", false
	}
	abs := p
	if !filepath.IsAbs(abs) {
		abs = filepath.Join(root, abs)
	}
	rel, err := filepath.Rel(resolveSymlinks(root), resolveSymlinks(filepath.Clean(abs)))
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return "", false
	}
	return filepath.ToSlash(rel), true
}

// goalLine is the lease's goal reduced to its first line. Goal holds the goal AND its
// acceptance criteria as one block (see types.Job), and pasting all of that
// into a denial would bury the next step under it.
func goalLine(u types.Job) string {
	line, _, _ := strings.Cut(strings.TrimSpace(u.Goal), "\n")
	if line == "" {
		return "no goal recorded"
	}
	return line
}

// adviseMemoryWrite nudges a magus-domain decision toward `magus memory put`
// when the write lands in a cross-host instruction file, or "" otherwise.
//
// Capture, not replication: host instructions belong in the file. The point is
// that a decision ABOUT THE WORKSPACE outlives a per-checkout, per-host file, so
// the advisory names both destinations rather than arguing against one.
func adviseMemoryWrite(path string) string {
	// Matched as a bare filename stem, which is the sanctioned form: these name
	// well-known files on disk rather than branching on which host is running.
	// The .md check keeps a template or a sibling extension (agents.md.tmpl,
	// agents.mdx) out of it.
	base := strings.ToLower(filepath.Base(strings.TrimSpace(path)))
	if filepath.Ext(base) != ".md" {
		return ""
	}
	switch strings.TrimSuffix(base, ".md") {
	case "agents", "claude":
	default:
		return ""
	}
	return "magus workspace: recording a DECISION ABOUT THIS WORKSPACE (a target, a saved query, an output ref, a doc)? Put it in the repository's memory too: `" + hint.MemoryPut.With("<name>") + "`.\n" +
		"This file is per-host and per-checkout, so a second worktree or a different agent host never sees it. Host instructions belong right where you are writing them; workspace decisions outlive the file. Load the magus-memory skill if not already loaded."
}

// adviseInstalledSkillWrite explains that an installed skill is generated, or
// "" when the path is not one. The other path advisories catch a write that is
// wasted; this one catches a write that DISAPPEARS: `magus doctor` reports it
// as drift and the next `install --force` erases it.
//
// The STAMP is the discriminator, not the path: a workspace's own skill sits in
// the same directory, and telling an author their file is generated would be
// worse than saying nothing.
//
// Unreachable in magus's own tree, which is worth knowing before hunting a bug:
// this repo declares its installed skills as outputs, so adviseGeneratedWrite
// claims the path first and can name the producing target.
func adviseInstalledSkillWrite(path string) string {
	clean := filepath.ToSlash(strings.TrimSpace(path))
	if filepath.Base(clean) != "SKILL.md" {
		return ""
	}
	installed := false
	for _, dir := range agent.WellKnownSkillDirs() {
		if strings.Contains(clean, dir+"/") {
			installed = true
			break
		}
	}
	if !installed {
		return ""
	}
	body, err := os.ReadFile(path)
	if err != nil || !strings.Contains(string(body), "source: magus") {
		return ""
	}
	return "magus workspace: put rules that belong to THIS workspace in a local skill beside the installed ones, in a directory magus does not ship (conventionally magus-local-development), which install and verify both leave alone.\n" +
		"That file is an INSTALLED skill, generated from magus's embedded sources and stamped with a content digest: `" + hint.Doctor.String() + "` reports your edit as stale rather than reading it, and the next `" + hint.AgentInstall.With("<dir>", "--force") + "` overwrites it.\n" +
		"Stamp each rule with its evidence and the condition that retires it. Load the magus-workspace-rules skill for the format."
}

// The two rules below name paths, a skill, and a target that belong to magus's OWN
// checkout. A shipped verdict may not normally do that: a workspace calls its targets
// whatever it likes, and asserting magus's vocabulary over somebody else's tree is the
// mistake runGuardContextFor exists to avoid. magusOwnSourceTree is what makes them
// legitimate: outside this repository neither rule can fire at all, so neither can be
// wrong there.

// magusOwnSourceTree reports whether the working directory is a checkout of magus's own
// sources.
//
// The same identification staleGuardNotice makes, moved from the binary's directory to the
// working directory: these rules judge the tree being EDITED rather than the one the binary
// was built from, and in a worktree those are routinely different checkouts.
func magusOwnSourceTree() bool {
	for _, marker := range []string{"magusfile.buzz", filepath.Join("cmd", "magus"), filepath.Join("internal", "agent")} {
		if _, err := os.Stat(marker); err != nil {
			return false
		}
	}
	return true
}

// agentSurfaceSources are the files an edit to what agents are TAUGHT lands in: the
// shipped skill bodies, the MCP registry that names what an agent may call, and the
// hint sources that name the tools and commands hints steer agents toward.
var agentSurfaceSources = []string{
	"internal/agent/skills/",
	"internal/handler/mcp/registry.go",
	"internal/hint/mcptool.go",
	"internal/hint/clicommand.go",
}

// adviseAgentSurfaceWrite routes an edit to the agent surface through the method that
// maintains it, or returns "" for every other path.
//
// The gap it closes is the one the authoring method itself names: both failures here are
// silent. A skill body is a text/template rendered per form, so a passage added
// outside a branch changes both and a passage added inside one changes neither, and
// nothing about the file says so. A content change without a SkillVersion bump leaves
// every install reporting itself up to date while carrying the previous bytes.
func adviseAgentSurfaceWrite(path string) string {
	rel, ok := workspaceRelativeFile(path)
	if !ok || !magusOwnSourceTree() {
		return ""
	}
	if !slices.ContainsFunc(agentSurfaceSources, func(s string) bool {
		return rel == s || strings.HasPrefix(rel, s)
	}) {
		return ""
	}
	return "magus workspace: load the magus-skill-authoring skill before editing this. It is hand-authored, committed beside the installed skills, and it holds the method these files are maintained by.\n" +
		rel + " is a SOURCE of what agents are taught. Both ways to get it wrong here are silent: a skill body is a template, so a passage lands in one form, both, or neither depending on the branch it sits in, and a content change with no SkillVersion bump leaves every install reporting itself up to date while carrying the old bytes.\n" +
		"Verify against a freshly built binary rather than against the docs. That is the method's first rule, and it is there because the registry once advertised a dry run that regenerated files."
}

// adviseDescriptorWrite catches an edit to a GENERATOR INPUT, or returns "" for every
// other path.
//
// Deliberately not the declared-output rule inverted. adviseGeneratedWrite fires on the
// file the generator writes, which is the wasted edit; this fires on the file that makes
// that output stale, which is the omitted one. The failure is the same shape as every
// other advisory here (silent), because a stale generated file looks exactly like a file
// nobody had to touch, right up until CI runs generate as a drift gate.
func adviseDescriptorWrite(path string) string {
	rel, ok := workspaceRelativeFile(path)
	if !ok || !magusOwnSourceTree() {
		return ""
	}
	switch {
	case strings.HasPrefix(rel, "proto/") && strings.HasSuffix(rel, ".proto"):
	// A Buzz host module descriptor sits directly in std/; a test beside it feeds no
	// generator, and a subdirectory is a module's implementation rather than its surface.
	case strings.HasPrefix(rel, "std/") && strings.HasSuffix(rel, ".go") &&
		!strings.HasSuffix(rel, "_test.go") && !strings.Contains(strings.TrimPrefix(rel, "std/"), "/"):
	default:
		return ""
	}
	return "magus workspace: regenerate in the SAME commit as this edit. Run `" + hint.Run.With("generate", ".") + "` once the source change is settled, and commit the source and the regenerated files together.\n" +
		rel + " is a GENERATOR INPUT, so an edit here moves files nobody types into. Measured: a one-word rename in a std/ descriptor left four generated files stale and three tests red across three commits. CI runs generate as a drift gate, so splitting them is also a red build you did not have to have.\n" +
		"`" + hint.DescribeFile.With("<path>") + "` says whether a path is generated and by what. Load the magus-vcs-hygiene skill for the commit checklist."
}

// workspaceRelativeFile returns path relative to the working directory, slash-separated,
// and whether it lands inside it.
//
// The file's sibling to workspaceRelativeDir, which the new-directory rule uses, and it
// resolves the same way for the same reason: the host sends an absolute path and this
// workspace is routinely checked out under a dot-directory, so a rule that matched the
// absolute form would be silently disabled in the layout this repository's own workflow
// uses.
func workspaceRelativeFile(path string) (string, bool) {
	clean := strings.TrimSpace(path)
	if clean == "" {
		return "", false
	}
	cwd, err := os.Getwd()
	if err != nil {
		return "", false
	}
	abs := clean
	if !filepath.IsAbs(abs) {
		abs = filepath.Join(cwd, abs)
	}
	rel, err := filepath.Rel(cwd, abs)
	if err != nil {
		return "", false
	}
	rel = filepath.ToSlash(rel)
	if rel == "." || rel == ".." || strings.HasPrefix(rel, "../") {
		return "", false
	}
	return rel, true
}
