package buzzgen

import (
	"bytes"
	"fmt"
	"go/format"
	"reflect"
	"strings"
	"time"
)

// RuntimeOptions configure the generated Go encoder methods.
type RuntimeOptions struct {
	Options
	// Package is the Go package clause of the emitted file.
	Package string
	// Method is the encoder method's name (e.g. "BuzzObject").
	Method string
	// ObjectType is the map type the method returns, as written in the emitted file
	// (e.g. "BuzzObject" when it is declared in Package, or "types.BuzzObject" when it
	// is not). It must be a named map[string]any.
	ObjectType string
	// Banner is the generated-file marker, without the leading "// ". It should name
	// the HOST's generator rather than this package, because the reader who opens the
	// file needs to know which command regenerates it. Defaults to "Code generated by
	// buzzgen. DO NOT EDIT."
	Banner string
}

// RuntimeMethods emits the runtime half of the Go-to-Buzz boundary: one encoder method
// per type, turning a Go value into the named map the VM reads.
//
// The methods contain ordinary field reads, so the host binary never pays for reflection
// when a value crosses at run time - the reflection happens here, once, at generate time.
func RuntimeMethods(types []reflect.Type, opts RuntimeOptions) ([]byte, error) {
	var methods bytes.Buffer
	r := runtimeRenderer{b: &methods, opts: opts}
	for _, rt := range types {
		if err := r.method(rt); err != nil {
			return nil, err
		}
	}

	banner := opts.Banner
	if banner == "" {
		banner = "Code generated by buzzgen. DO NOT EDIT."
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// %s\n\npackage %s\n", banner, opts.Package)
	if r.usesTime {
		fmt.Fprint(&b, "\nimport \"time\"\n")
	}
	fmt.Fprintln(&b)
	b.Write(methods.Bytes())
	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated encoder methods: %w", err)
	}
	return out, nil
}

type runtimeRenderer struct {
	b        *bytes.Buffer
	opts     RuntimeOptions
	usesTime bool
}

func (r *runtimeRenderer) method(rt reflect.Type) error {
	fmt.Fprintf(r.b, "func (v %s) %s() %s {\n", rt.Name(), r.opts.Method, r.opts.ObjectType)
	fields, err := r.fields(rt)
	if err != nil {
		return err
	}
	fmt.Fprintf(r.b, "\treturn %s{\n", r.opts.ObjectType)
	for _, f := range fields {
		fmt.Fprintf(r.b, "\t\t%q: %s,\n", f.name, f.expr)
	}
	fmt.Fprintln(r.b, "\t}")
	fmt.Fprintln(r.b, "}")
	fmt.Fprintln(r.b)
	return nil
}

type runtimeField struct{ name, expr string }

func (r *runtimeRenderer) fields(rt reflect.Type) ([]runtimeField, error) {
	var out []runtimeField
	for i := 0; i < rt.NumField(); i++ {
		f := rt.Field(i)
		if !f.IsExported() || f.Tag.Get("buzz") == "-" {
			continue
		}
		if f.Anonymous && f.Type.Kind() == reflect.Struct && f.Tag.Get("buzz") == "" {
			return nil, fmt.Errorf("%s: embedded boundary fields need an explicit generated representation", rt.Name())
		}
		expr, err := r.value("v."+f.Name, f.Name, f.Type)
		if err != nil {
			return nil, fmt.Errorf("%s.%s: %w", rt.Name(), f.Name, err)
		}
		out = append(out, runtimeField{name: MemberName(f), expr: expr})
	}
	return out, nil
}

// MemberName is the runtime map key for a field. It deliberately differs from FieldName:
// that one emits @"type" for DECLARATION syntax, while the runtime map must carry the
// actual member key, "type".
func MemberName(f reflect.StructField) string {
	name := f.Tag.Get("buzz")
	if name == "" {
		name = strings.ToLower(f.Name[:1]) + f.Name[1:]
	}
	return name
}

// value renders the expression for one field, emitting any temporaries it needs first.
// path names the field being rendered ("AffectedProjects", and "AffectedProjectsItem"
// one level into its element) and is what every temporary is named after. See tempName.
func (r *runtimeRenderer) value(value, path string, t reflect.Type) (string, error) {
	if r.opts.TimeAsString && t == reflect.TypeOf(time.Time{}) {
		r.usesTime = true
		name := tempName("formatted", path)
		fmt.Fprintf(r.b, "\t%s := \"\"\n", name)
		fmt.Fprintf(r.b, "\tif !%s.IsZero() {\n\t\t%s = %s.Format(time.RFC3339)\n\t}\n", value, name, value)
		return name, nil
	}
	switch t.Kind() {
	case reflect.String:
		// A NAMED string keeps its own Go type inside the map[string]any, and a decoder
		// type-switches on IDENTITY - so `case string` does not match it and the field
		// crosses as null. Convert here; a plain string is emitted bare rather than as
		// string(s), which is the redundant conversion unconvert exists to catch.
		if t != reflect.TypeOf("") {
			return "string(" + value + ")", nil
		}
		return value, nil
	case reflect.Map:
		if t.Key().Kind() != reflect.String {
			return "", fmt.Errorf("map key %s is not a string", t.Key())
		}
		// Identity, not Kind: a map of NAMED strings is not map[string]string to a Go
		// type switch, for the same reason as the String case above.
		if t.Elem() == reflect.TypeOf("") {
			return value, nil
		}
		out, key, item := tempName("mapped", path), tempName("key", path), tempName("item", path)
		fmt.Fprintf(r.b, "\t%s := make(map[string]any, len(%s))\n", out, value)
		fmt.Fprintf(r.b, "\tfor %s, %s := range %s {\n", key, item, value)
		expr, err := r.value(item, path+"Value", t.Elem())
		if err != nil {
			return "", err
		}
		fmt.Fprintf(r.b, "\t\t%s[%s] = %s\n\t}\n", out, key, expr)
		return out, nil
	case reflect.Slice, reflect.Array:
		if t.Elem() == reflect.TypeOf("") {
			return value, nil
		}
		out, index := tempName("items", path), tempName("index", path)
		fmt.Fprintf(r.b, "\t%s := make([]any, len(%s))\n", out, value)
		fmt.Fprintf(r.b, "\tfor %s := range %s {\n", index, value)
		expr, err := r.value(value+"["+index+"]", path+"Item", t.Elem())
		if err != nil {
			return "", err
		}
		fmt.Fprintf(r.b, "\t\t%s[%s] = %s\n\t}\n", out, index, expr)
		return out, nil
	case reflect.Struct:
		return value + "." + r.opts.Method + "()", nil
	case reflect.Pointer:
		// An optional field: nil crosses as null, which is what the mirror declares it
		// as. Emitted as a nil-checked temporary rather than an inline expression
		// because the element may itself need statements (a time needs formatting, a
		// struct needs its own encoder call).
		out := tempName("opt", path)
		fmt.Fprintf(r.b, "\tvar %s any\n", out)
		fmt.Fprintf(r.b, "\tif %s != nil {\n", value)
		expr, err := r.value("(*"+value+")", path, t.Elem())
		if err != nil {
			return "", err
		}
		fmt.Fprintf(r.b, "\t\t%s = %s\n\t}\n", out, expr)
		return out, nil
	default:
		return value, nil
	}
}

// tempName builds a temporary's identifier from the field path rather than a running
// counter. A counter makes every temporary after an inserted field shift by one, so
// adding a single field rewrites the rest of the file and the real change is lost in the
// renumbering. Naming after the path keeps a temporary stable under edits elsewhere and
// says what it holds: itemsAffectedProjects, not items61.
//
// path is always an exported field name, extended with Item/Value per nesting level, so
// it needs no case fixing. That is not quite a uniqueness proof - a field Foo [][]X and a
// sibling literally named FooItem derive the same temporary - but nesting puts the inner
// one inside the loop's braces, and a genuine same-scope collision is a Go redeclaration
// error in generated code, not a silent miscompile.
func tempName(prefix, path string) string { return prefix + path }
