// Package host is the host↔Buzz boundary: it owns how the std host-binding
// descriptors (std.Module/Method/Field) project onto the Buzz VM, in both
// directions and at both build and run time. It is the hand-written half; the
// generated per-module trampolines live in the gen subpackage.
//
//   - This package (hand-written): the value marshalling the trampolines call
//     (Str, AnyMapVal, ValueToAny, …, in helpers.go) and the surface convention
//     shared by the generator, docs-gen, and `magus describe` — the snake→camel
//     name transform (CamelCase), the Buzz call-signature renderer (BuzzSignature),
//     the Buzz-stdlib cross-reference (BuzzStdlibEquiv), and Impl-name
//     reflection.
//   - The gen subpackage (host/gen): only the per-module trampolines
//     (os.go, fs.go, …), generated by magus-utils bindings (-lang buzz); see the
//     //go:generate directives in std/*.go. It imports this package for marshalling.
//
// Naming: host names stay snake_case in Buzz (read_file → read_file), matching
// the magusfile DSL. Multi-return Impls return a Buzz list [ret0, ret1, ...];
// host errors propagate as Buzz runtime errors.
package host
