// Code generated by magus-utils enums. DO NOT EDIT.

package types

// Values lists the SignAlgorithm values a caller may choose, excluding the zero value.
func (v SignAlgorithm) Values() []string { return []string{"ed25519"} }

// Valid reports whether v is a declared SignAlgorithm. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v SignAlgorithm) Valid() bool {
	switch v {
	case "", "ed25519":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v SignAlgorithm) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the TermStyle values a caller may choose, excluding the zero value.
func (v TermStyle) Values() []string {
	return []string{"1", "2", "31", "32", "33", "2;32", "2;37", "1;32"}
}

// Valid reports whether v is a declared TermStyle. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v TermStyle) Valid() bool {
	switch v {
	case "", "1", "2", "31", "32", "33", "2;32", "2;37", "1;32":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v TermStyle) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the TimeLayout values a caller may choose, excluding the zero value.
func (v TimeLayout) Values() []string {
	return []string{"2006-01-02T15:04:05Z07:00", "2006-01-02T15:04:05.999999999Z07:00", "2006-01-02", "15:04:05", "2006-01-02 15:04:05", "Mon, 02 Jan 2006 15:04:05 MST", "3:04PM"}
}

// Valid reports whether v is a declared TimeLayout. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v TimeLayout) Valid() bool {
	switch v {
	case "", "2006-01-02T15:04:05Z07:00", "2006-01-02T15:04:05.999999999Z07:00", "2006-01-02", "15:04:05", "2006-01-02 15:04:05", "Mon, 02 Jan 2006 15:04:05 MST", "3:04PM":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v TimeLayout) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the LogLevel values a caller may choose, excluding the zero value.
func (v LogLevel) Values() []string { return []string{"trace", "debug", "info", "warn", "error"} }

// Valid reports whether v is a declared LogLevel. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v LogLevel) Valid() bool {
	switch v {
	case "", "trace", "debug", "info", "warn", "error":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v LogLevel) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the PlatformStyle values a caller may choose, excluding the zero value.
func (v PlatformStyle) Values() []string { return []string{"go", "uname"} }

// Valid reports whether v is a declared PlatformStyle. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v PlatformStyle) Valid() bool {
	switch v {
	case "", "go", "uname":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v PlatformStyle) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the DoctorCheckStatus values a caller may choose, excluding the zero value.
func (v DoctorCheckStatus) Values() []string { return []string{"ok", "fail", "advice"} }

// Valid reports whether v is a declared DoctorCheckStatus. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v DoctorCheckStatus) Valid() bool {
	switch v {
	case "", "ok", "fail", "advice":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v DoctorCheckStatus) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the EventOutcome values a caller may choose, excluding the zero value.
func (v EventOutcome) Values() []string {
	return []string{"waiting", "permission", "failed", "finished", "diagnostic", "update", "other"}
}

// Valid reports whether v is a declared EventOutcome. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v EventOutcome) Valid() bool {
	switch v {
	case "", "waiting", "permission", "failed", "finished", "diagnostic", "update", "other":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v EventOutcome) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the EventSeverity values a caller may choose, excluding the zero value.
func (v EventSeverity) Values() []string { return []string{"info", "notice", "warning", "critical"} }

// Valid reports whether v is a declared EventSeverity. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v EventSeverity) Valid() bool {
	switch v {
	case "", "info", "notice", "warning", "critical":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v EventSeverity) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the ServiceState values a caller may choose, excluding the zero value.
func (v ServiceState) Values() []string { return []string{"starting", "running", "idle", "failed"} }

// Valid reports whether v is a declared ServiceState. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v ServiceState) Valid() bool {
	switch v {
	case "", "starting", "running", "idle", "failed":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v ServiceState) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the PatternType values a caller may choose, excluding the zero value.
func (v PatternType) Values() []string { return []string{"glob", "regex", "literal"} }

// Valid reports whether v is a declared PatternType. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v PatternType) Valid() bool {
	switch v {
	case "", "glob", "regex", "literal":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v PatternType) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the SymbolIndexFreshness values a caller may choose, excluding the zero value.
func (v SymbolIndexFreshness) Values() []string {
	return []string{"up-to-date", "out-of-date", "not-indexed"}
}

// Valid reports whether v is a declared SymbolIndexFreshness. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v SymbolIndexFreshness) Valid() bool {
	switch v {
	case "", "up-to-date", "out-of-date", "not-indexed":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v SymbolIndexFreshness) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the TargetRunState values a caller may choose, excluding the zero value.
func (v TargetRunState) Values() []string {
	return []string{"queued", "running", "passed", "failed", "cached"}
}

// Valid reports whether v is a declared TargetRunState. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v TargetRunState) Valid() bool {
	switch v {
	case "", "queued", "running", "passed", "failed", "cached":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v TargetRunState) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the VCSSource values a caller may choose, excluding the zero value.
func (v VCSSource) Values() []string { return []string{"explicit", "auto", "default", "disabled"} }

// Valid reports whether v is a declared VCSSource. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v VCSSource) Valid() bool {
	switch v {
	case "", "explicit", "auto", "default", "disabled":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v VCSSource) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the ConflictKind values a caller may choose, excluding the zero value.
func (v ConflictKind) Values() []string { return []string{"content", "deleted", "both-deleted"} }

// Valid reports whether v is a declared ConflictKind. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v ConflictKind) Valid() bool {
	switch v {
	case "", "content", "deleted", "both-deleted":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v ConflictKind) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}
