// Subcommand `bindings` emits per-VM trampoline code from std.Module
// declarations. The generated file registers the module's methods on a backend
// Session: decode args, call the Impl in the host package, encode results.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"strings"

	"github.com/egladman/magus/host"
	"github.com/egladman/magus/std"
)

// wasmExcludedModules names the host modules whose generated trampolines are
// tagged //go:build !wasm: the IO leaves (process, filesystem, network, env, vcs,
// and the magus meta-module) whose std Impls don't compile for wasm, so the
// browser playground never registers them. Keep in sync with the //go:build !wasm
// tags on the matching std/<name>.go files and with dry.WASMCompatibleMagusModules
// (whose complement this is).
var wasmExcludedModules = map[string]bool{
	"fs":      true,
	"os":      true,
	"http":    true,
	"archive": true,
	"vcs":     true,
	"magus":   true,
}

func runBindings(args []string) error {
	fs := flag.NewFlagSet("bindings", flag.ExitOnError)
	moduleName := fs.String("module", "", "module name to generate (e.g. fs)")
	lang := fs.String("lang", "buzz", "codegen target: buzz")
	outPath := fs.String("out", "", "output file path")
	if err := fs.Parse(args); err != nil {
		return err
	}

	if *moduleName == "" || *outPath == "" {
		return fmt.Errorf("usage: magus-utils bindings -module <name> -lang buzz -out <path>")
	}

	m, ok := std.Get(*moduleName)
	if !ok {
		return fmt.Errorf("unknown module %q", *moduleName)
	}

	if *lang != "buzz" {
		return fmt.Errorf("unknown lang %q (have: buzz)", *lang)
	}
	out, err := emitBuzz(m)
	if err != nil {
		return fmt.Errorf("emit: %w", err)
	}
	if err := os.WriteFile(*outPath, out, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", *outPath, err)
	}
	return nil
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	if s[0] >= 'a' && s[0] <= 'z' {
		return string(s[0]-'a'+'A') + s[1:]
	}
	return s
}

func registerName(module string) string {
	return "Register" + titleCase(module)
}

func goLiteral(v any) string {
	switch x := v.(type) {
	case nil:
		return "nil"
	case string:
		return fmt.Sprintf("%q", x)
	case int:
		return fmt.Sprintf("%d", x)
	case int64:
		return fmt.Sprintf("%d", x)
	case float64:
		return fmt.Sprintf("%g", x)
	case bool:
		if x {
			return "true"
		}
		return "false"
	}
	return fmt.Sprintf("%#v", v)
}

// emitBuzz emits the Buzz trampolines for module m into package gen (host/gen):
// one Register<Module>(ctx, sess) that builds a buzz map of DirectValue closures.
// Buzz closures return (Value, error) natively, so host errors propagate as a Buzz
// runtime error instead of a panic. Method names stay snake_case to match the
// magusfile DSL; multi-return Impls yield a list.
//
// It emits directly against the concrete magus/gopherbuzz value system, calling
// the marshalling helpers in the parent host package; see the registerAllBuzz doc
// in interp/bindings/buzz.go for the full rationale.
func emitBuzz(m std.Module) ([]byte, error) {
	// Build the func body first, then derive the import set from what it uses:
	// std (Impls/resolvers) and host (marshalling) appear only when the body
	// references them, so an unused import can't sneak in.
	var body bytes.Buffer

	regFn := registerName(m.Name)
	fmt.Fprintf(&body, "// %s builds the %q module map and returns it.\n", regFn, m.Name)
	if m.Doc != "" {
		fmt.Fprintf(&body, "// %s\n", m.Doc)
	}
	fmt.Fprintf(&body, "func %s(ctx context.Context, sess *buzz.Session) vm.Value {\n", regFn)
	fmt.Fprintln(&body, "\t_ = ctx")
	fmt.Fprintln(&body, "\t_ = sess")
	fmt.Fprintln(&body, "\tm := vm.NewMap()")

	for _, f := range m.Fields {
		emitBuzzField(&body, f)
	}
	for _, meth := range m.Methods {
		emitBuzzMethod(&body, m, meth)
	}

	fmt.Fprintln(&body, "\treturn m")
	fmt.Fprintln(&body, "}")

	var b bytes.Buffer
	// The IO-heavy modules (fs/os/http/archive/env/vcs/magus) call std functions
	// that are themselves excluded from the wasm build, so their trampolines can't
	// compile there; tag them off wasm to match. The browser playground registers
	// only the pure-compute modules (dry.WASMCompatibleMagusModules), which stay in
	// every build.
	if wasmExcludedModules[m.Name] {
		fmt.Fprintln(&b, "//go:build !wasm")
		fmt.Fprintln(&b)
	}
	fmt.Fprintln(&b, "// Code generated by magus-utils bindings. DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package gen")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `import (`)
	fmt.Fprintln(&b, `	"context"`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `	buzz "github.com/egladman/gopherbuzz"`)
	fmt.Fprintln(&b, `	vm "github.com/egladman/gopherbuzz/vm"`)
	if bytes.Contains(body.Bytes(), []byte("host.")) {
		fmt.Fprintln(&b, `	"github.com/egladman/magus/host"`)
	}
	if bytes.Contains(body.Bytes(), []byte("std.")) {
		fmt.Fprintln(&b, `	"github.com/egladman/magus/std"`)
	}
	fmt.Fprintln(&b, `)`)
	fmt.Fprintln(&b)
	b.Write(body.Bytes())

	out, err := format.Source(b.Bytes())
	if err != nil {
		// Return nil on failure: the unformatted buffer is known-bad Go.
		return nil, fmt.Errorf("gofmt: %w\n--- source ---\n%s", err, b.String())
	}
	return out, nil
}

// emitBuzzField resolves a static field once and stores it on the module map.
// The key is camelCased (Buzz convention) though the std descriptor is snake_case.
func emitBuzzField(w *bytes.Buffer, f std.Field) {
	callArgs := ""
	if host.FieldResolverTakesCtx(f) {
		callArgs = "ctx"
	}
	fmt.Fprintf(w, "\tif v, err := std.%s(%s); err == nil {\n", host.FieldFuncName(f), callArgs)
	fmt.Fprintf(w, "\t\tm.MapSet(%q, %s)\n", host.CamelCase(f.Name), buzzValConv(f.Type, "v"))
	fmt.Fprintln(w, "\t}")
}

// emitBuzzMethod emits one DirectValue trampoline for meth. The closure's arg
// slice is named bzArgs to avoid colliding with host args named "args". The map
// key is camelCased to match Buzz's convention (the snake_case descriptor name
// stays the runtime label so errors still read e.g. "fs.readFile").
func emitBuzzMethod(w *bytes.Buffer, m std.Module, meth std.Method) {
	name := host.CamelCase(meth.Name)
	if meth.BuzzName != "" {
		name = meth.BuzzName
	}
	fmt.Fprintf(w, "\tm.MapSet(%q, vm.DirectValue(%q, func(ctx context.Context, bzArgs []vm.Value) (vm.Value, error) {\n",
		name, m.Name+"."+name)

	for i, a := range meth.Args {
		emitBuzzArgDecode(w, a, i)
	}

	callArgs := make([]string, 0, 1+len(meth.Args))
	callArgs = append(callArgs, "ctx")
	for _, a := range meth.Args {
		if a.Variadic {
			callArgs = append(callArgs, a.Name+"...")
		} else {
			callArgs = append(callArgs, a.Name)
		}
	}
	callStr := strings.Join(callArgs, ", ")

	switch len(meth.Returns) {
	case 0:
		fmt.Fprintf(w, "\t\tif err := std.%s(%s); err != nil {\n", host.MethodFuncName(meth), callStr)
		fmt.Fprintln(w, "\t\t\treturn vm.Null, err")
		fmt.Fprintln(w, "\t\t}")
		fmt.Fprintln(w, "\t\treturn vm.Null, nil")
	case 1:
		fmt.Fprintf(w, "\t\tret0, err := std.%s(%s)\n", host.MethodFuncName(meth), callStr)
		fmt.Fprintln(w, "\t\tif err != nil {")
		fmt.Fprintln(w, "\t\t\treturn vm.Null, err")
		fmt.Fprintln(w, "\t\t}")
		fmt.Fprintf(w, "\t\treturn %s, nil\n", returnConv(meth.Returns[0].Type, reflect.TypeOf(meth.Impl).Out(0), "ret0"))
	default:
		lhsParts := make([]string, 0, len(meth.Returns)+1)
		for i := range meth.Returns {
			lhsParts = append(lhsParts, fmt.Sprintf("ret%d", i))
		}
		lhsParts = append(lhsParts, "err")
		fmt.Fprintf(w, "\t\t%s := std.%s(%s)\n", strings.Join(lhsParts, ", "), host.MethodFuncName(meth), callStr)
		fmt.Fprintln(w, "\t\tif err != nil {")
		fmt.Fprintln(w, "\t\t\treturn vm.Null, err")
		fmt.Fprintln(w, "\t\t}")
		items := make([]string, len(meth.Returns))
		for i, ret := range meth.Returns {
			items[i] = buzzValConv(ret.Type, fmt.Sprintf("ret%d", i))
		}
		fmt.Fprintf(w, "\t\treturn vm.ListValue([]vm.Value{%s}), nil\n", strings.Join(items, ", "))
	}
	fmt.Fprintln(w, "\t}))")
}

// emitBuzzArgDecode emits the decode statement for arg a at positional index idx.
func emitBuzzArgDecode(w *bytes.Buffer, a std.Arg, idx int) {
	if a.Variadic {
		// Only TypeString variadic is used in practice.
		fmt.Fprintf(w, "\t\t%s := host.VariadicStr(bzArgs, %d)\n", a.Name, idx)
		return
	}
	switch a.Type {
	case std.TypeString:
		fmt.Fprintf(w, "\t\t%s := host.Str(bzArgs, %d)\n", a.Name, idx)
	case std.TypeInt:
		def := "0"
		if a.Optional && a.Default != nil {
			def = goLiteral(a.Default)
		}
		fmt.Fprintf(w, "\t\t%s := host.Int(bzArgs, %d, %s)\n", a.Name, idx, def)
	case std.TypeFloat:
		def := "0"
		if a.Optional && a.Default != nil {
			def = goLiteral(a.Default)
		}
		fmt.Fprintf(w, "\t\t%s := host.Float(bzArgs, %d, %s)\n", a.Name, idx, def)
	case std.TypeIndex:
		// Buzz lists are 0-based, matching the Go Impl; no offset.
		fmt.Fprintf(w, "\t\t%s := host.Int(bzArgs, %d, 0)\n", a.Name, idx)
	case std.TypeBool:
		def := "false"
		if a.Optional && a.Default != nil {
			def = goLiteral(a.Default)
		}
		fmt.Fprintf(w, "\t\t%s := host.Bool(bzArgs, %d, %s)\n", a.Name, idx, def)
	case std.TypeStringSlice:
		fmt.Fprintf(w, "\t\t%s := host.StrSlice(bzArgs, %d)\n", a.Name, idx)
	case std.TypeStringMap:
		fmt.Fprintf(w, "\t\t%s := host.StrMap(bzArgs, %d)\n", a.Name, idx)
	case std.TypeAnyMap:
		fmt.Fprintf(w, "\t\t%s := host.AnyMap(bzArgs, %d)\n", a.Name, idx)
	case std.TypeFunc:
		fmt.Fprintf(w, "\t\t%s := host.CallbackArg(sess, bzArgs, %d)\n", a.Name, idx)
	case std.TypeAny:
		fmt.Fprintf(w, "\t\t%s := host.Any(bzArgs, %d)\n", a.Name, idx)
	default:
		fmt.Fprintf(w, "\t\t%s := host.Any(bzArgs, %d) // unsupported type %s\n", a.Name, idx, a.Type.GoType())
	}
}

// fielderType is the interface a typed record return implements (ToMap() map[string]any).
var fielderType = reflect.TypeOf((*interface{ ToMap() map[string]any })(nil)).Elem()

// returnConv returns the Go expression that converts a method's single return
// (src) to a vm.Value. When the Impl returns a typed record (or a slice of them),
// i.e. its Go type implements ToMap, it marshals via ToMap so the Buzz boundary
// stays the same map a magusfile reads while the Go SDK gets the struct. Otherwise
// it falls back to the TypeTag-driven conversion.
func returnConv(tag std.TypeTag, goType reflect.Type, src string) string {
	switch {
	case goType.Implements(fielderType):
		return "host.AnyMapVal(" + src + ".ToMap())"
	case goType.Kind() == reflect.Slice && goType.Elem().Implements(fielderType):
		return "host.MapsVal(" + src + ")"
	default:
		return buzzValConv(tag, src)
	}
}

// buzzValConv returns the Go expression that converts src (of the given
// TypeTag) to a vm.Value.
func buzzValConv(t std.TypeTag, src string) string {
	switch t {
	case std.TypeString:
		return fmt.Sprintf("host.StrVal(%s)", src)
	case std.TypeInt, std.TypeIndex:
		return fmt.Sprintf("host.IntVal(%s)", src)
	case std.TypeBool:
		return fmt.Sprintf("host.BoolVal(%s)", src)
	case std.TypeFloat:
		return fmt.Sprintf("host.FloatVal(%s)", src)
	case std.TypeStringSlice:
		return fmt.Sprintf("host.StrSliceVal(%s)", src)
	case std.TypeStringMap:
		return fmt.Sprintf("host.StrMapVal(%s)", src)
	case std.TypeAnyMap:
		return fmt.Sprintf("host.AnyMapVal(%s)", src)
	case std.TypeAny:
		return fmt.Sprintf("host.AnyVal(%s)", src)
	default:
		panic(fmt.Sprintf("buzzValConv: unsupported type tag %s for value conversion", t.GoType()))
	}
}
