package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	// Importing the host package triggers all host/*.go init() calls, which
	// register every module (Sh, Fs, Vcs, …) with std.Register.
	"github.com/egladman/magus/std"
)

// buzzModules is the set of modules whose host/gen/*.go files are generated by
// `magus-utils bindings -lang buzz`. magus is excluded (hand-built in
// bindings/buzz.go). Unlike gen/js, charm is pure magus-utils output here.
var buzzModules = []string{
	"os", "vcs", "fs", "archive", "env", "json", "http", "charm",
}

// TestBuzzFilesUpToDate verifies that the checked-in host/gen/<module>.go files
// are byte-for-byte identical to what `magus-utils bindings -lang buzz` would emit today.
func TestBuzzFilesUpToDate(t *testing.T) {
	genBuzzDir := filepath.Join("..", "..", "host", "gen")

	for _, name := range buzzModules {
		t.Run(name, func(t *testing.T) {
			m, ok := std.Get(name)
			require.True(t, ok, "std.Get(%q): module not registered", name)
			want, err := emitBuzz(m)
			require.NoError(t, err, "emitBuzz(%q)", name)
			outPath := filepath.Join(genBuzzDir, name+".go")
			got, err := os.ReadFile(outPath)
			require.NoError(t, err, "read %s", outPath)
			assert.Equal(t, string(want), string(got),
				"%s.go is out of date; re-run:\n  go generate ./std/", name)
		})
	}
}
