package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/egladman/magus/internal/generate/emit"
)

// runBoundaryList emits the list of runtime boundary types, so a test can iterate every
// value that crosses Go -> Buzz instead of naming them by hand.
//
// A hand-maintained list is the failure this prevents. types.DoctorCheckStatus crossed
// as null for an unknown stretch because a type switch matches on identity and no test
// covered every boundary type, and the same trap had already bitten types.BuzzObject
// once. Sourcing the list from the registry that generates the mirrors means a new
// boundary type is covered the moment it is declared.
func runBoundaryList(args []string) error {
	fs := flag.NewFlagSet("boundarylist", flag.ExitOnError)
	outPath := fs.String("out", "", "output Go file path")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *outPath == "" {
		return fmt.Errorf("usage: magus-utils boundarylist -out <path.go>")
	}

	var rows []string
	usesSpells := false
	for _, e := range boundaryTypes {
		if !e.RuntimeObject {
			continue
		}
		t := e.Type
		qualified := t.PkgPath()[len("github.com/egladman/magus/"):] + "." + t.Name()
		if !strings.HasPrefix(qualified, "types.") {
			usesSpells = true
		}
		// The encoder is named after the Go type, matching buzzValueEmitter.funcName.
		// Carried as a closure rather than left for the test to look up: a method could
		// be reached through an interface assertion, and a free function cannot.
		rows = append(rows, fmt.Sprintf("\t{Name: %q, Zero: %s{}, Encode: func(v any) vm.Value { return Object%s(v.(%s)) }},",
			e.Name, qualified, t.Name(), qualified))
	}
	sort.Strings(rows)

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by magus-utils boundarylist. DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package gen")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `import (`)
	fmt.Fprintln(&b, `	vm "github.com/egladman/magus/libs/gopherbuzz/vm"`)
	if usesSpells {
		fmt.Fprintln(&b, `	"github.com/egladman/magus/spells"`)
	}
	fmt.Fprintln(&b, `	"github.com/egladman/magus/types"`)
	fmt.Fprintln(&b, `)`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// RuntimeBoundaryTypes is every value magus encodes for Buzz, zero-valued and paired")
	fmt.Fprintln(&b, "// with its encoder. A test populates each and asserts the round trip loses nothing.")
	fmt.Fprintln(&b, "var RuntimeBoundaryTypes = []BoundaryType{")
	for _, r := range rows {
		fmt.Fprintln(&b, r)
	}
	fmt.Fprintln(&b, "}")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("format boundary list: %w", err)
	}
	return emit.File(*outPath, formatted)
}
