package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"reflect"
	"sort"

	"github.com/egladman/magus/internal/generate/emit"
	"github.com/egladman/magus/internal/hostmodules"
	"github.com/egladman/magus/std"
)

// runBoundaryObjects emits one exported Go-to-Buzz encoder per boundary type, for the
// whole package, into internal/interp/bindings/gen.
//
// It replaced a second generator that wrote the same encoders as METHODS into package
// types. Two generators reading one registry produced two encoders for every field: a
// commit adding one field to KnowledgeAnswer had to add it in both places, and the
// method half had no production caller, because a trampoline inlines the conversion
// and only the hand-bound members reach for an encoder by name.
//
// Emitting here rather than into types also ends a bootstrap deadlock that needed a
// build tag to work around: a generator must not import the package it writes into
// (cmd/magus-utils/job_schema.go states the rule), and the method half had to, since Go
// puts a method in its receiver's package.
func runBoundaryObjects(args []string) error {
	fs := flag.NewFlagSet("boundaryobjects", flag.ExitOnError)
	outPath := fs.String("out", "", "output Go file path")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *outPath == "" {
		return fmt.Errorf("usage: magus-utils boundaryobjects -out <path.go>")
	}

	e := newBuzzValueEmitter()

	// Every type a DECLARED method returns. Module order is sorted so the emitted file
	// is stable under a registration-order change nobody made deliberately.
	mods := hostmodules.All()
	sort.Slice(mods, func(i, j int) bool { return mods[i].Name < mods[j].Name })
	for _, m := range mods {
		for _, meth := range m.Methods {
			if meth.Extern || meth.Impl == nil {
				continue
			}
			if err := emitReturnObjects(e, m, meth); err != nil {
				return err
			}
		}
	}

	// Every type the registry declares as crossing at run time. This is what covers a
	// type no declared method returns: magus\job and magus\describeModule are bound by
	// hand, so their returns are reachable from the registry and nowhere else.
	for _, entry := range boundaryTypes {
		if !entry.RuntimeObject {
			continue
		}
		if err := e.emitStruct(entry.Type); err != nil {
			return fmt.Errorf("boundary type %s: %w", entry.Name, err)
		}
	}

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by magus-utils boundaryobjects. DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package gen")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `import (`)
	fmt.Fprintln(&b, `	vm "github.com/egladman/magus/libs/gopherbuzz/vm"`)
	if e.usesSpells {
		fmt.Fprintln(&b, `	"github.com/egladman/magus/spells"`)
	}
	if e.usesTypes {
		fmt.Fprintln(&b, `	"github.com/egladman/magus/types"`)
	}
	if e.usesTime {
		fmt.Fprintln(&b, `	"time"`)
	}
	fmt.Fprintln(&b, `)`)
	fmt.Fprintln(&b)
	b.Write(e.funcs.Bytes())

	out, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt: %w\n--- source ---\n%s", err, b.String())
	}
	return emit.File(*outPath, out)
}

// emitReturnObjects walks one method's object returns. The Impl's reflected type is the
// authority on the shape; Ret.Object only names it, and checkObjectDecls has already
// proved the two agree.
func emitReturnObjects(e *buzzValueEmitter, m std.Module, meth std.Method) error {
	implOut := reflect.TypeOf(meth.Impl)
	for i, ret := range meth.Returns {
		if ret.Object == "" {
			continue
		}
		if _, err := e.valueFunc(implOut.Out(i), "v"); err != nil {
			return fmt.Errorf("%s\\%s: %w", m.Name, meth.Name, err)
		}
	}
	return nil
}
