package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRunBoundaryList(t *testing.T) {
	args := func(out string) []string { return []string{"-out", out} }

	got := readGenerated(t, runBoundaryList, args)
	assert.Contains(t, got, "// Code generated by magus-utils boundarylist. DO NOT EDIT.")
	assert.Contains(t, got, "package gen")
	assert.Contains(t, got, `"github.com/egladman/magus/types"`)
	assert.Contains(t, got, "var RuntimeBoundaryTypes = []BoundaryType{")
	assert.Contains(t, got, "Zero: types.ExecResult{}, Encode:")

	// A non-runtime entry gets no encoder and must not reach the list.
	assert.NotContains(t, got, "Zero: types.Path{}")

	assertDeterministic(t, runBoundaryList, args)

	t.Run("no -out", func(t *testing.T) {
		err := runBoundaryList(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "usage:")
	})
}
