package main

import (
	"flag"
	"fmt"
	"reflect"

	"github.com/egladman/magus/internal/generate/emit"
	"github.com/egladman/magus/libs/gopherbuzz/buzzgen"
	"github.com/egladman/magus/types"
)

// runBuzzObjects emits the runtime half of the Go-to-Buzz boundary: a BuzzObject()
// method per boundary type. It runs only under go generate; the emitted methods contain
// ordinary field reads, so the magus binary never pays for reflection when a host value
// crosses into Buzz.
//
// The rendering lives in libs/gopherbuzz/buzzgen. What is magus's, and stays here, is
// the registry of which types cross and what each is named on the far side.
func runBuzzObjects(args []string) error {
	fs := flag.NewFlagSet("buzzobjects", flag.ExitOnError)
	outPath := fs.String("out", "", "output Go file path")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *outPath == "" {
		return fmt.Errorf("usage: magus-utils buzzobjects -out <path.go>")
	}

	rts := make([]reflect.Type, 0, len(boundaryTypes))
	for _, entry := range boundaryTypes {
		if entry.RuntimeObject {
			rts = append(rts, entry.Type)
		}
	}

	out, err := buzzgen.RuntimeMethods(rts, buzzgen.RuntimeOptions{
		Options: mirrorOptions(),
		Package: "types",
		Method:  "BuzzObject",
		// Unqualified: the methods are emitted INTO package types, where BuzzObject is
		// declared (types/buzzobject.go).
		ObjectType: reflect.TypeFor[types.BuzzObject]().Name(),
		Banner:     "Code generated by magus-utils buzzobjects. DO NOT EDIT.",
	})
	if err != nil {
		return err
	}
	return emit.File(*outPath, out)
}
