package main

import (
	"errors"
	"flag"
	"fmt"
	"reflect"

	"github.com/egladman/magus/internal/generate/emit"
	"github.com/egladman/magus/libs/gopherbuzz/buzzgen"
	"github.com/egladman/magus/types"
)

// buzzObjectsExcludeTag is the build tag the generated methods are excluded under, and
// the one the go:generate directive in types/buzzobject.go passes to `go run`.
//
// Deliberately not "generate": that is a word a developer might plausibly type, and
// under this tag package types compiles without any of its encoders, which produces
// errors that do not explain themselves.
const buzzObjectsExcludeTag = "magusgen"

// runBuzzObjects emits the runtime half of the Go-to-Buzz boundary: a BuzzObject()
// method per boundary type. It runs only under go generate; the emitted methods contain
// ordinary field reads, so the magus binary never pays for reflection when a host value
// crosses into Buzz.
//
// The rendering lives in libs/gopherbuzz/buzzgen. What is magus's, and stays here, is
// the registry of which types cross and what each is named on the far side.
func runBuzzObjects(args []string) error {
	fs := flag.NewFlagSet("buzzobjects", flag.ExitOnError)
	outPath := fs.String("out", "", "output Go file path")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *outPath == "" {
		return fmt.Errorf("usage: magus-utils buzzobjects -out <path.go>")
	}

	rts := make([]reflect.Type, 0, len(boundaryTypes))
	encodes := make(map[reflect.Type]bool, len(boundaryTypes))
	for _, entry := range boundaryTypes {
		if entry.RuntimeObject {
			rts = append(rts, entry.Type)
			encodes[entry.Type] = true
		}
	}

	out, err := buzzgen.RuntimeMethods(rts, buzzgen.RuntimeOptions{
		Options: mirrorOptions(),
		Package: "types",
		Method:  "BuzzObject",
		// Unqualified: the methods are emitted INTO package types, where BuzzObject is
		// declared (types/buzzobject.go).
		ObjectType: reflect.TypeFor[types.BuzzObject]().Name(),
		Banner:     "Code generated by magus-utils buzzobjects. DO NOT EDIT.",
		// This generator imports types, so its own stale output can stop the package
		// compiling and block the regeneration that would fix it. The tag excludes the
		// output from the generator's build; see buzzgen.RuntimeOptions.ExcludeTag.
		ExcludeTag: buzzObjectsExcludeTag,
		// Registered OR already implementing the method by hand: Path, Commit, Status,
		// DriftResult and EvaluatedProject write their own encoder (they pick a subset
		// of fields, or format a time) and are deliberately absent from the registry.
		// A type that is in neither is one nobody has taught to cross, which is the
		// case worth stopping for.
		Known: func(t reflect.Type) bool {
			_, hasMethod := t.MethodByName("BuzzObject")
			return encodes[t] || hasMethod
		},
	})
	if err != nil {
		return withRegistryHint(err)
	}
	return emit.File(*outPath, out)
}

// withRegistryHint turns buzzgen's "this type has no encoder" into the line to paste.
//
// The remedy is deliberately NOT auto-applied. A type's Buzz name is not derivable from
// its Go name and this registry is where the difference is declared: ProjectsOutput
// crosses as Projects, StatusTargetRun as TargetRun. Registering automatically would
// invent a public Buzz name nobody chose, and silently.
func withRegistryHint(err error) error {
	var unknown *buzzgen.UnknownStructError
	if !errors.As(err, &unknown) {
		return err
	}
	name := unknown.Type.Name()
	return fmt.Errorf("%w\nadd it to boundaryTypes in cmd/magus-utils/boundary_types.go, "+
		"before the type that holds it:\n\t{Name: %q, Type: reflect.TypeFor[%s](), RuntimeObject: true}",
		err, name, unknown.Type.String())
}
