package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"reflect"
	"strings"
	"time"

	"github.com/egladman/magus/internal/generate/emit"
)

// runBuzzObjects emits the runtime half of the Go-to-Buzz boundary. It runs
// only under go generate; the emitted methods contain ordinary field reads, so
// the magus binary never pays for reflection when a host value crosses into Buzz.
func runBuzzObjects(args []string) error {
	fs := flag.NewFlagSet("buzzobjects", flag.ExitOnError)
	outPath := fs.String("out", "", "output Go file path")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *outPath == "" {
		return fmt.Errorf("usage: magus-utils buzzobjects -out <path.go>")
	}

	var methods bytes.Buffer
	renderer := buzzObjectRenderer{b: &methods}
	for _, entry := range boundaryTypes {
		if !entry.RuntimeObject {
			continue
		}
		if err := renderer.method(entry.Type); err != nil {
			return err
		}
	}

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by magus-utils buzzobjects. DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package types")
	if renderer.usesTime {
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "import \"time\"")
	}
	fmt.Fprintln(&b)
	b.Write(methods.Bytes())
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("format generated Buzz object methods: %w", err)
	}
	return emit.File(*outPath, formatted)
}

type buzzObjectRenderer struct {
	b        *bytes.Buffer
	n        int
	usesTime bool
}

func (r *buzzObjectRenderer) method(rt reflect.Type) error {
	fmt.Fprintf(r.b, "func (v %s) BuzzObject() BuzzObject {\n", rt.Name())
	fields, err := r.fields(rt)
	if err != nil {
		return err
	}
	fmt.Fprintln(r.b, "\treturn BuzzObject{")
	for _, field := range fields {
		fmt.Fprintf(r.b, "\t\t%q: %s,\n", field.name, field.expr)
	}
	fmt.Fprintln(r.b, "\t}")
	fmt.Fprintln(r.b, "}")
	fmt.Fprintln(r.b)
	return nil
}

type buzzObjectField struct {
	name string
	expr string
}

func (r *buzzObjectRenderer) fields(rt reflect.Type) ([]buzzObjectField, error) {
	var fields []buzzObjectField
	for i := 0; i < rt.NumField(); i++ {
		f := rt.Field(i)
		if !f.IsExported() || f.Tag.Get("buzz") == "-" {
			continue
		}
		if f.Anonymous && f.Type.Kind() == reflect.Struct && f.Tag.Get("buzz") == "" {
			return nil, fmt.Errorf("%s: embedded Buzz boundary fields need an explicit generated representation", rt.Name())
		}
		expr, err := r.value("v."+f.Name, f.Type)
		if err != nil {
			return nil, fmt.Errorf("%s.%s: %w", rt.Name(), f.Name, err)
		}
		fields = append(fields, buzzObjectField{name: buzzObjectFieldName(f), expr: expr})
	}
	return fields, nil
}

// buzzObjectFieldName is the runtime map key. It deliberately does not use
// buzzFieldName: that helper emits @"type" for Buzz declaration syntax, while
// the runtime object must carry the actual member key, "type".
func buzzObjectFieldName(f reflect.StructField) string {
	name := f.Tag.Get("buzz")
	if name == "" {
		name = strings.ToLower(f.Name[:1]) + f.Name[1:]
	}
	return name
}

func (r *buzzObjectRenderer) value(value string, t reflect.Type) (string, error) {
	if t == reflect.TypeFor[time.Time]() {
		r.usesTime = true
		name := r.name("formatted")
		fmt.Fprintf(r.b, "\t%s := \"\"\n", name)
		fmt.Fprintf(r.b, "\tif !%s.IsZero() {\n\t\t%s = %s.Format(time.RFC3339)\n\t}\n", value, name, value)
		return name, nil
	}
	switch t.Kind() {
	case reflect.Map:
		if t.Key().Kind() != reflect.String {
			return "", fmt.Errorf("map key %s is not a string", t.Key())
		}
		if t.Elem().Kind() == reflect.String {
			return value, nil
		}
		out, key, item := r.name("mapped"), r.name("key"), r.name("item")
		fmt.Fprintf(r.b, "\t%s := make(map[string]any, len(%s))\n", out, value)
		fmt.Fprintf(r.b, "\tfor %s, %s := range %s {\n", key, item, value)
		expr, err := r.value(item, t.Elem())
		if err != nil {
			return "", err
		}
		fmt.Fprintf(r.b, "\t\t%s[%s] = %s\n\t}\n", out, key, expr)
		return out, nil
	case reflect.Slice, reflect.Array:
		if t.Elem().Kind() == reflect.String {
			return value, nil
		}
		out, index := r.name("items"), r.name("index")
		fmt.Fprintf(r.b, "\t%s := make([]any, len(%s))\n", out, value)
		fmt.Fprintf(r.b, "\tfor %s := range %s {\n", index, value)
		expr, err := r.value(value+"["+index+"]", t.Elem())
		if err != nil {
			return "", err
		}
		fmt.Fprintf(r.b, "\t\t%s[%s] = %s\n\t}\n", out, index, expr)
		return out, nil
	case reflect.Struct:
		return value + ".BuzzObject()", nil
	case reflect.Pointer:
		return "", fmt.Errorf("pointer fields need an explicit Buzz boundary representation")
	default:
		return value, nil
	}
}

func (r *buzzObjectRenderer) name(prefix string) string {
	r.n++
	return fmt.Sprintf("%s%d", prefix, r.n)
}
