package main

import (
	"bytes"
	"flag"
	"fmt"
	"sort"
	"strings"

	"github.com/egladman/magus/internal/generate/emit"
	"github.com/egladman/magus/internal/manpage"
)

// runCLIFlags emits a constant per declared CLI flag name.
//
// The names existed only as string literals before this: `magus run` bound "wait"
// in run.go, the man page declared "wait" in its own list, and the code that has to
// recognise the flag later - localOnlyFlags, the pre-parse --detach peek, the REPL's
// "-C applies to the REPL" message - spelled it a third and fourth time. One const
// (detachFlagName) existed and its neighbour on the same line did not, which is the
// shape this is meant to make impossible: a flag name is now declared once, as data,
// and every other mention resolves to it or fails to compile.
//
// Constants are prefixed by command because a bare flag name is not unique -
// no-cache, upstream and depth each appear under several commands - and a shared
// constant would quietly tie two commands' flags together.
func runCLIFlags(args []string) error {
	fs := flag.NewFlagSet("cliflags", flag.ExitOnError)
	out := fs.String("out", "cmd/magus/gen/cli_flags.go", "output file")
	if err := fs.Parse(args); err != nil {
		return err
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by magus-utils cliflags; DO NOT EDIT.\n")
	b.WriteString("package gen\n\n")
	b.WriteString("// Flag names declared by internal/manpage's command registry, one constant\n")
	b.WriteString("// each so a caller never spells a flag as a literal.\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate with: cd magus && go generate ./cmd/magus/...\n")
	b.WriteString("const (\n")

	seen := map[string]string{}
	var lines []string
	for _, c := range manpage.All {
		lines = append(lines, constsFor(c.Name, c.Flags, seen)...)
		for _, child := range c.Children {
			lines = append(lines, constsFor(c.Name+" "+child.Name, child.Flags, seen)...)
		}
	}
	sort.Strings(lines)
	for _, l := range lines {
		b.WriteString(l)
	}
	b.WriteString(")\n")

	return emit.Go(*out, b.Bytes())
}

// constsFor renders one command's flags, skipping a name it has already emitted so
// a command listed twice cannot produce a duplicate declaration.
func constsFor(command string, flags []manpage.Flag, seen map[string]string) []string {
	var out []string
	for _, f := range flags {
		name := "Flag" + goIdent(command) + goIdent(f.Name)
		if prev, dup := seen[name]; dup {
			if prev == f.Name {
				continue
			}
			panic(fmt.Sprintf("cliflags: %s would name both %q and %q", name, prev, f.Name))
		}
		seen[name] = f.Name
		out = append(out, fmt.Sprintf("\t// %s: --%s\n\t%s = %q\n", command, f.Name, name, f.Name))
	}
	return out
}

// goIdent turns a command or flag name into an exported Go identifier fragment:
// "no-default-charms" becomes "NoDefaultCharms", "graph deps" becomes "GraphDeps".
func goIdent(s string) string {
	var b strings.Builder
	for _, part := range strings.FieldsFunc(s, func(r rune) bool { return r == '-' || r == ' ' || r == '_' }) {
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}
