package main

import (
	"bytes"
	"flag"
	"fmt"
	"slices"
	"strings"
	"time"

	"github.com/samber/lo"

	"github.com/egladman/magus/internal/clispec"
	"github.com/egladman/magus/internal/generate/emit"
)

// runCLIFlags emits a constant per declared CLI flag name.
//
// The names existed only as string literals before this: `magus run` bound "wait"
// in run.go, the man page declared "wait" in its own list, and the code that has to
// recognise the flag later - localOnlyFlags, the pre-parse --detach peek, the REPL's
// "-C applies to the REPL" message - spelled it a third and fourth time. One const
// (detachFlagName) existed and its neighbour on the same line did not, which is the
// shape this is meant to make impossible: a flag name is now declared once, as data,
// and every other mention resolves to it or fails to compile.
//
// Constants are prefixed by command because a bare flag name is not unique -
// no-cache, upstream and depth each appear under several commands - and a shared
// constant would quietly tie two commands' flags together.
func runCLIFlags(args []string) error {
	fs := flag.NewFlagSet("cliflags", flag.ExitOnError)
	out := fs.String("out", "cmd/magus/gen/cli_flags.go", "output file")
	if err := fs.Parse(args); err != nil {
		return err
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by magus-utils cliflags; DO NOT EDIT.\n")
	b.WriteString("package gen\n\n")
	b.WriteString("import (\n\t\"flag\"\n\t\"time\"\n)\n\n")
	b.WriteString("// Flag names declared by internal/clispec's command registry, one constant\n")
	b.WriteString("// each so a caller never spells a flag as a literal.\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate with: cd magus && go generate ./cmd/magus/...\n")
	b.WriteString("const (\n")

	seen := map[string]string{}
	var lines []string
	for _, c := range clispec.All {
		lines = append(lines, constsFor(c.Name, c.Flags, seen)...)
		for _, child := range c.Children {
			lines = append(lines, constsFor(c.Name+" "+child.Name, child.Flags, seen)...)
		}
	}
	slices.Sort(lines)
	for _, l := range lines {
		b.WriteString(l)
	}
	b.WriteString(")\n")

	for _, c := range clispec.All {
		for _, mode := range modesOf(c.Flags) {
			name := c.Name
			if mode != "" {
				name += " " + mode
			}
			writeBinder(&b, name, c.Name, flagsForMode(c.Flags, mode))
		}
		for _, child := range c.Children {
			writeBinder(&b, c.Name+" "+child.Name, c.Name+" "+child.Name, child.Flags)
		}
	}

	return emit.Go(*out, b.Bytes())
}

// modesOf lists the distinct sub-modes declared across a command's flags, base
// ("") first. A command whose flags declare no Modes yields just the base, so it
// keeps a single binder.
func modesOf(flags []clispec.Flag) []string {
	out := []string{""}
	seen := map[string]bool{"": true}
	for _, f := range flags {
		for _, m := range f.Modes {
			if !seen[m] {
				seen[m] = true
				out = append(out, m)
			}
		}
	}
	return out
}

// flagsForMode selects the flags one mode accepts: those declaring it, plus (for
// the base) those declaring no mode at all.
func flagsForMode(flags []clispec.Flag, mode string) []clispec.Flag {
	var out []clispec.Flag
	for _, f := range flags {
		if len(f.Modes) == 0 {
			if mode == "" {
				out = append(out, f)
			}
			continue
		}
		for _, m := range f.Modes {
			if m == mode {
				out = append(out, f)
				break
			}
		}
	}
	return out
}

// writeBinder emits the typed struct and the Bind function for one command.
//
// A struct of typed fields rather than a name-keyed lookup, because the hand-written
// binding it replaces already had typed destinations - a local var per flag, passed
// to fs.BoolVar and friends - and a lookup would have made every read site worse to
// buy nothing. The field names are derived from the flag names, so the struct is the
// flag list: adding a flag to the registry adds a field, and removing one breaks
// every read of it at compile time instead of leaving a silently-always-false bool.
// binder names the emitted type and function ("affected plan"); constCommand
// names the command whose constants its flags resolve to ("affected"). They
// differ only for a sub-mode: a mode binds a subset of ONE command's flags, so
// --base is a single FlagAffectedBase however many modes accept it.
func writeBinder(b *bytes.Buffer, command, constCommand string, flags []clispec.Flag) {
	if len(flags) == 0 {
		return
	}
	// A custom-valued flag is declared for the docs and bound by the command
	// itself; emitting a field and a second fs.Var for it would panic at parse
	// time with "flag redefined". Its name constant still comes out, via constsFor.
	bindable := make([]clispec.Flag, 0, len(flags))
	for _, f := range flags {
		if f.Kind != clispec.FlagCustom {
			bindable = append(bindable, f)
		}
	}
	if len(bindable) == 0 {
		return
	}
	groups := groupAliases(command, bindable)

	typeName := goIdent(command) + "Flags"
	fmt.Fprintf(b, "\n// %sFlags are the flags declared for `magus %s`.\ntype %s struct {\n", goIdent(command), command, typeName)
	for _, g := range groups {
		fmt.Fprintf(b, "\t%s %s // %s\n", g.field, goType(g.primary.Kind), g.spellings())
	}
	b.WriteString("}\n\n")

	// Commands with a runtime default take a Defaults argument. Emitted only when one
	// is declared, so the common command keeps a one-argument binder.
	var runtime []aliasGroup
	for _, g := range groups {
		if g.primary.DefaultAtBind {
			runtime = append(runtime, g)
		}
	}
	defaultsType := goIdent(command) + "Defaults"
	param := ""
	if len(runtime) > 0 {
		fmt.Fprintf(b, "// %s carries the defaults `magus %s` resolves at runtime (config, a\n// package constant) rather than declaring as a literal.\ntype %s struct {\n", defaultsType, command, defaultsType)
		for _, g := range runtime {
			fmt.Fprintf(b, "\t%s %s // %s\n", g.field, goType(g.primary.Kind), g.spellings())
		}
		b.WriteString("}\n\n")
		param = ", d " + defaultsType
	}

	fmt.Fprintf(b, "// Bind%s registers `magus %s`'s flags on fs and returns the destination.\nfunc Bind%s(fs *flag.FlagSet%s) *%s {\n\tvar f %s\n", goIdent(command), command, goIdent(command), param, typeName, typeName)
	for _, g := range groups {
		def := flagDefaultLiteral(g.primary)
		if g.primary.DefaultAtBind {
			def = "d." + g.field
		}
		for _, name := range g.names {
			fmt.Fprintf(b, "\tfs.%sVar(&f.%s, %s, %s, %q)\n",
				bindMethod(g.primary.Kind), g.field, "Flag"+goIdent(constCommand)+goIdent(name), def, docFor(flags, name))
		}
	}
	b.WriteString("\treturn &f\n}\n")
}

// aliasGroup is one destination and every flag name that writes to it.
type aliasGroup struct {
	primary clispec.Flag
	names   []string // primary first, then its aliases, in declaration order
	field   string
}

// spellings renders the group's names as a struct-field comment: "--watch, -W".
func (g aliasGroup) spellings() string {
	out := make([]string, 0, len(g.names))
	for _, n := range g.names {
		out = append(out, dashes(n)+n)
	}
	return strings.Join(out, ", ")
}

// dashes picks the prefix a name is actually invoked with. Go's flag package
// accepts either, but a one-character flag is written -c everywhere in this CLI's
// help and docs, and the generated comment should read the way the flag is typed.
func dashes(name string) string {
	if len(name) == 1 {
		return "-"
	}
	return "--"
}

// groupAliases folds each Flag.AliasOf into its primary, so the binder emits one
// destination per group rather than one per name.
//
// Order is the declaration order of the primaries; an alias never introduces a
// group. A dangling or mistyped AliasOf is a panic rather than a silent extra
// field, because the failure it would otherwise produce is a shorthand that parses
// and does nothing - the exact bug this concept was added to prevent.
func groupAliases(command string, flags []clispec.Flag) []aliasGroup {
	index := make(map[string]clispec.Flag, len(flags))
	for _, f := range flags {
		index[f.Name] = f
	}

	var groups []aliasGroup
	at := make(map[string]int, len(flags))
	for _, f := range flags {
		if f.AliasOf != "" {
			continue
		}
		at[f.Name] = len(groups)
		groups = append(groups, aliasGroup{primary: f, names: []string{f.Name}})
	}
	for _, f := range flags {
		if f.AliasOf == "" {
			continue
		}
		primary, ok := index[f.AliasOf]
		if !ok {
			panic(fmt.Sprintf("cliflags: %s --%s is AliasOf %q, which it does not declare", command, f.Name, f.AliasOf))
		}
		if primary.AliasOf != "" {
			panic(fmt.Sprintf("cliflags: %s --%s aliases --%s, which is itself an alias", command, f.Name, f.AliasOf))
		}
		if primary.Kind != f.Kind {
			panic(fmt.Sprintf("cliflags: %s --%s is %s but aliases --%s, which is %s", command, f.Name, f.Kind, f.AliasOf, primary.Kind))
		}
		i := at[f.AliasOf]
		groups[i].names = append(groups[i].names, f.Name)
	}

	// The field is named for the LONGEST spelling in the group, which is the one
	// written to be read: a group of {t, test} yields Test, not T. Naming it after
	// the primary instead would hand the reader f.T at every use site purely because
	// the short form happens to be the one the help text treats as canonical.
	for i, g := range groups {
		longest := g.names[0]
		for _, n := range g.names {
			if len(n) > len(longest) {
				longest = n
			}
		}
		groups[i].field = goIdent(longest)
	}
	return groups
}

// docFor returns the help text declared for one flag name.
func docFor(flags []clispec.Flag, name string) string {
	for _, f := range flags {
		if f.Name == name {
			return f.Doc
		}
	}
	return ""
}

func goType(k clispec.FlagKind) string {
	switch k {
	case clispec.FlagBool:
		return "bool"
	case clispec.FlagInt:
		return "int"
	case clispec.FlagDuration:
		return "time.Duration"
	case clispec.FlagString:
		return "string"
	}
	panic("cliflags: unknown flag kind " + string(k))
}

func bindMethod(k clispec.FlagKind) string {
	switch k {
	case clispec.FlagBool:
		return "Bool"
	case clispec.FlagInt:
		return "Int"
	case clispec.FlagDuration:
		return "Duration"
	case clispec.FlagString:
		return "String"
	}
	panic("cliflags: unknown flag kind " + string(k))
}

// flagDefaultLiteral renders a Flag's default as Go source for the generated binder.
func flagDefaultLiteral(f clispec.Flag) string {
	switch f.Kind {
	case clispec.FlagBool:
		if v, ok := f.Default.(bool); ok && v {
			return "true"
		}
		return "false"
	case clispec.FlagInt:
		if v, ok := f.Default.(int); ok {
			return fmt.Sprintf("%d", v)
		}
		return "0"
	case clispec.FlagDuration:
		if v, ok := f.Default.(time.Duration); ok {
			return fmt.Sprintf("time.Duration(%d)", int64(v))
		}
		return "0"
	case clispec.FlagString:
		if v, ok := f.Default.(string); ok {
			return fmt.Sprintf("%q", v)
		}
		return `""`
	}
	panic("cliflags: unknown flag kind " + string(f.Kind))
}

// constsFor renders one command's flags, skipping a name it has already emitted so
// a command listed twice cannot produce a duplicate declaration.
func constsFor(command string, flags []clispec.Flag, seen map[string]string) []string {
	var out []string
	for _, f := range flags {
		name := "Flag" + goIdent(command) + goIdent(f.Name)
		if prev, dup := seen[name]; dup {
			if prev == f.Name {
				continue
			}
			panic(fmt.Sprintf("cliflags: %s would name both %q and %q", name, prev, f.Name))
		}
		seen[name] = f.Name
		out = append(out, fmt.Sprintf("\t// %s: --%s\n\t%s = %q\n", command, f.Name, name, f.Name))
	}
	return out
}

// initialisms are the words Go spells in full caps, as a subset of the list Go's
// own linters carry (x/lint's commonInitialisms, which staticcheck's ST1003
// inherited), plus the two this workspace's vocabulary adds.
//
// A table rather than a library call because there is no algorithm here: no
// transformation derives "URL" from "url" - it is a convention list, and every
// package that offers this ships the same hardcoded map or asks the caller to
// register one. golang.org/x/text/cases does LANGUAGE casing, and titling "url"
// with it produces "Url", the output this exists to prevent.
//
// It matters more here than in hand-written code because these identifiers are
// EXPORTED constants and struct fields: a generated "Url" cannot be fixed at the
// place it is read.
var initialisms = map[string]string{
	"url": "URL", "vcs": "VCS", "id": "ID", "api": "API",
	"ci": "CI", "json": "JSON", "yaml": "YAML", "tty": "TTY", "mcp": "MCP",
}

// goIdent turns a command or flag name into an exported Go identifier fragment:
// "no-default-charms" becomes "NoDefaultCharms", "graph deps" becomes "GraphDeps".
//
// Splitting and casing come from lo, already a direct dependency, rather than from
// a hand-rolled FieldsFunc: lo.Words also breaks on case and digit boundaries, and
// lo.Capitalize is x/text's English titler, so the only thing left to supply is the
// initialism lookup those cannot know.
//
// lo.Capitalize lowercases the rest of each word, so the one-character flags -c and
// -C collapse to the same fragment; constsFor's panic catches that at generate time
// rather than emitting one constant for two flags.
func goIdent(s string) string {
	var b strings.Builder
	for _, part := range lo.Words(s) {
		if up, ok := initialisms[strings.ToLower(part)]; ok {
			b.WriteString(up)
			continue
		}
		b.WriteString(lo.Capitalize(part))
	}
	return b.String()
}
