package main

import (
	"bytes"
	"flag"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/egladman/magus/internal/generate/emit"
	"github.com/egladman/magus/internal/manpage"
)

// runCLIFlags emits a constant per declared CLI flag name.
//
// The names existed only as string literals before this: `magus run` bound "wait"
// in run.go, the man page declared "wait" in its own list, and the code that has to
// recognise the flag later - localOnlyFlags, the pre-parse --detach peek, the REPL's
// "-C applies to the REPL" message - spelled it a third and fourth time. One const
// (detachFlagName) existed and its neighbour on the same line did not, which is the
// shape this is meant to make impossible: a flag name is now declared once, as data,
// and every other mention resolves to it or fails to compile.
//
// Constants are prefixed by command because a bare flag name is not unique -
// no-cache, upstream and depth each appear under several commands - and a shared
// constant would quietly tie two commands' flags together.
func runCLIFlags(args []string) error {
	fs := flag.NewFlagSet("cliflags", flag.ExitOnError)
	out := fs.String("out", "cmd/magus/gen/cli_flags.go", "output file")
	if err := fs.Parse(args); err != nil {
		return err
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by magus-utils cliflags; DO NOT EDIT.\n")
	b.WriteString("package gen\n\n")
	b.WriteString("import (\n\t\"flag\"\n\t\"time\"\n)\n\n")
	b.WriteString("// Flag names declared by internal/manpage's command registry, one constant\n")
	b.WriteString("// each so a caller never spells a flag as a literal.\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate with: cd magus && go generate ./cmd/magus/...\n")
	b.WriteString("const (\n")

	seen := map[string]string{}
	var lines []string
	for _, c := range manpage.All {
		lines = append(lines, constsFor(c.Name, c.Flags, seen)...)
		for _, child := range c.Children {
			lines = append(lines, constsFor(c.Name+" "+child.Name, child.Flags, seen)...)
		}
	}
	sort.Strings(lines)
	for _, l := range lines {
		b.WriteString(l)
	}
	b.WriteString(")\n")

	for _, c := range manpage.All {
		writeBinder(&b, c.Name, c.Flags)
		for _, child := range c.Children {
			writeBinder(&b, c.Name+" "+child.Name, child.Flags)
		}
	}

	return emit.Go(*out, b.Bytes())
}

// writeBinder emits the typed struct and the Bind function for one command.
//
// A struct of typed fields rather than a name-keyed lookup, because the hand-written
// binding it replaces already had typed destinations - a local var per flag, passed
// to fs.BoolVar and friends - and a lookup would have made every read site worse to
// buy nothing. The field names are derived from the flag names, so the struct is the
// flag list: adding a flag to the registry adds a field, and removing one breaks
// every read of it at compile time instead of leaving a silently-always-false bool.
func writeBinder(b *bytes.Buffer, command string, flags []manpage.Flag) {
	if len(flags) == 0 {
		return
	}
	typeName := goIdent(command) + "Flags"
	fmt.Fprintf(b, "\n// %sFlags are the flags declared for `magus %s`.\ntype %s struct {\n", goIdent(command), command, typeName)
	for _, f := range flags {
		fmt.Fprintf(b, "\t%s %s // --%s\n", goIdent(f.Name), goType(f.Kind), f.Name)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "// Bind%s registers `magus %s`'s flags on fs and returns the destination.\nfunc Bind%s(fs *flag.FlagSet) *%s {\n\tvar f %s\n", goIdent(command), command, goIdent(command), typeName, typeName)
	for _, f := range flags {
		fmt.Fprintf(b, "\tfs.%sVar(&f.%s, %s, %s, %q)\n",
			bindMethod(f.Kind), goIdent(f.Name), "Flag"+goIdent(command)+goIdent(f.Name), flagDefaultLiteral(f), f.Doc)
	}
	b.WriteString("\treturn &f\n}\n")
}

func goType(k manpage.FlagKind) string {
	switch k {
	case manpage.FlagBool:
		return "bool"
	case manpage.FlagInt:
		return "int"
	case manpage.FlagDuration:
		return "time.Duration"
	case manpage.FlagString:
		return "string"
	}
	panic("cliflags: unknown flag kind " + string(k))
}

func bindMethod(k manpage.FlagKind) string {
	switch k {
	case manpage.FlagBool:
		return "Bool"
	case manpage.FlagInt:
		return "Int"
	case manpage.FlagDuration:
		return "Duration"
	case manpage.FlagString:
		return "String"
	}
	panic("cliflags: unknown flag kind " + string(k))
}

// flagDefaultLiteral renders a Flag's default as Go source for the generated binder.
func flagDefaultLiteral(f manpage.Flag) string {
	switch f.Kind {
	case manpage.FlagBool:
		if v, ok := f.Default.(bool); ok && v {
			return "true"
		}
		return "false"
	case manpage.FlagInt:
		if v, ok := f.Default.(int); ok {
			return fmt.Sprintf("%d", v)
		}
		return "0"
	case manpage.FlagDuration:
		if v, ok := f.Default.(time.Duration); ok {
			return fmt.Sprintf("time.Duration(%d)", int64(v))
		}
		return "0"
	case manpage.FlagString:
		if v, ok := f.Default.(string); ok {
			return fmt.Sprintf("%q", v)
		}
		return `""`
	}
	panic("cliflags: unknown flag kind " + string(f.Kind))
}

// constsFor renders one command's flags, skipping a name it has already emitted so
// a command listed twice cannot produce a duplicate declaration.
func constsFor(command string, flags []manpage.Flag, seen map[string]string) []string {
	var out []string
	for _, f := range flags {
		name := "Flag" + goIdent(command) + goIdent(f.Name)
		if prev, dup := seen[name]; dup {
			if prev == f.Name {
				continue
			}
			panic(fmt.Sprintf("cliflags: %s would name both %q and %q", name, prev, f.Name))
		}
		seen[name] = f.Name
		out = append(out, fmt.Sprintf("\t// %s: --%s\n\t%s = %q\n", command, f.Name, name, f.Name))
	}
	return out
}

// goIdent turns a command or flag name into an exported Go identifier fragment:
// "no-default-charms" becomes "NoDefaultCharms", "graph deps" becomes "GraphDeps".
func goIdent(s string) string {
	var b strings.Builder
	for _, part := range strings.FieldsFunc(s, func(r rune) bool { return r == '-' || r == ' ' || r == '_' }) {
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}
