package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const contractSrc = "../../internal/spell/contract.go"

func TestReadContract(t *testing.T) {
	funcs, err := readContract(contractSrc)
	require.NoError(t, err)
	returns := map[string]string{}
	for _, fn := range funcs {
		returns[fn.Name] = fn.Returns
		assert.NotEmpty(t, fn.Doc, "%s has no doc comment, so its reference entry would be empty", fn.Name)
	}
	assert.Equal(t, map[string]string{
		"mgs_getName":           "str",
		"mgs_listRequiredGlobs": "[Path]",
		"mgs_listProvidedGlobs": "[Path]",
		"mgs_listIgnoreDirs":    "[Path]",
		"mgs_listManifests":     "[Manifest]",
		"mgs_listScriptRunners": "[Command]",
		"mgs_getTools":          "{str: Tool}",
		"mgs_getLanguage":       "Language",
		"mgs_getSymbolIndexer":  "SymbolIndexer",
		"mgs_getSandbox":        "Sandbox",
		"mgs_isOpaque":          "bool",
		"mgs_getModeArgs":       "{str: [str]}",
		"mgs_listTargets":       "{str: fun(Target) Command}",
		"mgs_listServices":      "{str: fun(Target) Service}",
	}, returns)
	assert.True(t, funcs[0].Required)
	assert.Equal(t, "Name", funcs[0].Field)
}

func TestReadContractRefuses(t *testing.T) {
	cases := map[string]struct{ src, want string }{
		"an unregistered type": {
			src:  "type Contract struct {\n\tX time.Time `mgs:\"mgs_x\"`\n}",
			want: "time.Time is not a registered boundary type",
		},
		"a missing tag": {
			src:  "type Contract struct {\n\tX string\n}",
			want: "Contract.X has no mgs tag",
		},
		"an unknown option": {
			src:  "type Contract struct {\n\tX string `mgs:\"mgs_x,optional\"`\n}",
			want: `unknown mgs tag option "optional"`,
		},
		"a duplicate function": {
			src:  "type Contract struct {\n\tX string `mgs:\"mgs_x\"`\n\tY string `mgs:\"mgs_x\"`\n}",
			want: "mgs_x is declared twice",
		},
		"a handler that is not a map": {
			src:  "type Contract struct {\n\tX string `mgs:\"mgs_x,handler\"`\n}",
			want: "a handler field is a map",
		},
		"a name without the prefix": {
			src:  "type Contract struct {\n\tX string `mgs:\"getX\"`\n}",
			want: "does not name an mgs_ function",
		},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "contract.go")
			require.NoError(t, os.WriteFile(path, []byte("package spell\n\nimport \"time\"\n\nvar _ time.Time\n\n"+tc.src+"\n"), 0o644))
			_, err := readContract(path)
			require.Error(t, err)
			assert.Contains(t, err.Error(), tc.want)
		})
	}
}

func TestRunContract(t *testing.T) {
	table := readGenerated(t, runContract, func(out string) []string { return []string{"-src", contractSrc, "-out", out} })
	assert.Contains(t, table, "Code generated by magus-utils contract. DO NOT EDIT.")
	assert.Contains(t, table, "package decode")
	assert.Contains(t, table, `{Name: "mgs_getLanguage", Field: "Language", Returns: "Language", Required: false}`)

	page := readGenerated(t, runContract, func(out string) []string { return []string{"-src", contractSrc, "-docs", out} })
	assert.Contains(t, page, "generated_from: internal/spell/contract.go")
	assert.Contains(t, page, "## mgs_listTargets\n\n```buzz\nexport fun mgs_listTargets() > {str: fun(Target) Command}\n```")
	assert.Contains(t, page, "Required. The spell's name")

	assertDeterministic(t, runContract, func(out string) []string { return []string{"-src", contractSrc, "-out", out} })

	t.Run("no -src", func(t *testing.T) {
		err := runContract([]string{"-out", "x.go"})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "usage:")
	})
}
