package main

import (
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"testing"

	"github.com/egladman/magus/internal/hostmodules"
	"github.com/egladman/magus/std"
	"github.com/egladman/magus/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// readGenerated runs one scribe into a fresh path and returns what it wrote.
func readGenerated(t *testing.T, run func([]string) error, args func(out string) []string) string {
	t.Helper()
	out := filepath.Join(t.TempDir(), "out")
	require.NoError(t, run(args(out)))
	body, err := os.ReadFile(out)
	require.NoError(t, err)
	return string(body)
}

// assertDeterministic runs a scribe twice into two distinct paths and compares the
// bytes. Two paths rather than one: emit.File skips an identical write, so rewriting
// the same path would pass without the generator having rendered anything twice.
func assertDeterministic(t *testing.T, run func([]string) error, args func(out string) []string) {
	t.Helper()
	assert.Equal(t,
		readGenerated(t, run, args),
		readGenerated(t, run, args),
		"the generated bytes must not depend on map order; every generate is a drift gate")
}

func TestTitleCaseAndRegisterName(t *testing.T) {
	assert.Equal(t, "Fs", titleCase("fs"))
	assert.Equal(t, "Json", titleCase("json"))
	assert.Equal(t, "", titleCase(""))
	assert.Equal(t, "HTTP", titleCase("HTTP"), "an already-capitalized name is left alone")
	assert.Equal(t, "1st", titleCase("1st"), "a non-letter first byte is left alone")
	assert.Equal(t, "RegisterVcs", registerName("vcs"))
}

func TestGoLiteral(t *testing.T) {
	assert.Equal(t, "nil", goLiteral(nil))
	assert.Equal(t, `"x"`, goLiteral("x"))
	assert.Equal(t, `"a\"b"`, goLiteral(`a"b`))
	assert.Equal(t, "3", goLiteral(3))
	assert.Equal(t, "3", goLiteral(int64(3)))
	assert.Equal(t, "1.5", goLiteral(1.5))
	assert.Equal(t, "true", goLiteral(true))
	assert.Equal(t, "false", goLiteral(false))
	// Anything else falls through to %#v, which is Go syntax for the value.
	assert.Equal(t, "[]int{1}", goLiteral([]int{1}))
}

func TestBoundaryRegistryLookups(t *testing.T) {
	entry, ok := boundaryTypeNamed("ExecResult")
	require.True(t, ok)
	assert.Equal(t, reflect.TypeFor[types.ExecResult](), entry.Type)

	_, ok = boundaryTypeNamed("NotDeclared")
	assert.False(t, ok)

	// The registry key, not the Go name: types.HTTPResponse mirrors as HttpResponse,
	// and emitting the Go name would reference an object nothing declares.
	assert.Equal(t, "HttpResponse", buzzNameFor(reflect.TypeFor[types.HTTPResponse]()))
	// An unregistered type falls back to its own name, which an anonymous struct
	// does not have.
	assert.Equal(t, "", buzzNameFor(reflect.TypeFor[struct{}]()))

	e, ok := buzzEnumFor(reflect.TypeFor[types.TermStyle]())
	require.True(t, ok)
	assert.Equal(t, "TermStyle", e.Name)
	require.NotEmpty(t, e.Cases)

	_, ok = buzzEnumFor(reflect.TypeFor[string]())
	assert.False(t, ok)
}

// enumCarrier exercises every branch of enumsUsedBy: a referenced enum, a second
// reference to the same one, an opted-out field, an unexported field, and a field whose
// type is not an enum at all.
type enumCarrier struct {
	Style     types.TermStyle
	AlsoStyle types.TermStyle
	Skipped   types.TermStyle `buzz:"-"`
	unexposed types.TermStyle
	Plain     string
}

func TestEnumsUsedByDeduplicatesAndSkips(t *testing.T) {
	got := enumsUsedBy(reflect.TypeFor[enumCarrier]())
	require.Len(t, got, 1, "the same enum referenced twice is declared once")
	assert.Equal(t, "TermStyle", got[0].Name)

	assert.Empty(t, enumsUsedBy(reflect.TypeFor[struct{ N int }]()))
	assert.Empty(t, enumCarrier{}.unexposed, "the unexported field exists to be skipped")
}

func TestRenderBuzzMirrorCarriesHeaderAndDeclaration(t *testing.T) {
	out, err := renderBuzzMirror("ExecResult", reflect.TypeFor[types.ExecResult]())
	require.NoError(t, err)
	got := string(out)

	assert.Contains(t, got, "// Code generated by magus-utils types. DO NOT EDIT.")
	// The header names the Go type's own package and name, not the registry key: a
	// header naming a type the reader cannot find defeats its purpose.
	assert.Contains(t, got, "// Buzz mirror of github.com/egladman/magus/types.ExecResult,")
	assert.Contains(t, got, "export object ExecResult {")
	assert.True(t, strings.HasSuffix(got, "}\n"), got)
}

// TestRenderBuzzMirrorRenamesThroughTheRegistry pins the Namer: the header carries the
// Go name and the declaration carries the Buzz one.
func TestRenderBuzzMirrorRenamesThroughTheRegistry(t *testing.T) {
	out, err := renderBuzzMirror("HttpResponse", reflect.TypeFor[types.HTTPResponse]())
	require.NoError(t, err)

	assert.Contains(t, string(out), "types.HTTPResponse,")
	assert.Contains(t, string(out), "export object HttpResponse {")
}

func TestRunTypes(t *testing.T) {
	t.Run("writes the mirror", func(t *testing.T) {
		got := readGenerated(t, runTypes, func(out string) []string {
			return []string{"-type", "ExecResult", "-out", out}
		})
		assert.Contains(t, got, "export object ExecResult {")
	})

	t.Run("deterministic", func(t *testing.T) {
		assertDeterministic(t, runTypes, func(out string) []string {
			return []string{"-type", "ExecResult", "-out", out}
		})
	})

	t.Run("no -out", func(t *testing.T) {
		err := runTypes([]string{"-type", "ExecResult"})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "usage:")
	})

	// A renamed or misspelled boundary type used to surface as "usage:", which reads
	// as CLI misuse rather than as the registry gap it is.
	t.Run("unknown type", func(t *testing.T) {
		err := runTypes([]string{"-type", "NotDeclared", "-out", filepath.Join(t.TempDir(), "x.buzz")})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "unknown boundary type")
		assert.Contains(t, err.Error(), "boundaryTypes")
	})
}

func TestRunEnums(t *testing.T) {
	args := func(out string) []string { return []string{"-package", "types", "-out", out} }

	got := readGenerated(t, runEnums, args)
	assert.Contains(t, got, "// Code generated by magus-utils enums. DO NOT EDIT.")
	assert.Contains(t, got, "package types")
	assert.Contains(t, got, "func (v SignAlgorithm) Values() []string")
	assert.Contains(t, got, "func (v SignAlgorithm) Valid() bool")
	assert.Contains(t, got, "func (v SignAlgorithm) String() string")
	// The zero case is absent from Values (it names "unset") and present in Valid
	// (an unset field is distinguished from a wrong one).
	assert.Contains(t, got, `return []string{"ed25519"}`)
	assert.Contains(t, got, `case "", "ed25519":`)

	assertDeterministic(t, runEnums, args)

	t.Run("missing flags", func(t *testing.T) {
		err := runEnums([]string{"-package", "types"})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "usage:")
	})

	// Emitting an empty file would be a silent no-op for a misspelled package.
	t.Run("package with no enums", func(t *testing.T) {
		err := runEnums([]string{"-package", "nosuchpkg", "-out", filepath.Join(t.TempDir(), "x.go")})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no boundary enums declared")
	})
}

func TestRunBoundaryList(t *testing.T) {
	args := func(out string) []string { return []string{"-out", out} }

	got := readGenerated(t, runBoundaryList, args)
	assert.Contains(t, got, "// Code generated by magus-utils boundarylist. DO NOT EDIT.")
	assert.Contains(t, got, "package gen")
	assert.Contains(t, got, `import "github.com/egladman/magus/types"`)
	assert.Contains(t, got, "var RuntimeBoundaryTypes = []any{")
	assert.Contains(t, got, "types.ExecResult{},")

	// A non-runtime entry has no BuzzObject method and must not reach the list.
	assert.NotContains(t, got, "types.Path{},")

	assertDeterministic(t, runBoundaryList, args)

	t.Run("no -out", func(t *testing.T) {
		err := runBoundaryList(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "usage:")
	})
}

func TestRunBuzzObjects(t *testing.T) {
	args := func(out string) []string { return []string{"-out", out} }

	got := readGenerated(t, runBuzzObjects, args)
	assert.Contains(t, got, "Code generated by magus-utils buzzobjects. DO NOT EDIT.")
	assert.Contains(t, got, "package types")
	assert.Contains(t, got, "BuzzObject")
	assert.Contains(t, got, "ExecResult")

	assertDeterministic(t, runBuzzObjects, args)

	t.Run("no -out", func(t *testing.T) {
		err := runBuzzObjects(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "usage:")
	})
}

// TestRunAPIEmitsASortedLock: the .lock's whole value is that its diff reads as
// added/removed API elements, which only holds while the lines stay sorted.
func TestRunAPIEmitsASortedLock(t *testing.T) {
	got := readGenerated(t, runAPI, func(out string) []string { return []string{"-out", out} })

	require.True(t, strings.HasSuffix(got, "\n"))
	lines := strings.Split(strings.TrimSuffix(got, "\n"), "\n")
	require.NotEmpty(t, lines)
	assert.True(t, slices.IsSorted(lines), "the lock must be sorted or its diff is unreadable")
	assert.NotContains(t, lines, "", "a blank line is an element with no name")
}

func TestRunAPIRejectsAnUnknownFlag(t *testing.T) {
	assert.Error(t, runAPI([]string{"-nosuchflag"}))
}

func TestRunBindings(t *testing.T) {
	t.Run("missing flags", func(t *testing.T) {
		err := runBindings(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "usage:")
	})

	t.Run("unknown module", func(t *testing.T) {
		err := runBindings([]string{"-module", "nosuchmodule", "-out", filepath.Join(t.TempDir(), "x.go")})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "unknown module")
	})

	t.Run("unknown lang", func(t *testing.T) {
		err := runBindings([]string{"-module", "fs", "-lang", "rust", "-out", filepath.Join(t.TempDir(), "x.go")})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "unknown lang")
	})

	t.Run("writes what emitBuzz renders", func(t *testing.T) {
		m, ok := hostmodules.Get("fs")
		require.True(t, ok)
		want, err := emitBuzz(m)
		require.NoError(t, err)

		got := readGenerated(t, runBindings, func(out string) []string {
			return []string{"-module", "fs", "-lang", "buzz", "-out", out}
		})
		assert.Equal(t, string(want), got)
	})
}

func TestRenderModuleSet(t *testing.T) {
	mods := []std.Module{
		// magus is a registered host module and deliberately not a bare import.
		{Name: "magus"},
		{Name: "fs"},
		{Name: "http"},
		{Name: "json", Path: "encoding/json", WASM: true},
	}

	t.Run("native set", func(t *testing.T) {
		out, err := renderModuleSet(mods, "//go:build !wasm", false, "the full set.")
		require.NoError(t, err)
		got := string(out)

		assert.True(t, strings.HasPrefix(got, "//go:build !wasm\n"), got)
		assert.Contains(t, got, "// Code generated by magus-utils moduleset. DO NOT EDIT.")
		assert.Contains(t, got, "package gen")
		assert.Contains(t, got, "// Modules is the full set.")
		assert.Contains(t, got, "var Modules = Set{")
		assert.Contains(t, got, "{Register: RegisterFs}")
		assert.Contains(t, got, "{Register: RegisterHttp}")
		// A Path is emitted only when it differs from the name, and the WASM
		// capability rides along in both files.
		assert.Contains(t, got, `{Register: RegisterJson, Capabilities: Capabilities(WASM), Path: "encoding/json"}`)
		// Including magus would offer `import "magus"` a registry path resolving to a
		// context-less namespace.
		assert.NotContains(t, got, "RegisterMagus")
	})

	t.Run("wasm subset", func(t *testing.T) {
		out, err := renderModuleSet(mods, "//go:build wasm", true, "the browser's view.")
		require.NoError(t, err)
		got := string(out)

		assert.True(t, strings.HasPrefix(got, "//go:build wasm\n"), got)
		assert.Contains(t, got, "RegisterJson")
		// The IO trampolines are exactly what the wasm build must not reference.
		assert.NotContains(t, got, "RegisterFs")
		assert.NotContains(t, got, "RegisterHttp")
	})
}

func TestRunModuleSet(t *testing.T) {
	t.Run("writes both build-tagged files", func(t *testing.T) {
		dir := t.TempDir()
		require.NoError(t, runModuleSet([]string{"-outdir", dir}))

		native, err := os.ReadFile(filepath.Join(dir, "modules.go"))
		require.NoError(t, err)
		wasm, err := os.ReadFile(filepath.Join(dir, "modules_wasm.go"))
		require.NoError(t, err)

		assert.True(t, strings.HasPrefix(string(native), "//go:build !wasm\n"))
		assert.True(t, strings.HasPrefix(string(wasm), "//go:build wasm\n"))
		// Two tables over one declaration, and the wasm half is the subset: modules.go
		// is //go:build !wasm precisely because it references the IO trampolines.
		assert.Contains(t, string(native), "RegisterFs")
		assert.NotContains(t, string(wasm), "RegisterFs")
	})

	t.Run("no -outdir", func(t *testing.T) {
		err := runModuleSet(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "usage:")
	})

	t.Run("missing outdir", func(t *testing.T) {
		err := runModuleSet([]string{"-outdir", filepath.Join(t.TempDir(), "absent")})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "modules.go")
	})
}

func TestRunSpellsRefusesAnEmptySource(t *testing.T) {
	t.Run("no spells dir", func(t *testing.T) {
		err := runSpells([]string{
			"-spells", filepath.Join(t.TempDir(), "absent"),
			"-out", t.TempDir(),
		})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "read spells dir")
	})

	// Compiling nothing and exiting 0 is the silent failure this guard exists for:
	// the embedded set would come out empty with nothing saying so.
	t.Run("no built-ins found", func(t *testing.T) {
		err := runSpells([]string{"-spells", t.TempDir(), "-out", t.TempDir()})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no built-in spells found")
	})
}
