package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestIsInternal(t *testing.T) {
	cases := []struct {
		path string
		want bool
	}{
		{modulePath + "/internal/dry", true},
		{modulePath + "/internal/cache/store", true},
		{modulePath + "/internal", true},
		{modulePath + "/types", false},
		{modulePath, false},
		// "internal" as a name fragment is not an internal package.
		{modulePath + "/internalize", false},
	}
	for _, c := range cases {
		assert.Equal(t, c.want, isInternal(c.path), "isInternal(%q)", c.path)
	}
}

func TestMocksDir(t *testing.T) {
	root, err := mocksDir(modulePath)
	require.NoError(t, err)
	assert.Equal(t, filepath.Join("gen", "mocks"), root, "the module root is the case the path arithmetic leaves empty")

	nested, err := mocksDir(modulePath + "/project/impact")
	require.NoError(t, err)
	assert.Equal(t, filepath.Join("project", "impact", "gen", "mocks"), nested)

	_, err = mocksDir("example.com/elsewhere")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "outside "+modulePath)
}

func TestAssertFile(t *testing.T) {
	got := string(assertFile(modulePath+"/types", []string{"Inspector", "Repository"}))

	assert.Contains(t, got, "// Code generated by magus-utils mockassert; DO NOT EDIT.\n")
	assert.Contains(t, got, "package mocks\n")
	// The alias is fixed rather than the package's real name, because a package name
	// is not derivable from its import path.
	assert.Contains(t, got, "import iface \""+modulePath+"/types\"\n")
	assert.Contains(t, got, "var (\n\t_ iface.Inspector = (*MockInspector)(nil)\n\t_ iface.Repository = (*MockRepository)(nil)\n)\n")
}

// mockeryYAML writes a .mockery.yaml into dir and returns its path.
func mockeryYAML(t *testing.T, dir, body string) string {
	t.Helper()
	path := filepath.Join(dir, ".mockery.yaml")
	require.NoError(t, os.WriteFile(path, []byte(body), 0o644))
	return path
}

// TestRunMockAssertWritesOnlyForPublishedPackages covers the whole pass: the public
// package gets its assertions, the internal one is skipped (it would close an import
// cycle), and an interface-less entry contributes nothing.
func TestRunMockAssertWritesOnlyForPublishedPackages(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	// mockery's dir template does not create these; the generator writes beside the
	// mocks it already produced.
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "types", "gen", "mocks"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "internal", "dry", "gen", "mocks"), 0o755))

	cfg := mockeryYAML(t, dir, `
packages:
  `+modulePath+`/types:
    interfaces:
      Repository:
      Inspector:
  `+modulePath+`/internal/dry:
    interfaces:
      Evaluator:
  `+modulePath+`/empty:
    interfaces:
`)

	require.NoError(t, runMockAssert([]string{"-config", cfg}))

	raw, err := os.ReadFile(filepath.Join(dir, "types", "gen", "mocks", "assert.go"))
	require.NoError(t, err)
	body := string(raw)
	assert.Contains(t, body, "package mocks")
	assert.Contains(t, body, "(*MockInspector)(nil)")
	assert.Contains(t, body, "(*MockRepository)(nil)")
	// Sorted, because map order is not: the file is drift-gated and has to be
	// byte-stable across runs. Asserted by position rather than as one literal,
	// since gofmt aligns the block's "=" and the padding depends on the longest name.
	assert.Less(t,
		strings.Index(body, "MockInspector"),
		strings.Index(body, "MockRepository"))

	_, err = os.Stat(filepath.Join(dir, "internal", "dry", "gen", "mocks", "assert.go"))
	assert.True(t, os.IsNotExist(err), "an internal package's assertion would close an import cycle")

	_, err = os.Stat(filepath.Join(dir, "empty", "gen", "mocks", "assert.go"))
	assert.True(t, os.IsNotExist(err), "a package mocking no interface has nothing to assert")
}

func TestRunMockAssertRefusesABrokenConfig(t *testing.T) {
	dir := t.TempDir()

	t.Run("missing file", func(t *testing.T) {
		err := runMockAssert([]string{"-config", filepath.Join(dir, "absent.yaml")})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "read ")
	})

	t.Run("unparsable yaml", func(t *testing.T) {
		err := runMockAssert([]string{"-config", mockeryYAML(t, t.TempDir(), "packages: [\n")})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "parse ")
	})

	// A config declaring no packages means the schema moved, not that there is
	// nothing to do; emitting nothing would leave every published mock unverified.
	t.Run("no packages", func(t *testing.T) {
		err := runMockAssert([]string{"-config", mockeryYAML(t, t.TempDir(), "packages:\n")})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "declares no packages")
	})

	t.Run("package outside the module", func(t *testing.T) {
		cfg := mockeryYAML(t, t.TempDir(), "packages:\n  example.com/elsewhere:\n    interfaces:\n      Thing:\n")
		err := runMockAssert([]string{"-config", cfg})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "example.com/elsewhere")
	})
}
