package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"

	"github.com/egladman/magus/internal/diff"
	json "github.com/egladman/magus/internal/json"
)

// diffdemo renders a unified patch into the wire shape the console's Diff surface consumes,
// as a TypeScript module.
//
// It exists so the daemon-free showcase does not need a second parser. The console used to
// read a patch itself, that reader drifted from the Go one, and consolidating on Go left the
// demo as the only consumer with no daemon to ask - it renders offline, from a fixture, which
// is the whole point of it. Generating the fixture with the SAME parser keeps one reader
// without making the showcase a special case that could quietly diverge from what a real
// changeset looks like.
//
// The authored artifact stays the .patch file. That is deliberate and demo.ts said so before
// this existed: a patch you can read is a patch you can check against the tool that would have
// produced it, and a hand-maintained tree of rows is not.
func runDiffDemo(args []string) error {
	fs := flag.NewFlagSet("diffdemo", flag.ExitOnError)
	patchPath := fs.String("patch", "", "unified patch to render")
	out := fs.String("out", "", "TypeScript module to write")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *patchPath == "" || *out == "" {
		return fmt.Errorf("diffdemo: -patch and -out are both required")
	}

	patch, err := os.ReadFile(*patchPath)
	if err != nil {
		return fmt.Errorf("diffdemo: %w", err)
	}
	files := diff.Parse(string(patch))
	if len(files) == 0 {
		// A fixture that parses to nothing would render an empty showcase, which reads as a
		// broken surface rather than as a broken fixture.
		return fmt.Errorf("diffdemo: %s parsed to no files", *patchPath)
	}

	body, err := json.MarshalIndent(files, "", "  ")
	if err != nil {
		return fmt.Errorf("diffdemo: %w", err)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by magus-utils diffdemo; DO NOT EDIT.
//
// The changeset the Diff surface's daemon-free showcase renders, parsed from %s by the same
// reader the daemon uses. Edit that patch and re-run generate; editing this file is drift.

import type { WireFile } from "../parse";

export const DEMO_FILES: readonly WireFile[] = %s;
`, *patchPath, body)

	if err := os.WriteFile(*out, b.Bytes(), 0o644); err != nil {
		return fmt.Errorf("diffdemo: %w", err)
	}
	return nil
}
