package main

import (
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRunEnums(t *testing.T) {
	args := func(out string) []string { return []string{"-package", "types", "-out", out} }

	got := readGenerated(t, runEnums, args)
	assert.Contains(t, got, "// Code generated by magus-utils enums. DO NOT EDIT.")
	assert.Contains(t, got, "package types")
	assert.Contains(t, got, "func (v SignAlgorithm) Values() []string")
	assert.Contains(t, got, "func (v SignAlgorithm) Valid() bool")
	assert.Contains(t, got, "func (v SignAlgorithm) String() string")
	// The zero case is absent from Values (it names "unset") and present in Valid
	// (an unset field is distinguished from a wrong one).
	assert.Contains(t, got, `return []string{"ed25519"}`)
	assert.Contains(t, got, `case "", "ed25519":`)

	assertDeterministic(t, runEnums, args)

	t.Run("missing flags", func(t *testing.T) {
		err := runEnums([]string{"-package", "types"})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "usage:")
	})

	// Emitting an empty file would be a silent no-op for a misspelled package.
	t.Run("package with no enums", func(t *testing.T) {
		err := runEnums([]string{"-package", "nosuchpkg", "-out", filepath.Join(t.TempDir(), "x.go")})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no boundary enums declared")
	})
}
