package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"strings"

	"github.com/egladman/magus/internal/generate/emit"
)

// runEnums emits Valid and Values for every boundary enum declared in a package, and
// MarshalText/UnmarshalText for one that names a Noun.
//
// Go has no enum type: a defined string accepts any string forever, so the only
// enforcement available is a predicate plus a call at the boundary where external
// input arrives. Both halves were hand-written before this (a switch listing the
// cases, and prose listing them again in the error), which is two copies of the case
// list that drift from the constants and from each other.
//
// Generating them from the SAME registry that emits the Buzz enum means a new case is
// added in one place and the validator, the message, and the mirror all follow.
func runEnums(args []string) error {
	fs := flag.NewFlagSet("enums", flag.ExitOnError)
	outPath := fs.String("out", "", "output Go file path")
	pkg := fs.String("package", "", "package name to emit for (types, spells)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *outPath == "" || *pkg == "" {
		return fmt.Errorf("usage: magus-utils enums -package <name> -out <path.go>")
	}

	var b bytes.Buffer
	var emitted, textual int
	for _, e := range boundaryEnums {
		if e.Type.PkgPath() == "" || !strings.HasSuffix(e.Type.PkgPath(), "/"+*pkg) {
			continue
		}
		emitted++
		name := e.Type.Name()
		// The zero case is deliberately absent from Values: it names "unset", which is
		// not something a caller should be told to choose between.
		var vals []string
		for _, c := range e.Cases {
			if c.Value == "" {
				continue
			}
			vals = append(vals, fmt.Sprintf("%q", c.Value))
		}
		fmt.Fprintf(&b, `
// Values lists the %s values a caller may choose, excluding the zero value.
func (v %s) Values() []string { return []string{%s} }

// Valid reports whether v is a declared %s. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v %s) Valid() bool {
	switch v {
	case %s:
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v %s) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}
`, name, name, strings.Join(vals, ", "), name, name, strings.Join(append([]string{`""`}, vals...), ", "), name)
		if e.Noun == "" {
			continue
		}
		textual++
		fmt.Fprintf(&b, `
// MarshalText writes the name as given.
func (v %s) MarshalText() ([]byte, error) { return []byte(v), nil }

// UnmarshalText sets v from a name, refusing one outside Values.
func (v *%s) UnmarshalText(text []byte) error {
	n := %s(text)
	if !n.Valid() {
		return fmt.Errorf("unknown %s %%q (want one of %%v)", text, n.Values())
	}
	*v = n
	return nil
}
`, name, name, name, e.Noun)
	}
	if emitted == 0 {
		return fmt.Errorf("no boundary enums declared in package %q", *pkg)
	}

	var head bytes.Buffer
	fmt.Fprintln(&head, "// Code generated by magus-utils enums. DO NOT EDIT.")
	fmt.Fprintln(&head)
	fmt.Fprintf(&head, "package %s\n", *pkg)
	if textual > 0 {
		fmt.Fprintln(&head, `import "fmt"`)
	}
	formatted, err := format.Source(append(head.Bytes(), b.Bytes()...))
	if err != nil {
		return fmt.Errorf("format generated enum helpers: %w", err)
	}
	return emit.File(*outPath, formatted)
}
