package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestUsageNamesEverySubcommand: the usage line was maintained by hand and named
// 13 of the 20 registered scribes, so seven subcommands were unreachable to
// anyone who did not read the source.
func TestUsageNamesEverySubcommand(t *testing.T) {
	got := usageLine()
	for name := range scribes {
		require.Contains(t, got, name, "usage does not name %q", name)
	}
	require.Equal(t, len(scribes)-1, strings.Count(got, "|"), "one separator per subcommand pair")
}

// readGenerated runs one scribe into a fresh path and returns what it wrote.
func readGenerated(t *testing.T, run func([]string) error, args func(out string) []string) string {
	t.Helper()
	out := filepath.Join(t.TempDir(), "out")
	require.NoError(t, run(args(out)))
	body, err := os.ReadFile(out)
	require.NoError(t, err)
	return string(body)
}

// assertDeterministic runs a scribe twice into two distinct paths and compares the
// bytes. Two paths rather than one: emit.File skips an identical write, so rewriting
// the same path would pass without the generator having rendered anything twice.
func assertDeterministic(t *testing.T, run func([]string) error, args func(out string) []string) {
	t.Helper()
	assert.Equal(t,
		readGenerated(t, run, args),
		readGenerated(t, run, args),
		"the generated bytes must not depend on map order; every generate is a drift gate")
}
