// Subcommand `mcptools` emits the MCP tool CATALOG from the std module
// descriptors: one ToolDescriptor per std.Module MCPTool, with its parameters
// mapped to the JSON schema scalars the MCP tool builder understands.
//
// The catalog was hand-written (22 descriptors, ~22 KB of prose) and was the one
// magus surface that did not derive from the descriptor every other surface does:
// the runtime bindings, the checker declarations, and the reference docs all come
// from std. A hand-written twenty-third copy is how magus_tail_log lived on as a
// duplicate of magus_output long after the duplication was admitted in writing.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"slices"
	"strings"

	"github.com/egladman/magus/internal/generate/emit"
	"github.com/egladman/magus/internal/hostmodules"
	"github.com/egladman/magus/std"
)

func runMCPTools(args []string) error {
	fs := flag.NewFlagSet("mcptools", flag.ExitOnError)
	out := fs.String("out", "", "output path for the generated registry .go file")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *out == "" {
		return fmt.Errorf("usage: magus-utils mcptools -out <file>")
	}

	mods := hostmodules.All()
	slices.SortFunc(mods, func(a, b std.Module) int { return strings.Compare(a.Name, b.Name) })

	var tools []std.MCPTool
	for _, m := range mods {
		tools = append(tools, m.MCPTools...)
	}
	if len(tools) == 0 {
		return fmt.Errorf("no module declares an MCP tool; refusing to write an empty registry")
	}

	src, err := renderMCPTools(tools)
	if err != nil {
		return err
	}
	if err := emit.Go(*out, src); err != nil {
		return fmt.Errorf("write %s: %w", *out, err)
	}
	fmt.Printf("wrote %s (%d tools)\n", *out, len(tools))
	return nil
}

// mcpParamType maps a declared param type to the JSON schema scalar name
// internal/handler/mcp's buildMCPTool switches on. std's validation already
// rejects every other tag, so an unmapped one here is a programmer error rather
// than a shape a descriptor can reach.
func mcpParamType(t std.TypeTag) (string, error) {
	switch t {
	case std.TypeString:
		return "string", nil
	case std.TypeBool:
		return "boolean", nil
	case std.TypeInt, std.TypeFloat:
		return "number", nil
	default:
		return "", fmt.Errorf("param type %s has no JSON schema scalar", t.GoType())
	}
}

func renderMCPTools(tools []std.MCPTool) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by magus-utils mcptools. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// The MCP tool catalog, emitted from the std module descriptors. Edit the\n")
	b.WriteString("// MCPTools declaration on the module (std/magus.go) and rerun `go generate\n")
	b.WriteString("// ./internal/handler/mcp/`, never this file.\n\n")
	b.WriteString("package gen\n\n")

	b.WriteString("// ParamDescriptor describes a single parameter on an MCP tool.\n")
	b.WriteString("type ParamDescriptor struct {\n")
	b.WriteString("\tName        string `json:\"name\"                  yaml:\"name\"`\n")
	b.WriteString("\tType        string `json:\"type\"                  yaml:\"type\"`\n")
	b.WriteString("\tRequired    bool   `json:\"required,omitempty\"    yaml:\"required,omitempty\"`\n")
	b.WriteString("\tDescription string `json:\"description,omitempty\" yaml:\"description,omitempty\"`\n")
	b.WriteString("}\n\n")

	b.WriteString("// ToolDescriptor is a static description of one MCP tool: it registers the tool\n")
	b.WriteString("// with the server (registerTools) and populates `magus describe mcp-tools`.\n")
	b.WriteString("//\n")
	b.WriteString("// Member is the descriptor member the tool wraps, empty when no typed Buzz\n")
	b.WriteString("// member covers the verb yet. It is carried through so the gap is readable from\n")
	b.WriteString("// the catalog rather than only from the descriptor.\n")
	b.WriteString("type ToolDescriptor struct {\n")
	b.WriteString("\tName        string            `json:\"name\"                  yaml:\"name\"`\n")
	b.WriteString("\tMember      string            `json:\"member,omitempty\"      yaml:\"member,omitempty\"`\n")
	b.WriteString("\tDescription string            `json:\"description,omitempty\" yaml:\"description,omitempty\"`\n")
	b.WriteString("\tParams      []ParamDescriptor `json:\"params,omitempty\"      yaml:\"params,omitempty\"`\n")
	b.WriteString("}\n\n")

	b.WriteString("// Registry is the canonical list of MCP tools the magus daemon exposes.\n")
	b.WriteString("var Registry = []ToolDescriptor{\n")
	for _, t := range tools {
		b.WriteString("\t{\n")
		fmt.Fprintf(&b, "\t\tName: %q,\n", t.Name)
		if t.Member != "" {
			fmt.Fprintf(&b, "\t\tMember: %q,\n", t.Member)
		}
		fmt.Fprintf(&b, "\t\tDescription: %q,\n", t.Doc)
		if len(t.Params) > 0 {
			b.WriteString("\t\tParams: []ParamDescriptor{\n")
			for _, p := range t.Params {
				typ, err := mcpParamType(p.Type)
				if err != nil {
					return nil, fmt.Errorf("tool %s param %s: %w", t.Name, p.Name, err)
				}
				fmt.Fprintf(&b, "\t\t\t{Name: %q, Type: %q", p.Name, typ)
				if p.Required {
					b.WriteString(", Required: true")
				}
				if p.Doc != "" {
					fmt.Fprintf(&b, ", Description: %q", p.Doc)
				}
				b.WriteString("},\n")
			}
			b.WriteString("\t\t},\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return b.Bytes(), nil
}
