// Subcommand `moduledecls` emits the Buzz DECLARATION half of every host module:
// an `export extern fun` per method, carrying the parameter and return types the
// checker needs. Registered alongside the native implementation under the same
// import path (SetModuleDecls beside SetNativeModule), it is what turns
// `magus\affectedImpact(base)` from an Unknown-typed call into a checked one.
//
// Without it every host call typed as Unknown, so a magusfile could read a field
// no return carries and only find out at run time - which is the gap Ret.Object was
// added to close and, until now, only the docs consumed.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"path/filepath"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/egladman/magus/internal/generate/emit"
	buzz "github.com/egladman/magus/libs/gopherbuzz"
	"github.com/egladman/magus/std"
)

func runModuleDecls(args []string) error {
	fs := flag.NewFlagSet("moduledecls", flag.ExitOnError)
	outDir := fs.String("outdir", "", "output directory for the per-module .buzz declarations")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *outDir == "" {
		return fmt.Errorf("usage: magus-utils moduledecls -outdir <dir>")
	}

	mods := std.All()
	slices.SortFunc(mods, func(a, b std.Module) int { return strings.Compare(a.Name, b.Name) })
	for _, mod := range mods {
		src, err := renderModuleDecls(mod)
		if err != nil {
			return fmt.Errorf("module %s: %w", mod.Name, err)
		}
		var b bytes.Buffer
		fmt.Fprintln(&b, "// Code generated by magus-utils moduledecls. DO NOT EDIT.")
		fmt.Fprintln(&b, "//")
		fmt.Fprintf(&b, "// Buzz declarations for the %s host module: the object mirrors its methods\n", mod.Name)
		fmt.Fprintln(&b, "// return, then one `export extern fun` per method. Registered with SetModuleDecls")
		fmt.Fprintln(&b, "// beside the native implementation, so the checker reads the signature while the")
		fmt.Fprintln(&b, "// runtime keeps the host binding - an extern emits no code, so it cannot shadow")
		fmt.Fprintln(&b, "// one. Edit the std.Module declaration and rerun `go generate`, never this file.")
		fmt.Fprintln(&b)
		b.WriteString(src)
		// Parse what we are about to write. A declaration source that does not parse is
		// not a loud failure at run time - SetModuleDecls drops it and the module simply
		// goes back to being untyped - so without this check a typo silently un-types a
		// whole module and every call through it stops being verified. That is exactly
		// how KnowledgeGodNode shipped an unparseable `in:` field: nothing parsed it.
		// Codegen is the right place to fail, for the same reason checkObjectDecls fails
		// here rather than at load.
		if _, err := buzz.Parse(b.String()); err != nil {
			return fmt.Errorf("generated declarations for %s do not parse: %w", mod.Name, err)
		}
		if err := emit.File(filepath.Join(*outDir, mod.Name+".buzz"), b.Bytes()); err != nil {
			return fmt.Errorf("write %s: %w", mod.Name, err)
		}
	}
	return nil
}

// renderModuleDecls renders one module's declaration source: the object mirrors its
// returns reference (leaf-first, since a field referencing an object needs that
// object declared already), then an extern per method.
func renderModuleDecls(mod std.Module) (string, error) {
	var b strings.Builder
	// Enums first: an object mirror may use one as a field type, and Buzz needs the
	// declaration before the use.
	enums, err := enumsFor(mod)
	if err != nil {
		return "", err
	}
	for _, e := range enums {
		b.Write(renderBuzzEnumDecl(e))
		b.WriteByte('\n')
	}

	mirrors, err := mirrorsFor(mod)
	if err != nil {
		return "", err
	}
	for _, name := range mirrors {
		entry, _ := boundaryTypeNamed(name) // mirrorsFor already resolved every name it returns
		out, err := renderBuzzMirrorDecl(name, entry.Type)
		if err != nil {
			return "", err
		}
		b.Write(out)
		b.WriteByte('\n')
	}

	for _, m := range sortedMethods(mod) {
		decl, err := externDecl(m)
		if err != nil {
			return "", fmt.Errorf("%s: %w", m.Name, err)
		}
		b.WriteString(decl)
	}
	return b.String(), nil
}

// externDecl renders one method as `export extern fun name(params) > ret;`.
//
// A variadic method gets a COMMENT instead of a declaration. Buzz has no variadic
// parameter, and the call it has to accept - fs\join("a", "b", "c") - cannot be
// spelled with a fixed parameter list. Declaring it as a list parameter would reject
// every existing call site, so the method keeps today's untyped behaviour and says so
// in the generated output rather than going silently missing.
func externDecl(m std.Method) (string, error) {
	name := std.CamelCase(m.Name)
	if m.BuzzName != "" {
		name = m.BuzzName
	}
	for _, a := range m.Args {
		if a.Variadic {
			return fmt.Sprintf("// %s is variadic; Buzz has no variadic parameter, so it stays untyped.\n", name), nil
		}
	}

	params := make([]string, 0, len(m.Args))
	for _, a := range m.Args {
		typ, err := buzzArgType(a.Type)
		if err != nil {
			return "", fmt.Errorf("arg %s: %w", a.Name, err)
		}
		// A declared object wins over the raw tag: the shape is what the checker should
		// enforce, and {str: any} enforces nothing.
		if a.Object != "" {
			typ = a.Object
		}
		// Same rule for a closed set of strings: the enum is what the checker should
		// enforce, and `str` enforces nothing.
		if a.Enum != "" {
			typ = a.Enum
		}
		p := a.Name + ": " + typ
		if a.Optional {
			def, derr := buzzDefault(a)
			if derr != nil {
				return "", fmt.Errorf("arg %s: %w", a.Name, derr)
			}
			p += " = " + def
		}
		params = append(params, p)
	}
	ret, err := buzzReturnType(m)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("export extern fun %s(%s) > %s;\n", name, strings.Join(params, ", "), ret), nil
}

// buzzArgType maps a parameter's TypeTag to its Buzz annotation.
func buzzArgType(t std.TypeTag) (string, error) {
	switch t {
	case std.TypeString:
		return "str", nil
	case std.TypeInt, std.TypeIndex:
		return "int", nil
	case std.TypeFloat:
		return "double", nil
	case std.TypeBool:
		return "bool", nil
	case std.TypeStringSlice:
		return "[str]", nil
	case std.TypeFloatSlice:
		return "[double]", nil
	case std.TypeByteSlice:
		return "[int]", nil
	case std.TypeStringSliceSlice:
		return "[[str]]", nil
	case std.TypeStringMapMap:
		return "{str: {str: str}}", nil
	case std.TypeStringMap:
		return "{str: str}", nil
	case std.TypeAnyMap:
		return "{str: any}", nil
	case std.TypeFunc:
		return "Function", nil
	case std.TypeAny:
		return "any", nil
	default:
		return "", fmt.Errorf("no Buzz annotation for type tag %d", t)
	}
}

// buzzDefault renders the default an optional parameter declares, so a caller may
// omit it.
//
// Arg.Default is what the caller gets, NOT the type's zero, and the difference is not
// cosmetic: fs.mkdirall's perm defaults to 0o755, so declaring the zero would have Buzz
// pass an explicit mode 0 and create a directory nothing can then write into. Before
// these declarations existed the trampoline applied the default itself and the omission
// never reached the host; now the declaration is what fills the gap, so it has to carry
// the same value.
//
// It dispatches on the DECLARED TypeTag, not on the default's dynamic Go type. Those
// can disagree - std does not cross-check them - and dispatching on the dynamic type
// renders the disagreement faithfully instead of catching it: {Type: TypeFloat,
// Default: 1} would emit `x: double = 1`. That parses, so the codegen parse gate waves
// it through, and the checker then rejects correct call sites against a declaration
// nobody looked at. Keying on the tag turns a mismatched default into a codegen error.
func buzzDefault(a std.Arg) (string, error) {
	if a.Default == nil {
		return buzzZero(a.Type)
	}
	mismatch := func() error {
		return fmt.Errorf("default %#v (%T) does not match the declared type tag %d", a.Default, a.Default, a.Type)
	}
	switch a.Type {
	case std.TypeString:
		v, ok := a.Default.(string)
		if !ok {
			return "", mismatch()
		}
		return strconv.Quote(v), nil
	case std.TypeBool:
		v, ok := a.Default.(bool)
		if !ok {
			return "", mismatch()
		}
		return strconv.FormatBool(v), nil
	case std.TypeInt, std.TypeIndex:
		switch v := a.Default.(type) {
		case int:
			return strconv.Itoa(v), nil
		case int64:
			return strconv.FormatInt(v, 10), nil
		default:
			return "", mismatch()
		}
	case std.TypeFloat:
		switch v := a.Default.(type) {
		case float64:
			return strconv.FormatFloat(v, 'f', -1, 64), nil
		case int: // an integral default on a double parameter is not a mismatch
			return strconv.FormatFloat(float64(v), 'f', -1, 64), nil
		default:
			return "", mismatch()
		}
	default:
		return "", fmt.Errorf("no Buzz literal for a default on type tag %d", a.Type)
	}
}

// buzzZero is the default for an optional parameter that declares none.
//
// An unmapped tag is an error rather than a fallback. The fallback was `null`, which is
// not the zero of any tag and is not even assignable to the annotations the unmapped
// tags produce: an optional TypeFunc arg would emit `fn: Function = null` against a
// non-nullable Function. Nothing declares one today, so this only ever fires the moment
// someone adds the first - which is exactly when a silent `null` would be worst.
func buzzZero(t std.TypeTag) (string, error) {
	switch t {
	case std.TypeString:
		return `""`, nil
	case std.TypeInt, std.TypeIndex:
		return "0", nil
	case std.TypeFloat:
		return "0.0", nil
	case std.TypeBool:
		return "false", nil
	case std.TypeStringSlice:
		return "[<str>]", nil
	case std.TypeFloatSlice:
		return "[<double>]", nil
	case std.TypeByteSlice:
		return "[<int>]", nil
	case std.TypeStringSliceSlice:
		return "[<[str]>]", nil
	case std.TypeStringMapMap:
		return "{<str: {str: str}>}", nil
	case std.TypeStringMap:
		return "{<str: str>}", nil
	case std.TypeAnyMap:
		return "{<str: any>}", nil
	case std.TypeAny:
		// The one tag whose zero really is null: `any` is nullable, so `x: any = null`
		// annotates cleanly. That is not true of the tags still falling through - a
		// TypeFunc arg would emit `fn: Function = null` against a non-nullable Function.
		return "null", nil
	default:
		return "", fmt.Errorf("optional arg of type tag %d has no expressible Buzz default", t)
	}
}

// buzzReturnType renders a method's Buzz return annotation.
//
// Several returns marshal to a LIST, not a tuple - os.platform crosses as
// [goos, goarch, arch] and magusfile.buzz reads os\platform()[1] - so the
// annotation follows the wire shape, using the element type when the returns agree
// and [any] when they do not (env.lookup is (str, bool)).
func buzzReturnType(m std.Method) (string, error) {
	if len(m.Returns) == 0 {
		return "void", nil
	}
	if len(m.Returns) > 1 {
		first, err := buzzArgType(m.Returns[0].Type)
		if err != nil {
			return "", err
		}
		for _, r := range m.Returns[1:] {
			t, terr := buzzArgType(r.Type)
			if terr != nil {
				return "", terr
			}
			if t != first {
				return "[any]", nil
			}
		}
		return "[" + first + "]", nil
	}
	r := m.Returns[0]
	if r.Object != "" {
		return r.Object, nil
	}
	return buzzArgType(r.Type)
}

// mirrorsFor returns the object mirrors a module's declarations must carry, in
// leaf-first order: every object its methods return, plus every object those
// reference transitively. Derived from the returns rather than hand-listed, so a new
// object return cannot be declared without its mirror travelling with it.
//
// An unresolvable name is an ERROR, not a skip. Skipping was the original shape and it
// defeated the point: a Ret.Object naming a type no registry row claims produced a
// module whose mirror was missing while the extern still referenced it by name, which
// parses fine (buzz.Parse is syntax-only) and is then rejected at check time - dropping
// the module's declarations wholesale, with no codegen error to say why.
func mirrorsFor(mod std.Module) ([]string, error) {
	seen := map[string]bool{}
	var order []string
	var visit func(name string) error
	visit = func(name string) error {
		if name == "" || seen[name] {
			return nil
		}
		entry, ok := boundaryTypeNamed(name)
		if !ok {
			return fmt.Errorf("object %q is not declared in boundaryTypes", name)
		}
		seen[name] = true // before descending, so a self-referential type terminates
		for _, dep := range referencedObjects(entry.Type) {
			if err := visit(dep); err != nil {
				return fmt.Errorf("%s -> %w", name, err)
			}
		}
		order = append(order, name) // after its dependencies: declare-before-use
		return nil
	}
	for _, m := range sortedMethods(mod) {
		// ARGUMENTS as well as returns. An Arg.Object names a type the declaration
		// references just as a return does, and emitting only the return side left
		// http\get's `retry: HttpRetry` pointing at a type the file never declared -
		// which the checker rejects, taking the whole module's signatures down with
		// it. encoding\buildUrl never caught this because its URL argument is also
		// parseUrl's return, so the type came along by accident.
		for _, a := range m.Args {
			if err := visit(strings.Trim(a.Object, "[]")); err != nil {
				return nil, fmt.Errorf("%s: %w", m.Name, err)
			}
		}
		for _, r := range m.Returns {
			if err := visit(strings.Trim(r.Object, "[]")); err != nil {
				return nil, fmt.Errorf("%s: %w", m.Name, err)
			}
		}
	}
	return order, nil
}

// enumsFor returns the enum declarations a module's signatures name, in first-use
// order.
//
// Derived from the signatures rather than hand-listed, for the same reason
// mirrorsFor is: an Arg.Enum naming a type whose declaration does not travel with it
// produces a module whose extern references an undefined name. That parses (buzz.Parse
// is syntax-only) and is then rejected at CHECK time, which drops the module's whole
// declaration set with no codegen error saying why.
//
// This is why an enum reachable only from a signature needs collecting at all: the
// types generator emits an enum into the mirror of the OBJECT whose field uses it, so
// an enum no object references had nowhere to be declared.
func enumsFor(mod std.Module) ([]boundaryEnum, error) {
	seen := map[string]bool{}
	var order []boundaryEnum
	add := func(name, where string) error {
		if name == "" || seen[name] {
			return nil
		}
		e, ok := boundaryEnumNamed(name)
		if !ok {
			return fmt.Errorf("%s: enum %q is not declared in boundaryEnums", where, name)
		}
		seen[name] = true
		order = append(order, e)
		return nil
	}
	for _, m := range sortedMethods(mod) {
		for _, a := range m.Args {
			if err := add(a.Enum, m.Name); err != nil {
				return nil, err
			}
		}
		for _, r := range m.Returns {
			if err := add(r.Enum, m.Name); err != nil {
				return nil, err
			}
		}
	}
	return order, nil
}

// renderBuzzEnumDecl renders one enum as its Buzz declaration. It matches what the
// types generator emits into an object mirror, so a reader sees one form wherever an
// enum is declared.
func renderBuzzEnumDecl(e boundaryEnum) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "export enum<str> %s {\n", e.Name)
	for _, c := range e.Cases {
		fmt.Fprintf(&b, "    %s = %q,\n", c.Name, c.Value)
	}
	fmt.Fprintln(&b, "}")
	return b.Bytes()
}

// sortedMethods orders a module's methods by name. Both the mirror walk and the extern
// emission read it, so reordering two methods in a std module cannot rewrite the
// generated file - generated drift is a CI gate here, and a no-op diff wastes it.
func sortedMethods(mod std.Module) []std.Method {
	methods := slices.Clone(mod.Methods)
	slices.SortFunc(methods, func(a, b std.Method) int { return strings.Compare(a.Name, b.Name) })
	return methods
}

// referencedObjects lists the Buzz object names rt's fields reference, so a mirror is
// never emitted before one it depends on.
//
// time.Time is excluded explicitly: it is a struct, but it crosses the boundary as an
// RFC3339 str (see buzzType), so treating it as a referenced object would ask for a
// mirror named "Time" that must not exist. It was previously swallowed by mirrorsFor's
// silent skip; now that an unresolvable name is an error, the exclusion has to be
// stated rather than relied upon.
func referencedObjects(rt reflect.Type) []string {
	var out []string
	for i := 0; i < rt.NumField(); i++ {
		f := rt.Field(i)
		if !f.IsExported() || f.Tag.Get("buzz") == "-" {
			continue
		}
		t := f.Type
		for t.Kind() == reflect.Slice || t.Kind() == reflect.Array || t.Kind() == reflect.Pointer || t.Kind() == reflect.Map {
			t = t.Elem()
		}
		if t.Kind() == reflect.Struct && t != reflect.TypeFor[time.Time]() {
			out = append(out, buzzNameFor(t))
		}
	}
	return out
}
