// Subcommand `moduleset` emits internal/interp/bindings/gen's module registry: the
// table mapping each host module's bind name to its generated Register trampoline.
//
// It emits TWO files because the registry is build-tagged. modules.go is the native
// set and references every trampoline including the IO ones; modules_wasm.go is the
// browser playground's subset and must not, so the wasm build sees a parallel table.
//
// Both were hand-maintained, and the wasm half carried the instruction "Keep this in
// sync with the WASM-capable entries of modules.go" - a mirror with a rule no test
// could check, because the WASM classification lived nowhere but in those two tables.
// std.Module.WASM now declares it, which is what makes both files projections.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/egladman/magus/internal/hostmodules"
	"github.com/egladman/magus/std"
)

func runModuleSet(args []string) error {
	fs := flag.NewFlagSet("moduleset", flag.ExitOnError)
	outDir := fs.String("outdir", "", "directory to write modules.go and modules_wasm.go into")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *outDir == "" {
		return fmt.Errorf("usage: magus-utils moduleset -outdir <dir>")
	}

	mods := hostmodules.All()
	slices.SortFunc(mods, func(a, b std.Module) int { return strings.Compare(a.Name, b.Name) })

	for _, f := range []struct {
		name    string
		tag     string
		wasm    bool
		purpose string
	}{
		{"modules.go", "//go:build !wasm", false,
			"the full host-module registry: every bare import name a Buzz session resolves\n// beyond Buzz's own stdlib, mapped to its generated Register trampoline."},
		{"modules_wasm.go", "//go:build wasm", true,
			"the wasm build's view: only the modules std marks WASM, which the browser\n// playground can install. modules.go holds the full set but is //go:build !wasm\n// because it references the IO trampolines."},
	} {
		src, err := renderModuleSet(mods, f.tag, f.wasm, f.purpose)
		if err != nil {
			return fmt.Errorf("%s: %w", f.name, err)
		}
		if err := os.WriteFile(filepath.Join(*outDir, f.name), src, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", f.name, err)
		}
	}
	fmt.Printf("wrote modules.go and modules_wasm.go (%d modules) to %s\n", len(mods), *outDir)
	return nil
}

func renderModuleSet(mods []std.Module, buildTag string, wasmOnly bool, purpose string) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "%s\n\n", buildTag)
	b.WriteString("// Code generated by magus-utils moduleset. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with: go generate ./internal/interp/bindings/...\n\n")
	b.WriteString("package gen\n\n")
	fmt.Fprintf(&b, "// Modules is %s\n", purpose)
	b.WriteString("//\n")
	b.WriteString("// The `magus` namespace is intentionally absent. It is not a bare import; it is\n")
	b.WriteString("// wired onto the magus.* namespace with a magusfile's target context.\n")
	b.WriteString("var Modules = Set{\n")

	for _, m := range mods {
		// magus is NOT a bare import - it is wired onto the magus.* namespace with a
		// magusfile's target context, so it has no entry here even though it is a
		// registered host module. Including it would offer `import "magus"` a
		// registry path that resolves to a context-less namespace.
		if m.Name == "magus" {
			continue
		}
		if wasmOnly && !m.WASM {
			continue
		}
		fmt.Fprintf(&b, "\t%q: {Register: Register%s", m.Name, titleCase(m.Name))
		if m.WASM {
			b.WriteString(", Capabilities: Capabilities(WASM)")
		}
		if m.Path != "" {
			fmt.Fprintf(&b, ", Path: %q", m.Path)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return out, nil
}
