package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/egladman/magus/std"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRenderModuleSet(t *testing.T) {
	mods := []std.Module{
		// magus is a registered host module and deliberately not a bare import.
		{Name: "magus"},
		{Name: "fs"},
		{Name: "http"},
		{Name: "json", Path: "encoding/json", WASM: true},
	}

	t.Run("native set", func(t *testing.T) {
		out, err := renderModuleSet(mods, "//go:build !wasm", false, "the full set.")
		require.NoError(t, err)
		got := string(out)

		assert.True(t, strings.HasPrefix(got, "//go:build !wasm\n"), got)
		assert.Contains(t, got, "// Code generated by magus-utils moduleset. DO NOT EDIT.")
		assert.Contains(t, got, "package gen")
		assert.Contains(t, got, "// Modules is the full set.")
		assert.Contains(t, got, "var Modules = Set{")
		assert.Contains(t, got, "{Register: RegisterFs}")
		assert.Contains(t, got, "{Register: RegisterHttp}")
		// A Path is emitted only when it differs from the name, and the WASM
		// capability rides along in both files.
		assert.Contains(t, got, `{Register: RegisterJson, Capabilities: Capabilities(WASM), Path: "encoding/json"}`)
		// Including magus would offer `import "magus"` a registry path resolving to a
		// context-less namespace.
		assert.NotContains(t, got, "RegisterMagus")
	})

	t.Run("wasm subset", func(t *testing.T) {
		out, err := renderModuleSet(mods, "//go:build wasm", true, "the browser's view.")
		require.NoError(t, err)
		got := string(out)

		assert.True(t, strings.HasPrefix(got, "//go:build wasm\n"), got)
		assert.Contains(t, got, "RegisterJson")
		// The IO trampolines are exactly what the wasm build must not reference.
		assert.NotContains(t, got, "RegisterFs")
		assert.NotContains(t, got, "RegisterHttp")
	})
}

func TestRunModuleSet(t *testing.T) {
	t.Run("writes both build-tagged files", func(t *testing.T) {
		dir := t.TempDir()
		require.NoError(t, runModuleSet([]string{"-outdir", dir}))

		native, err := os.ReadFile(filepath.Join(dir, "modules.go"))
		require.NoError(t, err)
		wasm, err := os.ReadFile(filepath.Join(dir, "modules_wasm.go"))
		require.NoError(t, err)

		assert.True(t, strings.HasPrefix(string(native), "//go:build !wasm\n"))
		assert.True(t, strings.HasPrefix(string(wasm), "//go:build wasm\n"))
		// Two tables over one declaration, and the wasm half is the subset: modules.go
		// is //go:build !wasm precisely because it references the IO trampolines.
		assert.Contains(t, string(native), "RegisterFs")
		assert.NotContains(t, string(wasm), "RegisterFs")
	})

	t.Run("no -outdir", func(t *testing.T) {
		err := runModuleSet(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "usage:")
	})

	t.Run("missing outdir", func(t *testing.T) {
		err := runModuleSet([]string{"-outdir", filepath.Join(t.TempDir(), "absent")})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "modules.go")
	})
}
