package main

import (
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/egladman/magus/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestEnumsUsedByDeduplicatesAndSkips(t *testing.T) {
	got := enumsUsedBy(reflect.TypeFor[enumCarrier]())
	require.Len(t, got, 1, "the same enum referenced twice is declared once")
	assert.Equal(t, "TermStyle", got[0].Name)

	assert.Empty(t, enumsUsedBy(reflect.TypeFor[struct{ N int }]()))
	assert.Empty(t, enumCarrier{}.unexposed, "the unexported field exists to be skipped")
}

func TestRenderBuzzMirrorCarriesHeaderAndDeclaration(t *testing.T) {
	out, err := renderBuzzMirror("ExecResult", reflect.TypeFor[types.ExecResult]())
	require.NoError(t, err)
	got := string(out)

	assert.Contains(t, got, "// Code generated by magus-utils types. DO NOT EDIT.")
	// The header names the Go type's own package and name, not the registry key: a
	// header naming a type the reader cannot find defeats its purpose.
	assert.Contains(t, got, "// Buzz mirror of github.com/egladman/magus/types.ExecResult,")
	assert.Contains(t, got, "export object ExecResult {")
	assert.True(t, strings.HasSuffix(got, "}\n"), got)
}

// TestRenderBuzzMirrorRenamesThroughTheRegistry pins the Namer: the header carries the
// Go name and the declaration carries the Buzz one.
func TestRenderBuzzMirrorRenamesThroughTheRegistry(t *testing.T) {
	out, err := renderBuzzMirror("HttpResponse", reflect.TypeFor[types.HTTPResponse]())
	require.NoError(t, err)

	assert.Contains(t, string(out), "types.HTTPResponse,")
	assert.Contains(t, string(out), "export object HttpResponse {")
}

func TestRunTypes(t *testing.T) {
	t.Run("writes the mirror", func(t *testing.T) {
		got := readGenerated(t, runTypes, func(out string) []string {
			return []string{"-type", "ExecResult", "-out", out}
		})
		assert.Contains(t, got, "export object ExecResult {")
	})

	t.Run("deterministic", func(t *testing.T) {
		assertDeterministic(t, runTypes, func(out string) []string {
			return []string{"-type", "ExecResult", "-out", out}
		})
	})

	t.Run("no -out", func(t *testing.T) {
		err := runTypes([]string{"-type", "ExecResult"})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "usage:")
	})

	// A renamed or misspelled boundary type used to surface as "usage:", which reads
	// as CLI misuse rather than as the registry gap it is.
	t.Run("unknown type", func(t *testing.T) {
		err := runTypes([]string{"-type", "NotDeclared", "-out", filepath.Join(t.TempDir(), "x.buzz")})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "unknown boundary type")
		assert.Contains(t, err.Error(), "boundaryTypes")
	})
}

// enumCarrier exercises every branch of enumsUsedBy: a referenced enum, a second
// reference to the same one, an opted-out field, an unexported field, and a field whose
// type is not an enum at all.
type enumCarrier struct {
	Style     types.TermStyle
	AlsoStyle types.TermStyle
	Skipped   types.TermStyle `buzz:"-"`
	unexposed types.TermStyle
	Plain     string
}
