// Subcommand `types` emits the Buzz `object` mirror of a Go value type in
// github.com/egladman/magus/types, so the Go struct stays the single source of
// truth and the two shapes can never drift. The emitted file is shipped as part
// of the declarations for whichever host import path returns the type - os for
// ExecResult, vcs for Tag, magus for TargetGraph, and so on (see internal/spellruntime
// and internal/interp/bindings/modules.go) - so importing that path already
// brings the type into a magusfile's or spell's scope for annotations and
// literals, with no separate import required.
//
// The rendering itself lives in libs/gopherbuzz/buzzgen: what an object declaration
// looks like, which identifiers are reserved, how a Go shape maps to a Buzz type. None
// of that is magus's to know, and this file used to reach into gopherbuzz for every one
// of those facts - the usual sign a boundary sits in the wrong place. What stays here is
// what IS magus's: which types cross (boundaryTypes) and what each is called on the far
// side (buzzNameFor), handed over as the Namer.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"reflect"

	"github.com/egladman/magus/internal/generate/emit"
	"github.com/egladman/magus/libs/gopherbuzz/buzzgen"
)

func runTypes(args []string) error {
	fs := flag.NewFlagSet("types", flag.ExitOnError)
	typeName := fs.String("type", "", "value type to mirror (e.g. ExecResult)")
	outPath := fs.String("out", "", "output .buzz file path")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *outPath == "" {
		return fmt.Errorf("usage: magus-utils types -type <Name> -out <path.buzz>")
	}
	// Distinguished from the usage error above: a renamed or misspelled boundary type
	// used to surface as "usage:", which reads as CLI misuse rather than as the registry
	// gap it actually is.
	entry, ok := boundaryTypeNamed(*typeName)
	if !ok {
		return fmt.Errorf("unknown boundary type %q: declare it in boundaryTypes first", *typeName)
	}

	out, err := renderBuzzMirror(*typeName, entry.Type)
	if err != nil {
		return err
	}
	if err := emit.File(*outPath, out); err != nil {
		return fmt.Errorf("write %s: %w", *outPath, err)
	}
	return nil
}

// mirrorOptions is magus's configuration of the shared renderer: resolve a struct
// field's object name through the boundary registry, and mirror a timestamp as a string.
// The Namer is what keeps a RENAMED mirror referenceable - types.StatusTargetRun declares
// as TargetRun, and emitting the Go name would reference an object nothing declares.
func mirrorOptions() buzzgen.Options {
	opts := buzzgen.DefaultOptions()
	opts.Namer = buzzNameFor
	return opts
}

// renderBuzzMirror renders rt as a standalone mirror file: the generated-file header
// followed by the declaration.
func renderBuzzMirror(name string, rt reflect.Type) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by magus-utils types. DO NOT EDIT.")
	fmt.Fprintln(&b, "//")
	// rt.Name(), not the registry key: the two differ wherever the Buzz name reads
	// better than the Go one (Projects/ProjectsOutput, HttpResponse/HTTPResponse),
	// and a header that names a type the reader cannot find defeats its purpose.
	fmt.Fprintf(&b, "// Buzz mirror of github.com/egladman/magus/types.%s, bundled into\n", rt.Name())
	fmt.Fprintln(&b, "// whichever module owns it (magus/spell, or the host module that returns it -")
	fmt.Fprintln(&b, "// see internal/spellruntime/target.go and hosttypes.go). Edit the Go struct and rerun")
	fmt.Fprintln(&b, "// `go generate`, never this file.")
	fmt.Fprintln(&b)
	body, err := renderBuzzMirrorDecl(name, rt)
	if err != nil {
		return nil, err
	}
	b.Write(body)
	return b.Bytes(), nil
}

// renderBuzzMirrorDecl renders just the `export object <name> { … }` declaration. Split
// from the header so a module bundle (moduledecls) can carry many mirrors under one
// header instead of repeating the banner per type.
func renderBuzzMirrorDecl(name string, rt reflect.Type) ([]byte, error) {
	return buzzgen.ObjectDecl(name, rt, mirrorOptions())
}
