# fish completion for magus
# Generated by `magus completion fish`. Place in:
#   ~/.config/fish/completions/magus.fish

function __magus_subcommands
    printf '%s\t%s\n' \
        ls        'list discovered projects' \
        graph     'print dependency tree' \
        describe  'explain affected membership' \
        run       'run a verb for selected projects' \
        x         'interactive shorthand: pick project + verb' \
        affected  'run a verb for VC-affected projects' \
        mage      'run a magefile/magusfile target' \
        version   'print version, commit, build date' \
        help      'show help' \
        completion 'generate shell completion' \
        doctor    'validate the workspace'
end

function __magus_verbs
    printf '%s\t%s\n' \
        ls       'print selected projects' \
        build    'build selected projects' \
        test     'test selected projects' \
        lint     'lint selected projects' \
        format   'format selected projects' \
        clean    'remove build artifacts' \
        generate 'run code generation' \
        ci       'full pipeline'
end

function __magus_projects
    magus ls -o name 2>/dev/null
end

set -l verb_set ls build test lint format clean generate ci

for _cmd in magus mgs
    complete -c $_cmd -f
    complete -c $_cmd -n '__fish_use_subcommand' -a '(__magus_subcommands)'

    complete -c $_cmd -n "__fish_seen_subcommand_from run; and not __fish_seen_subcommand_from $verb_set" -a '(__magus_verbs)'
    complete -c $_cmd -n "__fish_seen_subcommand_from run; and __fish_seen_subcommand_from $verb_set" -a '(__magus_projects)'

    complete -c $_cmd -n "__fish_seen_subcommand_from affected; and not __fish_seen_subcommand_from $verb_set" -a '(__magus_verbs)'

    complete -c $_cmd -n '__fish_seen_subcommand_from describe' -a '(__magus_projects)'
    complete -c $_cmd -n '__fish_seen_subcommand_from x'        -a '(__magus_projects)'
    complete -c $_cmd -n '__fish_seen_subcommand_from affected' -l explain -d 'show why a project is affected'
    complete -c $_cmd -n '__fish_seen_subcommand_from affected' -l plan -d 'emit a CI shard plan for the affected set'
    complete -c $_cmd -n '__fish_seen_subcommand_from affected' -l bisect -d 'find the commit that broke a project'
    complete -c $_cmd -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish powershell'
end
