# PowerShell completion for magus
# Generated by `magus completion powershell`. Source from your PowerShell profile:
#   magus completion powershell | Out-String | Invoke-Expression
#
# Or persist it:
#   magus completion powershell >> $PROFILE

$__magus_scriptblock = {
    param($wordToComplete, $commandAst, $cursorPosition)

    # magus-utils:subcommands:begin
    $subcommands = 'ls', 'describe', 'run', 'x', 'where', 'affected',
                   'query', 'explain', 'path', 'refs', 'graph', 'watch',
                   'status', 'clean', 'vcs', 'doctor', 'config', 'memory',
                   'server', 'buzz', 'completion', 'man', 'init', 'agent',
                   'hook', 'notify', 'self', 'version', 'help'
    # magus-utils:subcommands:end
    $describeNouns = 'spell', 'charm', 'target', 'project', 'workspace', 'module', 'mcp-tool'
    $lenses        = 'hotspots', 'affinity', 'ownership', 'trend', 'unreferenced', 'report'
    $graphSubs     = 'deps', 'export', 'stats'
    $configSubs    = 'view', 'set', 'history', 'cache', 'mcp'
    $serverSubs    = 'start', 'stop'
    $selfSubs      = 'update', 'install-shorthand'
    $shells        = 'bash', 'zsh', 'fish', 'powershell'
    $runFlags      = '--dry-run', '--graph', '--upstream', '--depth', '--timeout',
                      '--shard', '--n-shards', '--no-volatility-retry', '--race', '--step',
                      '--no-default-charms'
    $affectedFlags = '--dry-run', '--base', '--stdin', '--null', '--graph', '--upstream',
                      '--depth', '--explain', '--plan', '--max-shards',
                      '--max-parallel-budget', '--bisect', '--good', '--target',
                      '--timeout', '--step', '--race'
    $graphDepsFlags   = '--upstream', '--depth', '--spell', '--target'
    $graphExportFlags = '--refresh'
    $graphStatsFlags  = '--kind', '--refresh'
    $insightFlags     = '--commits', '--since', '--workspace', '--files'
    $watchFlags       = '--debounce', '--initial', '--null', '--backend', '--ignore'
    $statusFlags      = '--watch', '--compact', '--socket', '--probe', '--workspace'
    $initFlags        = '--global', '--local', '--force', '--vcs'

    function Complete-From($values, $kind = 'ParameterValue') {
        return $values |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, $kind, $_)
            }
    }

    function Get-MagusProjects {
        try { & magus ls -o name 2>$null } catch { @() }
    }

    # Get-MagusTargets returns the targets this workspace declares, falling back to
    # the built-in set when the workspace cannot be read (`describe` fails by design
    # outside one, and completion that vanishes there is worse than a generic list).
    function Get-MagusTargets {
        $t = try { & magus describe targets -o name 2>$null } catch { @() }
        if ($t) { return $t }
        return 'ls', 'build', 'test', 'lint', 'format', 'clean', 'generate', 'ci'
    }

    # Tokenize the command line (splits on whitespace, respects quotes via CommandAst).
    $tokens = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })
    $tokenCount = $tokens.Count

    # Nothing beyond `magus` yet -> complete a subcommand.
    if ($tokenCount -le 1) {
        return Complete-From $subcommands
    }

    $cmd = $tokens[1]
    $atArg2 = ($tokenCount -le 2 -or ($tokenCount -eq 3 -and $wordToComplete -ne ''))

    switch ($cmd) {
        'run' {
            if ($wordToComplete.StartsWith('-')) {
                return Complete-From $runFlags 'ParameterName'
            }
            if ($atArg2) {
                return Complete-From (Get-MagusTargets)
            }
            return Complete-From (Get-MagusProjects)
        }
        'affected' {
            if ($wordToComplete.StartsWith('-')) {
                return Complete-From $affectedFlags 'ParameterName'
            }
            if ($atArg2) {
                return Complete-From (Get-MagusTargets)
            }
        }
        'describe' {
            if ($atArg2) {
                return Complete-From $describeNouns
            }
            return Complete-From (Get-MagusProjects)
        }
        'x' {
            if ($wordToComplete.StartsWith('-')) {
                return Complete-From @('--step') 'ParameterName'
            }
            return Complete-From (Get-MagusProjects)
        }
        'insight' {
            if ($atArg2) {
                return Complete-From $lenses
            }
            return Complete-From $insightFlags 'ParameterName'
        }
        'graph' {
            if ($atArg2) {
                return Complete-From $graphSubs
            }
            $sub = $tokens[2]
            switch ($sub) {
                'deps'   { return Complete-From $graphDepsFlags 'ParameterName' }
                'export' { return Complete-From $graphExportFlags 'ParameterName' }
                'stats'  { return Complete-From $graphStatsFlags 'ParameterName' }
            }
        }
        'watch' {
            return Complete-From $watchFlags 'ParameterName'
        }
        'status' {
            return Complete-From $statusFlags 'ParameterName'
        }
        'clean' {
            return Complete-From @('--cache') 'ParameterName'
        }
        'config' {
            if ($atArg2) {
                return Complete-From $configSubs
            }
        }
        'server' {
            if ($atArg2) {
                return Complete-From $serverSubs
            }
        }
        'self' {
            if ($atArg2) {
                return Complete-From $selfSubs
            }
        }
        'init' {
            return Complete-From $initFlags 'ParameterName'
        }
        'completion' {
            if ($atArg2) {
                return Complete-From $shells
            }
        }
        'man' {
            return Complete-From @('install', '--dir')
        }
    }
}

Register-ArgumentCompleter -CommandName magus -Native -ScriptBlock $__magus_scriptblock
Register-ArgumentCompleter -CommandName mgs   -Native -ScriptBlock $__magus_scriptblock
