# bash completion for magus
# Generated by `magus completion bash`. Source from your bashrc:
#   source <(magus completion bash)

# _magus_targets echoes the target names this workspace actually declares, falling
# back to the built-in set when the workspace cannot be read.
#
# The fallback matters: completion that vanishes outside a workspace is worse than
# completion that is merely generic, and `magus describe targets` fails by design
# when there is no magusfile to read. The static list is the language-agnostic core
# every spell provides, so it is never wrong, only incomplete.
# COMPREPLY=( $(compgen ...) ) is the bash-completion idiom and word splitting is
# the point; mapfile is bash 4+, and this targets bash 3.2 (macOS).
# shellcheck disable=SC2207

_magus_targets() {
    local t
    t=$(magus describe targets -o name 2>/dev/null)
    if [[ -n "$t" ]]; then
        printf '%s\n' "$t"
    else
        printf '%s\n' "ls build test lint format clean generate ci"
    fi
}

_magus_complete() {
    local cur cmd
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"

# magus-utils:subcommands:begin
    local subcommands="ls describe where run affected x clean query refs explain path graph diff vcs session memory notes watch events server status buzz agent init doctor config completion man self version help"
# magus-utils:subcommands:end
    local nouns="spell charm target project workspace module mcp-tool"
    local lenses="hotspots affinity ownership trend unreferenced report"
    local graph_subs="deps export stats"
    local config_subs="view set history cache mcp"
    local server_subs="start stop"
    local self_subs="update install-shorthand"
    local shells="bash zsh fish powershell"
    # Verbs chained after --then. `outputs` and `file` read the target's declared
    # outputs; `value` reads what the target returned.
    local chain_verbs="outputs file value"
    local chain_actions="contents export"
    local run_flags="--dry-run --graph --upstream --depth --timeout --skip --shard --n-shards --no-volatility-retry --race --step --no-default-charms --live --no-cache --then"
    local affected_flags="--dry-run --base --stdin --null --graph --upstream --depth --explain --plan --max-shards --max-parallel-budget --bisect --good --target --timeout --step --race"
    local graph_deps_flags="--upstream --depth --spell --target"
    local graph_export_flags="--refresh"
    local graph_stats_flags="--kind --refresh"
    local insight_flags="--commits --since --workspace --files"
    local watch_flags="--debounce --initial --null --backend --ignore"
    local status_flags="--watch --compact --socket --probe --workspace"
    local init_flags="--global --local --force --vcs"

    if [[ "$COMP_CWORD" -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )
        return 0
    fi

    cmd="${COMP_WORDS[1]}"

    case "$cmd" in
        attention)
            # dispose wants an open request id; ids come from the queue itself, the
            # same way run's targets come from the workspace. Elsewhere the verb list
            # is static.
            if [[ "$COMP_CWORD" -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "ls dispose" -- "$cur") )
            elif [[ "${COMP_WORDS[2]}" == "dispose" && "$COMP_CWORD" -eq 3 ]]; then
                COMPREPLY=( $(compgen -W "$(magus attention -o name 2>/dev/null)" -- "$cur") )
            fi
            return 0
            ;;
        run)
            # Everything after --then is the chain's, so its verbs win over run's own
            # flags and project names.
            local ti=-1 i
            for ((i = 2; i < COMP_CWORD; i++)); do
                if [[ "${COMP_WORDS[i]}" == "--then" ]]; then ti=$i; break; fi
            done
            if [[ "$ti" -ge 0 ]]; then
                local depth=$((COMP_CWORD - ti))
                if [[ "$depth" -eq 1 ]]; then
                    COMPREPLY=( $(compgen -W "$chain_verbs" -- "$cur") )
                elif [[ "${COMP_WORDS[ti+1]}" == "outputs" ]]; then
                    COMPREPLY=( $(compgen -W "export --path" -- "$cur") )
                elif [[ "${COMP_WORDS[ti+1]}" == "file" ]]; then
                    if [[ "$depth" -eq 2 ]]; then
                        COMPREPLY=( $(compgen -W "$(magus run "${COMP_WORDS[2]}" --then outputs 2>/dev/null)" -- "$cur") )
                    else
                        COMPREPLY=( $(compgen -W "$chain_actions --path" -- "$cur") )
                    fi
                fi
                return 0
            fi
            if [[ "$cur" == -* ]]; then
                COMPREPLY=( $(compgen -W "$run_flags" -- "$cur") )
            elif [[ "$COMP_CWORD" -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$(_magus_targets)" -- "$cur") )
            else
                local projects
                projects=$(magus ls -o name 2>/dev/null)
                COMPREPLY=( $(compgen -W "$projects" -- "$cur") )
            fi
            ;;
        affected)
            if [[ "$cur" == -* ]]; then
                COMPREPLY=( $(compgen -W "$affected_flags" -- "$cur") )
            elif [[ "$COMP_CWORD" -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$(_magus_targets)" -- "$cur") )
            fi
            ;;
        describe)
            if [[ "$COMP_CWORD" -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$nouns" -- "$cur") )
            else
                local projects
                projects=$(magus ls -o name 2>/dev/null)
                COMPREPLY=( $(compgen -W "$projects" -- "$cur") )
            fi
            ;;
        x)
            if [[ "$cur" == -* ]]; then
                COMPREPLY=( $(compgen -W "--step" -- "$cur") )
            else
                local projects
                projects=$(magus ls -o name 2>/dev/null)
                COMPREPLY=( $(compgen -W "$projects" -- "$cur") )
            fi
            ;;
        insight)
            if [[ "$COMP_CWORD" -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$lenses" -- "$cur") )
            else
                COMPREPLY=( $(compgen -W "$insight_flags" -- "$cur") )
            fi
            ;;
        graph)
            if [[ "$COMP_CWORD" -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$graph_subs" -- "$cur") )
            else
                case "${COMP_WORDS[2]}" in
                    deps)   COMPREPLY=( $(compgen -W "$graph_deps_flags" -- "$cur") ) ;;
                    export) COMPREPLY=( $(compgen -W "$graph_export_flags" -- "$cur") ) ;;
                    stats)  COMPREPLY=( $(compgen -W "$graph_stats_flags" -- "$cur") ) ;;
                esac
            fi
            ;;
        watch)
            COMPREPLY=( $(compgen -W "$watch_flags" -- "$cur") )
            ;;
        status)
            COMPREPLY=( $(compgen -W "$status_flags" -- "$cur") )
            ;;
        clean)
            COMPREPLY=( $(compgen -W "--cache" -- "$cur") )
            ;;
        config)
            if [[ "$COMP_CWORD" -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$config_subs" -- "$cur") )
            fi
            ;;
        server)
            if [[ "$COMP_CWORD" -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$server_subs" -- "$cur") )
            fi
            ;;
        self)
            if [[ "$COMP_CWORD" -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$self_subs" -- "$cur") )
            fi
            ;;
        init)
            COMPREPLY=( $(compgen -W "$init_flags" -- "$cur") )
            ;;
        completion)
            if [[ "$COMP_CWORD" -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$shells" -- "$cur") )
            fi
            ;;
        man)
            COMPREPLY=( $(compgen -W "install --dir" -- "$cur") )
            ;;
    esac
    return 0
}
complete -F _magus_complete magus mgs
