package agent

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"testing/fstest"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func testCatalog(t *testing.T) *Catalog {
	t.Helper()
	files := make(fstest.MapFS, len(skillSources))
	for _, source := range skillSources {
		files[source.bodyPath] = &fstest.MapFile{Data: []byte("# " + source.name + "\n")}
	}
	return NewCatalog(files, "## Magus\n\nUse the graph.\n", 6)
}

func TestCatalogInstallsAndVerifiesSkillTree(t *testing.T) {
	catalog := testCatalog(t)
	dir := t.TempDir()
	written, err := catalog.WriteSkillTree(dir, ".agents/skills", false, VariantFull)
	require.NoError(t, err)
	require.Len(t, written, len(skillSources))

	body, err := os.ReadFile(filepath.Join(dir, ".agents/skills", anchorSkillRel))
	require.NoError(t, err)
	assert.Contains(t, string(body), "license: "+skillLicense)
	assert.Contains(t, string(body), "skill-content: "+catalog.contentDigest)

	statuses := catalog.CheckStatuses(dir)
	require.Len(t, statuses, 1)
	assert.Equal(t, ".agents/skills", statuses[0].Location)
	assert.True(t, statuses[0].Installed)
	assert.False(t, statuses[0].Stale)

	stale := strings.Replace(string(body), "skill-content: "+catalog.contentDigest, "skill-content: 000000000000", 1)
	require.NoError(t, os.WriteFile(filepath.Join(dir, ".agents/skills", anchorSkillRel), []byte(stale), 0o644))
	assert.True(t, catalog.CheckStatuses(dir)[0].Stale)
}

func TestCatalogMaintainsOnlyManagedAgentsSection(t *testing.T) {
	catalog := testCatalog(t)
	dir := t.TempDir()
	path := filepath.Join(dir, "AGENTS.md")
	require.NoError(t, os.WriteFile(path, []byte("# Local rules\n\nkeep this\n"), 0o644))
	_, err := catalog.WriteAgentsSection(dir)
	require.NoError(t, err)
	_, err = catalog.WriteAgentsSection(dir)
	require.NoError(t, err)

	body, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Contains(t, string(body), "keep this")
	assert.Equal(t, 1, strings.Count(string(body), "magus:skills:begin"))
}

func TestCatalogSkillTarIsByteStable(t *testing.T) {
	catalog := testCatalog(t)
	a, err := catalog.SkillTar(".claude/skills", VariantFull)
	require.NoError(t, err)
	b, err := catalog.SkillTar(".claude/skills", VariantFull)
	require.NoError(t, err)
	assert.Equal(t, a, b, "SkillTar must be reproducible; no embedded timestamps in the body")
	assert.NotEmpty(t, a)
}

func TestCatalogSkillBytesByName(t *testing.T) {
	catalog := testCatalog(t)
	body, err := catalog.SkillBytes("magus-architecture", VariantFull)
	require.NoError(t, err)
	assert.Contains(t, string(body), "name: magus-architecture")
	assert.Contains(t, string(body), "skill-content: "+catalog.contentDigest)

	_, err = catalog.SkillBytes("does-not-exist", VariantFull)
	assert.ErrorContains(t, err, "unknown skill")
}

func TestCatalogRenderAndStamp(t *testing.T) {
	catalog := testCatalog(t)
	rendered := catalog.RenderSkill(AgentSkill{Name: "magus-test", Description: "Does one thing.", Body: "# Test"})
	assert.Equal(t, "---\nname: magus-test\ndescription: \"Does one thing.\"\n---\n\n# Test\n", string(rendered))
	stamped := string(catalog.StampSkill(rendered, VariantFull))
	assert.Contains(t, stamped, "metadata:\n  source: magus\n")
	assert.Equal(t, 1, strings.Count(stamped, "generated by: magus agent install"))
}

// TestApplyVariantKeepsBothPermutationsWellFormed pins the elision contract. The
// full permutation must lose only the markers; the simple one must lose the marked
// spans and still read as finished sentences, because a variant that reads as
// damaged text is worse than no variant.
func TestApplyVariantKeepsBothPermutationsWellFormed(t *testing.T) {
	body := "Do the thing<!-- why --> - because the alternative silently corrupts output<!-- /why -->.\n" +
		"\n<!-- why -->A whole paragraph of rationale.<!-- /why -->\n\nNext step."

	full, err := applyVariant("s", body, VariantFull)
	require.NoError(t, err)
	assert.Equal(t, "Do the thing - because the alternative silently corrupts output.\n\nA whole paragraph of rationale.\n\nNext step.", full)
	assert.NotContains(t, full, "why", "no scaffolding may reach an installed file")

	simple, err := applyVariant("s", body, VariantSimple)
	require.NoError(t, err)
	assert.Equal(t, "Do the thing.\n\nNext step.", simple,
		"the marked spans go, the sentence still ends in a period, and the emptied paragraph leaves no blank-line run")
}

// TestApplyVariantDoesNotTouchUnelidedContent is the regression guard for a bug
// this mechanism shipped once: a global " ." -> "." tidy pass rewrote `git checkout .`
// into `git checkout.` - corrupting a command in a skill that tells the reader never
// to run it, in text that was never marked at all. Seam repair is local or it is wrong.
func TestApplyVariantDoesNotTouchUnelidedContent(t *testing.T) {
	body := "Never run `git checkout .` or `git clean`<!-- why --> - it destroys untracked work<!-- /why -->.\n" +
		"\nKeep ( these ) spaces and this : colon."

	for _, v := range []Variant{VariantFull, VariantSimple} {
		got, err := applyVariant("s", body, v)
		require.NoError(t, err)
		assert.Contains(t, got, "`git checkout .`", "%s must not rewrite an unelided command", v)
		assert.Contains(t, got, "( these ) spaces and this : colon.", "%s must not retouch unelided punctuation", v)
	}
}

// TestApplyVariantSwapsTwoWordings pins the idiom that makes real compression
// possible: a why span carrying the long wording, immediately followed by a terse
// span carrying the short one. Each variant keeps exactly one of them, so the
// full form loses nothing and the simple form is genuinely rewritten rather than
// merely truncated.
func TestApplyVariantSwapsTwoWordings(t *testing.T) {
	body := "Scope explicitly<!-- why -->, because a bare command acts on whichever project holds " +
		"your current directory and therefore means something different depending on where you " +
		"happen to be standing<!-- /why --><!-- terse --> (magus is CWD-relative)<!-- /terse -->."

	full, err := applyVariant("s", body, VariantFull)
	require.NoError(t, err)
	assert.Equal(t, "Scope explicitly, because a bare command acts on whichever project holds your "+
		"current directory and therefore means something different depending on where you happen "+
		"to be standing.", full)

	simple, err := applyVariant("s", body, VariantSimple)
	require.NoError(t, err)
	assert.Equal(t, "Scope explicitly (magus is CWD-relative).", simple)

	for _, got := range []string{full, simple} {
		assert.NotContains(t, got, "<!--", "no scaffolding may reach an installed file")
	}
}

// TestApplyVariantTerseAloneIsSimpleOnly covers the unpaired case: a terse span
// with no why sibling is content the short form has and the long form does not.
func TestApplyVariantTerseAloneIsSimpleOnly(t *testing.T) {
	body := "Step one.<!-- terse --> See the docs for why.<!-- /terse -->"

	full, err := applyVariant("s", body, VariantFull)
	require.NoError(t, err)
	assert.Equal(t, "Step one.", full)

	simple, err := applyVariant("s", body, VariantSimple)
	require.NoError(t, err)
	assert.Equal(t, "Step one. See the docs for why.", simple)
}

// TestApplyVariantRefusesUnbalancedMarkers keeps a malformed body from installing.
// Silently dropping to the end of the file, or silently keeping everything, both
// ship a skill missing a step - and in an instruction file a missing step is
// indistinguishable from an instruction not to do it.
func TestApplyVariantRefusesUnbalancedMarkers(t *testing.T) {
	for name, body := range map[string]string{
		"open with no close":       "Do it<!-- why --> because.",
		"close with no open":       "Do it because<!-- /why -->.",
		"nested open":              "a<!-- why -->b<!-- why -->c<!-- /why -->d",
		"terse open with no close": "Do it<!-- terse --> briefly.",
		"terse close with no open": "Do it briefly<!-- /terse -->.",
		"nested terse open":        "a<!-- terse -->b<!-- terse -->c<!-- /terse -->d",
	} {
		t.Run(name, func(t *testing.T) {
			_, err := applyVariant("magus-x", body, VariantSimple)
			require.Error(t, err)
			assert.Contains(t, err.Error(), "magus-x", "the error must name the skill that is malformed")
		})
	}
}

// TestStampNamesTheVariantButSharesTheDigest pins the versioning property the
// single-source design exists for: both permutations come from one body, so they
// must report the same content digest and go stale together. A per-variant digest
// would let a simple install look current against a source its sibling outgrew.
func TestStampNamesTheVariantButSharesTheDigest(t *testing.T) {
	catalog := testCatalog(t)
	full, err := catalog.SkillBytes("magus-vcs", VariantFull)
	require.NoError(t, err)
	simple, err := catalog.SkillBytes("magus-vcs", VariantSimple)
	require.NoError(t, err)

	assert.Contains(t, string(full), "skill-variant: full")
	assert.Contains(t, string(simple), "skill-variant: simple")

	digest := footerDigestRe.FindStringSubmatch(string(full))
	require.Len(t, digest, 2)
	assert.Contains(t, string(simple), "skill-content: "+digest[1],
		"one source body, one digest - the permutations version together")
}
