package agent

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"testing/fstest"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func testCatalog(t *testing.T) *Catalog {
	t.Helper()
	files := make(fstest.MapFS, len(skillSources))
	for _, source := range skillSources {
		files[source.bodyPath] = &fstest.MapFile{Data: []byte("# " + source.name + "\n")}
	}
	return NewCatalog(files, "## Magus\n\nUse the graph.\n", 6)
}

func TestCatalogInstallsAndVerifiesSkillTree(t *testing.T) {
	catalog := testCatalog(t)
	dir := t.TempDir()
	written, err := catalog.InstallSkillTree(dir, ".agents/skills", false)
	require.NoError(t, err)
	require.Len(t, written, len(skillSources))

	body, err := os.ReadFile(filepath.Join(dir, ".agents/skills", anchorSkillRel))
	require.NoError(t, err)
	assert.Contains(t, string(body), "license: "+skillLicense)
	assert.Contains(t, string(body), "skill-content: "+catalog.contentDigest)

	statuses := catalog.CheckStatuses(dir)
	require.Len(t, statuses, 1)
	assert.Equal(t, ".agents/skills", statuses[0].Location)
	assert.True(t, statuses[0].Installed)
	assert.False(t, statuses[0].Stale)

	stale := strings.Replace(string(body), "skill-content: "+catalog.contentDigest, "skill-content: 000000000000", 1)
	require.NoError(t, os.WriteFile(filepath.Join(dir, ".agents/skills", anchorSkillRel), []byte(stale), 0o644))
	assert.True(t, catalog.CheckStatuses(dir)[0].Stale)
}

func TestCatalogMaintainsOnlyManagedAgentsSection(t *testing.T) {
	catalog := testCatalog(t)
	dir := t.TempDir()
	path := filepath.Join(dir, "AGENTS.md")
	require.NoError(t, os.WriteFile(path, []byte("# Local rules\n\nkeep this\n"), 0o644))
	_, err := catalog.InstallAgentsSection(dir)
	require.NoError(t, err)
	_, err = catalog.InstallAgentsSection(dir)
	require.NoError(t, err)

	body, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Contains(t, string(body), "keep this")
	assert.Equal(t, 1, strings.Count(string(body), "magus:skills:begin"))
}

func TestCatalogRenderAndStamp(t *testing.T) {
	catalog := testCatalog(t)
	rendered := catalog.RenderSkill(AgentSkill{Name: "magus-test", Description: "Does one thing.", Body: "# Test"})
	assert.Equal(t, "---\nname: magus-test\ndescription: \"Does one thing.\"\n---\n\n# Test\n", string(rendered))
	stamped := string(catalog.StampSkill(rendered))
	assert.Contains(t, stamped, "metadata:\n  source: magus\n")
	assert.Equal(t, 1, strings.Count(stamped, "generated by: magus agent install"))
}
