package main

import (
	"os"
	"path/filepath"
	"testing"

	// Importing the host package triggers all host/*.go init() calls, which
	// register every module (Sh, Fs, Vcs, …) with std.Register.
	"github.com/egladman/magus/internal/std"
)

// buzzModules is the set of modules whose gen/buzz/*.go files are generated by
// magus-bindings-gen -lang buzz. magus is excluded (hand-built in bindings/buzz.go). Unlike
// gen/js, charm is pure magus-bindings-gen output here.
var buzzModules = []string{
	"os", "vcs", "fs", "archive", "env", "json", "http", "charm",
}

// TestBuzzFilesUpToDate verifies that the checked-in gen/buzz/<module>.go files
// are byte-for-byte identical to what `magus-bindings-gen -lang buzz` would emit today.
func TestBuzzFilesUpToDate(t *testing.T) {
	genBuzzDir := filepath.Join("..", "..", "internal", "std", "gen", "buzz")

	for _, name := range buzzModules {
		name := name
		t.Run(name, func(t *testing.T) {
			m, ok := std.Get(name)
			if !ok {
				t.Fatalf("std.Get(%q): module not registered", name)
			}
			want, err := emitBuzz(m)
			if err != nil {
				t.Fatalf("emitBuzz(%q): %v", name, err)
			}
			outPath := filepath.Join(genBuzzDir, name+".go")
			got, err := os.ReadFile(outPath)
			if err != nil {
				t.Fatalf("read %s: %v", outPath, err)
			}
			if string(got) != string(want) {
				t.Errorf("%s.go is out of date; re-run:\n  go generate ./internal/std/", name)
			}
		})
	}
}
