// Package queue is a speculative, partitioned merge queue, which `magus queue` runs.
//
// A queue run has three steps, each with the rights it needs and no more, and the
// version control each gets says which: [types.ReadVCS] reads, [types.BuildVCS] also
// commits locally, and only [types.PushVCS] pushes.
//
//   - A [Planner] reads the changes carrying merge intent (a [types.Changes] document,
//     from a [types.Provider] or from anywhere else), checks each one's approval at its
//     head, finds which changes are stacked on which from their ancestry, drops the ones
//     that conflict with the base branch on their own, and splits the rest into
//     partitions whose affected sets are pairwise disjoint. It writes a [types.Plan].
//   - A [Validator] executes the changes' code and needs read access only. Per partition
//     it builds candidates base+A, base+A+B, base+A+B+C onto each other, regenerates
//     generated files on each, and runs a gate on up to Depth of them at once. It records
//     one [types.Verdict] per change the moment that change is decided.
//   - An [Applier] holds the write credential and executes no change's code. It rebuilds
//     each green change's candidate itself, merges it through the provider with the
//     change's own merge method as soon as every change beneath it in its partition has
//     merged, and stops when the base branch does not carry the tree it predicted.
//
// Bytes produced by running a change's code are as untrusted as code its author typed.
// Everything validation writes is a claim the Applier checks against its own rebuild,
// never content it takes on trust. Generated bytes reach an author's branch two ways,
// both exactly what validation gated: the base's own regeneration, run by the Applier
// when the build tool proves the change touches none of the code that regeneration
// runs, or validation's regeneration, carried in a bundle beside its verdict and taken
// only once the Applier checks it is the gated commit, on the Applier's own merge,
// differing from it only in declared outputs. A change whose merge needs regenerated
// files and has neither goes back to its author. A file is generated only when the
// build tool declares it a target's output.
//
// The vocabulary: base is the branch the queue merges into, and the base commit is its
// tip when the plan was made. A candidate is a speculative merge commit, built onto
// either the base commit or the candidate beneath it. The tip is the base branch's
// commit at apply, and a head is a change's own commit. A change is stacked on another
// when it carries that one's head and the base does not; the stack base is that head,
// and the change's own delta is measured from it.
//
// The contract lives in the types package: the documents, the codes, and what the
// version control, the build tool ([types.BuildFacts]), the provider ([types.Provider])
// and the CI system ([types.ArtifactLister]) answer. The gate and the regeneration are
// hooks run on each candidate ([CommandGate], [CommandRegenerate]). Every merge, check
// and push is composed here from the version control's facts, so which merge base a
// prediction takes, which conflicts are the author's and which differences a review
// need not see are decided once, in Go. The decisions themselves (stack detection,
// partitioning, what waits on what, approval carry-over, what an atomic run pins) are
// pure functions over what the steps read, so they are tested and fuzzed without a
// repository. The client package wires magus's version control and its Go SDK in, and
// [CommandFacts] asks any other build tool through a command line.
//
// Go holds what the invariants are proven over and what needs the machine: admission,
// partitioning, candidate order, the merge checks, version control, processes, files
// and concurrency. Buzz holds what talks to a system outside the repository, the
// provider and the CI system, as a pure function of that system's answers and the
// record it was handed: it supplies facts and performs writes, and decides nothing (see
// the provider package). A fact the queue acts on is re-checked in Go before it is
// trusted: a change record passes [types.Change.Check], an approval must name a head, a
// base and a merge method, a declared stack parent must match ancestry, and a stale
// head is unproven. A knob is a fact, not a script: what the schedule computes over
// comes from the build tool and the provider, and how it computes is fixed here.
//
// Every document it reads or writes is JSON carrying a "schema" name with a version,
// and everything it reports is JSONL [Event] records.
package queue
