package knowledge

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/egladman/magus/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestScanMarkersGrammar(t *testing.T) {
	for _, tc := range []struct {
		name, rel, src string
		want           []markerHit
	}{
		{"go comment point", "a.go", "// magus:diagram server-share (the box)\n",
			[]markerHit{{family: "diagram", args: "server-share (the box)", line: 1}}},
		{"html comment block with closer", "AGENTS.md", "x\n<!-- magus:skills:begin a: 1 -->\n<!-- magus:skills:end -->\n",
			[]markerHit{{family: "skills", verb: "begin", args: "a: 1", line: 2}, {family: "skills", verb: "end", line: 3}}},
		{"hash comment", "x.sh", "# magus:calls internal/x http\n",
			[]markerHit{{family: "calls", args: "internal/x http", line: 1}}},
		{"unknown family is still a token", "x.go", "\t// magus:bogus x\n",
			[]markerHit{{family: "bogus", args: "x", line: 1}}},
		{"prose mention", "x.go", "// every magus:diagram marker in sourceGlobs\n", nil},
		{"string literal", "x.go", "const p = \"magus:notice:\"\n", nil},
		{"quoted at line start", "x.buzz", "    \"magus:regenerate:requested\",\n", nil},
		{"backticked in docs", "x.md", "a `magus:diagram <id>` comment\n", nil},
		{"hyphenated word is not a family", "x.ts", "// magus:theme-set bridge on commit.\n", nil},
		{"colon suffix is not a verb", "x.go", "// magus:notice:hello\n", nil},
		{"render-time placeholder", "x.md", "<!-- magus-run -->\n<!-- magus-run-recorder -->\n", nil},
		{"fenced example", "x.md", "```go\n// magus:bogus x\n```\n~~~~\n# magus:bogus y\n~~~~\n", nil},
		{"crlf", "x.go", "// magus:observed stamp=abc\r\n",
			[]markerHit{{family: "observed", args: "stamp=abc", line: 1}}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, scanMarkers(tc.rel, []byte(tc.src)))
		})
	}
}

func TestParseMarkerArgs(t *testing.T) {
	_, stamps := parseMarkerArgs("generated by: magus agent install; agent-skill-version: 101; " +
		"knowledge-schema-version: 17; skill-content: b0be169ef08d; do not edit - re-run it")
	assert.Equal(t, map[string]string{
		"agent-skill-version": "101", "knowledge-schema-version": "17", "skill-content": "b0be169ef08d",
	}, stamps)

	pos, stamps := parseMarkerArgs("internal/handler/mcp http via=:8080; family=x; owner=core")
	assert.Equal(t, []string{"internal/handler/mcp", "http"}, pos)
	assert.Equal(t, map[string]string{"via": ":8080", "owner": "core"}, stamps, "a reserved key is never stamped")
}

func TestFoldMarkers(t *testing.T) {
	got := foldMarkers([]markerHit{
		{family: "skills", verb: "begin", args: "a: 1", line: 2},
		{family: "diagram", args: "x", line: 3},
		{family: "skills", verb: "end", line: 9},
		{family: "observed", verb: "end", line: 10},
		{family: "observed", verb: "begin", line: 11},
	})
	assert.Equal(t, []foldedMarker{
		{markerHit: markerHit{family: "skills", verb: "begin", args: "a: 1", line: 2}, endLine: 9},
		{markerHit: markerHit{family: "diagram", args: "x", line: 3}},
		{markerHit: markerHit{family: "observed", verb: "end", line: 10}, unresolved: "magus:observed:end has no :begin above it"},
		{markerHit: markerHit{family: "observed", verb: "begin", line: 11}, unresolved: "magus:observed:begin has no :end below it"},
	}, got)
}

// markerTree writes a workspace whose root is its only project.
func markerTree(t *testing.T, files map[string]string) Inputs {
	t.Helper()
	root := t.TempDir()
	for rel, body := range files {
		full := filepath.Join(root, filepath.FromSlash(rel))
		require.NoError(t, os.MkdirAll(filepath.Dir(full), 0o755))
		require.NoError(t, os.WriteFile(full, []byte(body), 0o644))
	}
	return Inputs{Root: root, Graph: types.TargetGraphOutput{Projects: []types.TargetGraphProject{{Path: "."}}}}
}

func TestAssembleMarkers(t *testing.T) {
	in := markerTree(t, map[string]string{
		"internal/share/share.go":   "// Package share.\n// magus:diagram server-share (the boxes).\n// magus:diagram gone\npackage share\n",
		"internal/client/c.go":      "package client\n\n// magus:calls internal/share http\n// magus:calls internal/share grpc\n// magus:calls nowhere http\n",
		"internal/client/c_test.go": "package client\n\n" + "// magus:bogus fixture\n",
		"docs/server.md":            "# Server\n\n## Share\n\nText.\n\n<!--diagram:server-share-->\n",
		"docs/run.md":               "<!-- magus-run -->\n",
		"AGENTS.md": "# Agents\n\n<!-- magus:skills:begin generated by: magus agent install; agent-skill-version: 101; " +
			"knowledge-schema-version: 17; skill-content: abc; do not edit -->\nbody\n<!-- magus:skills:end -->\n",
	})
	shards := AssembleShards(in)
	for _, sh := range shards {
		require.NoError(t, sh.Err)
	}
	g := mergeAll(shards)

	var markers []string
	for _, n := range g.Output().Nodes {
		if n.Kind == types.KindMarker {
			markers = append(markers, n.ID)
		}
	}
	assert.Equal(t, []string{
		"marker:AGENTS.md:3",
		"marker:internal/client/c.go:3",
		"marker:internal/client/c.go:4",
		"marker:internal/client/c.go:5",
		"marker:internal/share/share.go:2",
		"marker:internal/share/share.go:3",
	}, markers)

	skills, _ := g.node("marker:AGENTS.md:3")
	assert.Equal(t, types.KnowledgeNode{
		ID: "marker:AGENTS.md:3", Kind: types.KindMarker, Label: "magus:skills", Source: "AGENTS.md:3",
		Attrs: map[string]string{
			types.AttrMarkerFamily: "skills", types.AttrMarkerVerb: "block", types.AttrLine: "3", types.AttrEndLine: "5",
			types.AttrMarkerArgs:  "generated by: magus agent install; agent-skill-version: 101; knowledge-schema-version: 17; skill-content: abc; do not edit",
			"agent-skill-version": "101", "knowledge-schema-version": "17", "skill-content": "abc",
		},
	}, skills)

	share, _ := g.node("marker:internal/share/share.go:2")
	assert.Equal(t, types.KnowledgeNode{
		ID: "marker:internal/share/share.go:2", Kind: types.KindMarker, Label: "magus:diagram server-share",
		Source: "internal/share/share.go:2",
		Attrs: map[string]string{
			types.AttrMarkerFamily: "diagram", types.AttrMarkerVerb: "point", types.AttrLine: "2",
			types.AttrMarkerArgs: "server-share (the boxes).",
		},
	}, share)
	gone, _ := g.node("marker:internal/share/share.go:3")
	assert.Equal(t, "no docs page embeds figure gone", gone.Attrs[attrMarkerUnresolved])
	nowhere, _ := g.node("marker:internal/client/c.go:5")
	assert.Equal(t, "magus:calls destination nowhere is not a directory", nowhere.Attrs[attrMarkerUnresolved])

	declared := map[string]types.KnowledgeEdge{}
	for _, e := range g.Edges() {
		if e.Confidence == types.ConfidenceDeclared {
			declared[e.Source+" "+string(e.Relation)+" "+e.Target] = e
		}
	}
	for _, k := range []string{
		"doc:AGENTS.md contains marker:AGENTS.md:3",
		"file:internal/share/share.go contains marker:internal/share/share.go:2",
		"file:internal/share/share.go contains marker:internal/share/share.go:3",
		"file:internal/client/c.go contains marker:internal/client/c.go:3",
		"file:internal/client/c.go contains marker:internal/client/c.go:4",
		"file:internal/client/c.go contains marker:internal/client/c.go:5",
		"marker:internal/share/share.go:2 references docsection:docs/server.md#share",
		"marker:internal/client/c.go:3 references dir:internal/share",
		"marker:internal/client/c.go:4 references dir:internal/share",
		"dir:internal/client calls dir:internal/share",
	} {
		assert.Contains(t, declared, k)
	}
	assert.Len(t, declared, 10, "an unresolved marker has no references edge")
	assert.Equal(t, types.KnowledgeEdge{
		Source: "dir:internal/client", Target: "dir:internal/share", Relation: types.RelationCalls,
		Confidence: types.ConfidenceDeclared, Score: 1, Provenance: "internal/client/c.go:3",
		Attrs: map[string]string{types.AttrTransport: "grpc,http"},
	}, declared["dir:internal/client calls dir:internal/share"])

	assert.Empty(t, g.UndeclaredEdges())
}

func TestAssembleMarkersUnknownFamily(t *testing.T) {
	in := markerTree(t, map[string]string{
		"a/x.go": "package a\n\n// magus:bogus x\n",
		"b.md":   "<!-- magus:nope:begin -->\n",
	})
	var err error
	for _, sh := range AssembleShards(in) {
		if sh.Err != nil {
			err = sh.Err
		}
	}
	require.ErrorIs(t, err, &types.DiagnosticError{Code: types.UnknownMarkerFamily})
	assert.ErrorContains(t, err, "a/x.go:3: magus:bogus, b.md:1: magus:nope")
	for _, f := range types.MarkerFamily("").Values() {
		assert.ErrorContains(t, err, f)
	}
}
