package render

import (
	"fmt"
	"io"
	"slices"
	"strconv"
	"strings"

	"github.com/egladman/magus/internal/render/md"
	"github.com/egladman/magus/types"
)

// heatPalette is a 5-stop cold→hot ramp; index 0 is "no recent churn", index 4 the
// hottest. Text colors keep the labels legible against each fill.
var heatPalette = []struct{ fill, text string }{
	{"#eff3ff", "#000"},
	{"#bdd7e7", "#000"},
	{"#6baed6", "#000"},
	{"#3182bd", "#fff"},
	{"#08519c", "#fff"},
}

// heatBucket maps a churn count onto a palette index. 0 stays cold (0); any
// non-zero count lands in 1..4, scaled so the busiest project reaches the top of
// the ramp (ceil(count/max * 4)).
func heatBucket(count, max int) int {
	if count <= 0 || max <= 0 {
		return 0
	}
	b := (count*4 + max - 1) / max
	if b > 4 {
		b = 4
	}
	return b
}

// hotspotGraphIR maps a HotspotOutput onto the shared renderGraph. IDs are assigned
// in path order (collisions get a numeric suffix) so output is deterministic — it
// mirrors projectGraphIR but buckets nodes by churn instead of spell and stays flat
// (no subgraphs), which reads better as a heatmap.
func hotspotGraphIR(out types.HotspotOutput) renderGraph {
	paths := make([]string, len(out.Nodes))
	maxChurn := 0
	for i, n := range out.Nodes {
		paths[i] = n.Path
		if n.Churn > maxChurn {
			maxChurn = n.Churn
		}
	}
	ids := mermaidIDs(paths)

	g := renderGraph{Title: "magus hotspot heatmap", DOTName: "magus_hotspots"}

	nodes := slices.Clone(out.Nodes)
	slices.SortFunc(nodes, func(a, b types.Node) int { return strings.Compare(a.Path, b.Path) })
	for _, n := range nodes {
		label := n.Label() + fmt.Sprintf("<br/>commits=%d", n.Churn)
		if n.Authors > 0 {
			label += fmt.Sprintf("<br/>authors=%d", n.Authors)
		}
		if n.BlastRadius > 0 {
			label += fmt.Sprintf("<br/>BR=%d", n.BlastRadius)
		}
		class := fmt.Sprintf("heat%d", heatBucket(n.Churn, maxChurn))
		rn := renderNode{ID: ids[n.Path], DOTID: n.Path, Label: label, Shape: shapeBox, Classes: []string{class}}
		if n.Dir != "" {
			rn.ClickURL = "file://" + n.Dir
			rn.ClickTip = n.Path
		}
		g.Nodes = append(g.Nodes, rn)
	}
	for _, n := range out.Nodes {
		for _, child := range n.Children {
			if cid, ok := ids[child]; ok {
				g.Edges = append(g.Edges, renderEdge{From: ids[n.Path], To: cid})
			}
		}
	}
	for i, c := range heatPalette {
		g.Classes = append(g.Classes, renderClass{
			Name:  fmt.Sprintf("heat%d", i),
			Style: fmt.Sprintf("fill:%s,color:%s", c.fill, c.text),
		})
	}
	return g
}

func affinityGraphIR(out types.AffinityOutput) renderGraph {
	pathSet := map[string]struct{}{}
	for _, c := range out.Pairs {
		pathSet[c.A] = struct{}{}
		pathSet[c.B] = struct{}{}
	}
	paths := make([]string, 0, len(pathSet))
	for p := range pathSet {
		paths = append(paths, p)
	}
	ids := mermaidIDs(paths)

	g := renderGraph{Title: "magus affinity graph", DOTName: "magus_affinity"}
	slices.Sort(paths)
	labels := make(map[string]string, len(out.Pairs)*2)
	for _, pair := range out.Pairs {
		labels[pair.A] = pair.ALabel()
		labels[pair.B] = pair.BLabel()
	}
	for _, p := range paths {
		g.Nodes = append(g.Nodes, renderNode{ID: ids[p], DOTID: p, Label: labels[p], Shape: shapeBox})
	}
	// out.Pairs is already sorted; the edge is symmetric, so the arrow is only a
	// drawing artifact — the count label carries the meaning. A hidden pair is dashed.
	hidden := false
	for _, c := range out.Pairs {
		e := renderEdge{From: ids[c.A], To: ids[c.B], Label: strconv.Itoa(c.Count), Dashed: c.Hidden}
		if c.Hidden {
			hidden = true
		}
		g.Edges = append(g.Edges, e)
	}
	if hidden {
		g.Title += " (dashed = hidden affinity)"
	}
	return g
}

// WriteInsightMarkdown writes the combined insight report.
//
// It emits the PORTABLE Mermaid subset (no quadrantChart, no click directives, no
// subgraph/classDef) rather than the richer dialect. The CLI that wanted the rich
// output is gone; what is left writes INSIGHT.md into a repository or a CI step
// summary, and those renderers are the lowest common denominator this subset targets.
func WriteInsightMarkdown(w io.Writer, r types.InsightReport) error {
	var b md.Builder

	b.Heading(1, "Insight")
	b.Comment("Generated by magus\\insightMarkdown. A point-in-time snapshot of VCS history; regenerate to refresh.")
	b.Paragraph(types.InsightDefinition)
	b.Paragraphf("_Window: %s._", windowText(r.Hotspots.Commits, r.Hotspots.Since))
	b.Paragraph("Use this as a work-selection signal: [hotspots](https://eli.gladman.cc/magus/guides/insight/#the-lenses) identify refactoring candidates; [affinity](https://eli.gladman.cc/magus/guides/insight/#the-lenses) exposes undeclared coupling; ownership and trend identify maintenance risk.")

	// Hotspots.
	b.Heading(2, "Hotspots")
	b.Paragraph(types.HotspotDefinition)
	if err := b.Fenced("mermaid", func(w io.Writer) error {
		return writeGitHubMermaid(w, hotspotGraphIR(r.Hotspots))
	}); err != nil {
		return err
	}
	if len(r.Hotspots.Files) > 0 {
		rows := make([][]string, 0, 20)
		for _, f := range topFiles(r.Hotspots.Files, 20) {
			rows = append(rows, []string{
				strconv.Itoa(f.Score), strconv.Itoa(f.Commits), strconv.Itoa(f.Complexity),
				strconv.Itoa(f.Authors), md.Code(f.Path),
			})
		}
		b.Table([]string{"Score", "Commits", "Complexity", "Authors", "File"},
			[]md.Align{md.Right, md.Right, md.Right, md.Right}, rows)
		b.Paragraph("**Next:** start with the highest score; split or simplify code only after checking its dependents and test coverage.")
	}

	// Affinity.
	b.Heading(2, "Affinity")
	b.Paragraph(types.AffinityDefinition)
	if len(r.Affinity.Pairs) > 0 {
		if err := b.Fenced("mermaid", func(w io.Writer) error {
			return writeGitHubMermaid(w, affinityGraphIR(r.Affinity))
		}); err != nil {
			return err
		}
		rows := make([][]string, 0, len(r.Affinity.Pairs))
		for _, c := range r.Affinity.Pairs {
			rows = append(rows, []string{
				strconv.Itoa(c.Count), checkbox(c.Hidden),
				md.Code(c.ALabel()) + " ↔ " + md.Code(c.BLabel()),
			})
		}
		b.Table([]string{"Count", "Hidden", "Projects"},
			[]md.Align{md.Right, md.Center}, rows)
		b.Paragraph("**Next:** investigate rows marked hidden; either declare the real dependency or remove the accidental coupling.")
	}

	// Ownership.
	b.Heading(2, "Ownership")
	b.Paragraph(types.OwnershipDefinition)
	rows := make([][]string, 0, len(r.Ownership.Projects))
	for _, o := range r.Ownership.Projects {
		rows = append(rows, []string{
			fmt.Sprintf("%d%%", o.PrimaryShare), checkbox(o.BusFactor1), checkbox(o.Stale),
			strconv.Itoa(o.Authors), mdAuthor(o.Primary), md.Code(o.Label()),
		})
	}
	b.Table([]string{"Primary share", "Bus factor 1", "Stale", "Authors", "Primary", "Project"},
		[]md.Align{md.Right, md.Center, md.Center, md.Right}, rows)
	b.Paragraph("**Next:** pair on bus-factor-one work and confirm whether stale projects still have an owner.")

	// Trend.
	b.Heading(2, "Trend")
	b.Paragraph(types.TrendDefinition)
	rows = rows[:0]
	for _, t := range r.Trend.Projects {
		rows = append(rows, []string{
			fmt.Sprintf("%+d", t.Delta), strconv.Itoa(t.Recent), strconv.Itoa(t.Earlier), md.Code(t.Label()),
		})
	}
	b.Table([]string{"Delta", "Recent", "Earlier", "Project"},
		[]md.Align{md.Right, md.Right, md.Right}, rows)
	b.Paragraph("**Next:** investigate sharply rising projects before they become recurring delivery risk.")

	writeVolatilitySection(&b, r.Volatility)
	writeUnreferencedSection(&b, r.Unreferenced)

	_, err := b.WriteTo(w)
	return err
}

func writeGitHubMermaid(w io.Writer, graph renderGraph) error {
	graph.Title = ""
	graph.NodeSpacing = 0
	graph.RankSpacing = 0
	graph.Nodes = slices.Clone(graph.Nodes)
	for i := range graph.Nodes {
		graph.Nodes[i].ClickURL = ""
		graph.Nodes[i].ClickTip = ""
	}
	// Keep GitHub summaries to the oldest common flowchart subset. In
	// particular, do not emit edge-label quoting, subgraphs, or class/style
	// directives: GitHub has changed support for those independently of its
	// flowchart parser, while the report's tables provide the omitted detail.
	graph.Edges = slices.Clone(graph.Edges)
	for i := range graph.Edges {
		graph.Edges[i].Label = ""
	}
	graph.Groups = nil
	graph.Classes = nil
	return writeMermaid(w, graph)
}

// unreferencedReportRows caps the committed report's table; the full list is a command away.
const unreferencedReportRows = 50

// writeUnreferencedSection renders the knowledge-graph lens.
//
// Unlike the other sections it renders even when the list is EMPTY, whenever the verdict
// is unknown. An omitted section reads as "nothing to report", and the one case this lens
// exists to catch is a workspace whose symbol index was never built, where nothing to
// report is precisely what it cannot claim.
func writeUnreferencedSection(b *md.Builder, u types.UnreferencedOutput) {
	if len(u.Symbols) == 0 && u.Answer.Verdict != types.VerdictUnknown {
		return
	}
	b.Heading(2, "Unreferenced symbols")
	b.Paragraph(types.UnreferencedDefinition)
	if len(u.Symbols) > 0 {
		// A committed report is read, not scrolled, so the table is capped and the
		// omission is stated. A silent truncation would read as a complete list, which
		// is the same failure the verdict below exists to prevent.
		shown := u.Symbols
		if len(shown) > unreferencedReportRows {
			shown = shown[:unreferencedReportRows]
		}
		rows := make([][]string, 0, len(shown))
		for _, s := range shown {
			rows = append(rows, []string{s.Kind, md.Code(s.Source), md.Code(s.Label)})
		}
		b.Table([]string{"Kind", "Source", "Symbol"}, []md.Align{md.Left, md.Left, md.Left}, rows)
		if len(u.Symbols) > len(shown) {
			b.Paragraphf("_Showing %d of %d. Read `magus\\insightReport` for the full list._", len(shown), len(u.Symbols))
		}
	}
	switch u.Answer.Verdict {
	case types.VerdictUnknown:
		b.Paragraphf("**Incomplete:** %s. This list is what magus could see, not what exists.", uncoveredPhrase(u.Answer))
	case types.VerdictAbsent:
		b.Paragraph("**Next:** nothing here is unreferenced, across every symbol index this workspace declares.")
	default:
		b.Paragraph("**Next:** read each entry before deleting it. Reflection, interface dispatch, build tags, and consumers outside this workspace are all invisible here.")
	}
}

// uncoveredPhrase names what put an answer outside coverage, for prose.
func uncoveredPhrase(ans types.KnowledgeAnswer) string {
	switch ans.Reason {
	case types.ReasonSymbolsNotLoaded:
		return "no code symbols were loaded for this report"
	case types.ReasonCoverageUnknown:
		return "magus could not determine which projects it searched"
	}
	if len(ans.Gaps) == 0 {
		return "part of the workspace was outside coverage"
	}
	return "no symbol index for " + types.DescribeGaps(ans.Gaps)
}

// writeVolatilitySection renders the run-outcome axis (`magus insight volatility`) into the
// combined report: each (project, target) pair's Wilson-scored flakiness against the threshold.
// Empty when no history was read or it held no targets (the report is best-effort here).
func writeVolatilitySection(b *md.Builder, v types.VolatilityReport) {
	if len(v.Targets) == 0 {
		return
	}
	b.Heading(2, "Volatility")
	b.Paragraph(types.VolatilityDefinition)
	b.Paragraphf("_Threshold: %.3f (Wilson lower bound), from run-outcome history._", v.Threshold)
	rows := make([][]string, 0, len(v.Targets))
	for _, t := range v.Targets {
		rows = append(rows, []string{
			fmt.Sprintf("%.3f", t.Score), checkbox(t.Volatile),
			strconv.Itoa(t.Pass), strconv.Itoa(t.Fail), strconv.Itoa(t.VolatileCount),
			strconv.Itoa(t.Samples), md.Code(t.Project + ":" + t.Target),
		})
	}
	b.Table([]string{"Score", "Volatile", "Pass", "Fail", "Volatile runs", "Samples", "Target"},
		[]md.Align{md.Right, md.Center, md.Right, md.Right, md.Right, md.Right}, rows)
}

func windowText(commits int, since string) string {
	s := fmt.Sprintf("last %d commits", commits)
	if since != "" {
		s += " within " + since
	}
	return s
}

func topFiles(files []types.FileHotspot, n int) []types.FileHotspot {
	if len(files) > n {
		return files[:n]
	}
	return files
}

func checkbox(b bool) string {
	if b {
		return "yes"
	}
	return ""
}

func mdAuthor(a string) string {
	if a == "" {
		return "-"
	}
	return a
}
