package render

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io"
	"net/url"
	"path"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/egladman/magus/internal/hint"
	"github.com/egladman/magus/internal/render/md"
	"github.com/egladman/magus/types"
)

// glossaryDocURL is the canonical, hosted magus glossary. MAGUS.md links out to it
// instead of embedding its own copy, so the term definitions have a single source
// of truth on the docs site.
const glossaryDocURL = "https://eli.gladman.cc/magus/glossary/"

// EncodeFragmentRaw gzip-compresses (BestCompression) raw and returns a
// base64url-encoded string (no padding) suitable for use as a #data= URL
// fragment. The browser reverses it with DecompressionStream('gzip'). gzip
// header fields are left at their zero values to guarantee byte-stable output
// across calls. Callers marshal their payload to JSON first; this is the
// canonical encoder shared by the render package and cmd/magus (graph open
// --targets and the knowledge-graph #data= path), both of which feed the same
// browser decode contract, so byte-for-byte wire-format parity is required.
func EncodeFragmentRaw(raw []byte) (string, error) {
	return encodeFragmentRaw(raw)
}

// encodeFragmentRaw is the inner encoder: gzip BestCompression + base64url (no
// padding). Callers that have already marshaled their payload use this directly.
func encodeFragmentRaw(raw []byte) (string, error) {
	var buf bytes.Buffer
	zw, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if err != nil {
		return "", err
	}
	if _, err := zw.Write(raw); err != nil {
		return "", err
	}
	if err := zw.Close(); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf.Bytes()), nil
}

// stripFragment returns url with any existing fragment (the '#' and everything
// after it) removed. Used to strip a #src= or #data= from explorerURL before
// appending a new #q= fragment, ensuring the resulting URL has exactly one
// fragment and is valid.
func stripFragment(rawURL string) string {
	if i := strings.IndexByte(rawURL, '#'); i >= 0 {
		return rawURL[:i]
	}
	return rawURL
}

// queryCell returns a Markdown inline-code span for query when explorerURL is
// empty, or a Markdown link whose text is the inline-code span and whose target
// is the base explorer URL + "#q=" + percent-encoded query, so clicking the
// cell opens the Graph Explorer pre-seeded with that query. Any existing
// fragment on explorerURL (e.g. a #src= passed from graphExplorerLink) is
// stripped so the #q= is the only fragment and the URL is valid.
//
// Spaces are encoded as %20 (via url.PathEscape) rather than '+' (QueryEscape)
// because the browser decodes the fragment with decodeURIComponent, which turns
// %20 back into a space but leaves '+' as a literal plus character.
func queryCell(query, explorerURL string) string {
	if explorerURL == "" {
		return md.Code(query)
	}
	base := stripFragment(explorerURL)
	return md.Link(md.Code(query), strings.TrimRight(base, "/")+"/#q="+url.PathEscape(query))
}

// magnitude renders a count rounded down to its leading digit ("50+", "200+"), so a
// routing index conveys real size without churning on every increment.
//
// Leading digit rather than bare order of magnitude: collapsing 273 to "100+" reads the
// same as 136 and under-states it, losing the thing the column exists to convey. Rounding
// to 200+ keeps that while still absorbing nine increments out of ten. Under 10 it prints
// exactly: that range is stable and is where precision actually reads differently.
// kindSize renders a routing row's size, or "built in" for a kind magus supplies rather
// than the workspace.
//
// Those counts track the BINARY, and this file is committed and drift-gated, so a figure
// there makes each index disagree with every other one generated by a different magus and
// hands a regenerating contributor a diff MGS4005 refuses to stage. Withheld rather than
// coarsened: a wider bucket only makes the disagreement rarer, and the magnitude rule
// below is an argued choice about workspace counts that has no reason to move for this.
func kindSize(k types.KnowledgeRoutingKind) string {
	if k.FromBinary {
		return "built in"
	}
	return magnitude(k.Count)
}

// canon renders cmd with the canonical PATH spelling instead of this process's own
// invocation. MAGUS.md is committed once and drift-gated; its content must not depend
// on whether the generating process happened to run as `./magus` or bare `magus`.
func canon(cmd hint.Command, args ...string) string {
	return cmd.WithAs(hint.DefaultBinaryName, args...)
}

func magnitude(n int) string {
	if n < 10 {
		return strconv.Itoa(n)
	}
	step := 10
	for n/step >= 10 {
		step *= 10
	}
	return strconv.Itoa((n/step)*step) + "+"
}

// WriteTargetGraphMarkdown renders a workspace's MAGUS.md: a routing index, not a
// catalog. It leads with the knowledge-graph "query first" section, then lists
// every project's targets with a one-line summary each, and points the reader at
// `magus describe target <name>` for a target's fully-evaluated dispatch plan. The
// per-target dispatch plan and any drawn graph deliberately do
// not live here: their bulk made the file useless as in-context routing, and both
// are one command (or the Graph Explorer link) away. It is engine- and
// repo-agnostic: `magus describe graph -o markdown` produces it for any magus
// workspace, which is how a project's MAGUS.md is generated and drift-checked.
// Output is deterministic (no timestamps) so it can back a drift gate.
//
// routing supplies the workspace-wide tables. Pass nil for an index scoped to some
// projects: each renders as a breadcrumb leaf, so nothing outside it can change its
// bytes beyond the neighbors it links.
//
// indexes maps every workspace project path to the MAGUS.md it declares (project
// relative), including projects out of scope, so a leaf can link its neighbors.
func WriteTargetGraphMarkdown(w io.Writer, out types.TargetGraphOutput, routing *types.KnowledgeRouting, indexes map[string]string, explorerURL string, defaultCharms []string) error {
	var b md.Builder

	if routing == nil {
		for _, p := range nonEmptyProjects(out) {
			writeLeaf(&b, p, indexes)
		}
		_, err := b.WriteTo(w)
		return err
	}

	b.Heading(1, "Targets")
	b.Comment("Generated by `" + canon(hint.DescribeGraph, "-o", "markdown") + "`. Do not edit by hand.")

	// Staleness contract, right under the header: this file is a generated snapshot,
	// only as fresh as the last `generate`. When its counts look stale, the live
	// query tools (not this file) are the source of truth.
	//
	// NO catalog fingerprint here, deliberately. It named the build that wrote the
	// file, meant to make a cross-branch regeneration legible as that rather than as
	// an ordinary change. It did the opposite: this file is drift-gated, the
	// fingerprint is a property of the BINARY rather than of the content, and two
	// builds of the same source produced different values, so a regeneration that
	// changed nothing at all still rewrote the line and failed the gate, with the
	// fingerprint as the entire diff. Content-identical output must not touch the
	// file. The fingerprint still rides the JSON export (magus graph export), which
	// is where attribution was actually wanted and where nothing gates on equality.
	provenance := "Generated by " + md.Code(canon(hint.Run, "generate:rw", ".")) + ". Do not edit by hand."
	b.Quote(provenance, "If the counts look stale, trust "+md.Code(canon(hint.Query))+" over this file.")

	// Default charms apply to every local `magus run`; surfaced only when the
	// workspace config sets them. Omitted entirely when there are none, so the
	// header carries no empty line to read past.
	if len(defaultCharms) > 0 {
		b.Paragraph("Default charms: " + strings.Join(defaultCharms, ", ") +
			" (local runs write; CI strips them with " + md.Code("--no-default-charms") + ").")
	}

	b.Paragraph("A **target** is a named unit of work (build, test, lint, ...) declared as an `export fun` in a " +
		"project's magusfile. This is a routing index: every target with a one-line summary, plus the " +
		"commands that expand any one of them. It is extracted statically from the magusfile source, so it " +
		"stays in lockstep with how the project actually builds.")

	// Route by question, front-loaded as the first section: an agent lands on the
	// exact command before scrolling any table. Static routing text: none of it is
	// derived from the graph.
	b.Heading(2, "Route by question")
	b.Table([]string{"To find out", "Run"}, []md.Align{md.Left, md.Left}, [][]string{
		{"what exists / what relates", md.Code(canon(hint.Query, `"<terms>"`))},
		{"is this file generated", md.Code(canon(hint.DescribeFile, "<path>"))},
		{"what a target runs", md.Code(canon(hint.DescribeTarget, "<name>"))},
		{"what my change affected", md.Code(canon(hint.Affected, "ci"))},
		{"a failing run's output", md.Code(canon(hint.QueryOutput, "<ref>"))},
	})

	b.Heading(2, "Quick start")
	b.AlignedCodeBlock("sh", []md.CodeLine{
		{Code: canon(hint.Run, "<target>"), Note: "from inside the project directory"},
		{Code: canon(hint.Run, "<target>", "<path>"), Note: "from anywhere in the workspace"},
		{Code: canon(hint.Run, "<target>:<charm>"), Note: "change HOW it runs (e.g. lint:rw)"},
	})
	b.Paragraph("Unfamiliar with a term? See the " + md.Link("Glossary", glossaryDocURL) + ".")

	// A target's full evaluated dispatch plan is the bulk this index leaves out. The
	// agent tooling (MCP, skills) is not listed: hosts discover it themselves.
	b.Paragraph("Need the detail this index leaves out? Run " + md.Code(canon(hint.DescribeTarget, "<name>")) +
		" for a target's fully-evaluated dispatch plan (sources, outputs, spells, command, policy).")

	// Prefer a picture: a link to the hosted Graph Explorer preloaded with this
	// repo's committed graph.json (emitted only when that link resolves).
	if explorerURL != "" {
		b.Paragraph("Prefer a picture? Explore this graph in the " + md.Link("Graph Explorer", explorerURL) +
			" - an interactive, force-directed view of this repo's committed graph.json (it renders in your browser; nothing is uploaded).")
	}

	projects := nonEmptyProjects(out)
	writeRouting(&b, routing, indexes, explorerURL)

	// A project with its own index is reached through the routing link, so its table
	// is not repeated here.
	for _, p := range projects {
		if p.Index != "" && p.Path != "." {
			continue
		}
		b.Heading(2, "Project: "+projectLabel(p))
		writeTargetTable(&b, p)
	}

	// The root index is reference reading an agent opens partway through a task.
	_, err := io.WriteString(w, md.WithContents(string(b.Bytes())))
	return err
}

// writeLeaf emits a scoped project's index: a breadcrumb to its neighbors, the query
// that scopes to it, and its target table. Nothing here is workspace-wide, so the
// bytes move only with the project and the index paths of the projects it links.
func writeLeaf(b *md.Builder, p types.TargetGraphProject, indexes map[string]string) {
	b.Heading(1, projectLabel(p))
	b.Comment("Generated by `" + canon(hint.DescribeGraph, "-o", "markdown") + "`. Do not edit by hand.")

	if p.Path != "." {
		if up, ok := indexLink(p.Path, ".", indexes); ok {
			b.Paragraph("Up: " + md.Link("workspace index", up))
		}
	}
	if len(p.DependsOn) > 0 {
		deps := make([]string, 0, len(p.DependsOn))
		for _, d := range p.DependsOn {
			label := types.ProjectLabel(d, "")
			if href, ok := indexLink(p.Path, d, indexes); ok {
				deps = append(deps, md.Link(label, href))
			} else {
				deps = append(deps, label)
			}
		}
		b.Paragraph("Depends on: " + strings.Join(deps, ", "))
	}
	b.Paragraph("Query: " + md.Code(canon(hint.Query, "project="+p.Path)))

	writeTargetTable(b, p)
}

func writeTargetTable(b *md.Builder, p types.TargetGraphProject) {
	if len(p.Cycle) > 0 {
		b.Paragraph("> dependency cycle: " + strings.Join(p.Cycle, " -> "))
	}
	rows := make([][]string, 0, len(p.Nodes))
	for _, n := range catalogOrder(p.Nodes) {
		rows = append(rows, []string{md.Code(n.Name), firstDocLine(n.Doc)})
	}
	b.Table([]string{"Target", "What it does"}, []md.Align{md.Left, md.Left}, rows)
}

// indexLink is the forward-slash path from project from's directory to the index
// project to declares, reporting false when to declares none.
func indexLink(from, to string, indexes map[string]string) (string, bool) {
	idx := indexes[to]
	if idx == "" {
		return "", false
	}
	rel, err := filepath.Rel(from, path.Join(to, idx))
	if err != nil {
		return "", false
	}
	return filepath.ToSlash(rel), true
}

// firstDocLine returns the first line of a target's doc comment, trimmed, with
// any pipe escaped so it can sit in a Markdown table cell. Empty for an
// undocumented target.
func firstDocLine(doc string) string {
	if i := strings.IndexByte(doc, '\n'); i >= 0 {
		doc = doc[:i]
	}
	return strings.ReplaceAll(strings.TrimSpace(doc), "|", `\|`)
}

// writeRouting emits the "query first" section: the retrieval verbs, then the
// workspace-wide tables from r (a per-kind entry table and per-project rows). It routes
// the reader's next action to a magus query (counts + the query to run + a few
// high-degree anchor nodes); it never dumps graph data, so it stays diff-stable across
// routine edits. When explorerURL is non-empty, the query-string cells are emitted as
// Markdown links that open the Graph Explorer pre-seeded with that query (#q=...).
// A project that declares an index (indexes) links to it from its Project cell.
func writeRouting(b *md.Builder, r *types.KnowledgeRouting, indexes map[string]string, explorerURL string) {
	b.Heading(2, "Query first")
	// Deliberately NOT the node and edge totals. They move on almost every commit
	// (a doc, a file, a function is enough), so a committed, drift-gated file carrying
	// them churns on changes that have nothing to do with what this section says.
	// `magus graph stats` reports the live counts to anyone who wants them, and it is
	// right there in the block below. The schema version stays: it changes when the
	// graph's SHAPE does, which is exactly when a reader should notice.
	b.Paragraphf("This workspace has a knowledge graph (schema v%d). Query it instead "+
		"of grepping:", r.SchemaVersion)
	b.AlignedCodeBlock("sh", []md.CodeLine{
		{Code: canon(hint.Query, `"<terms>"`), Note: "kind=spell, project=pkg/foo, relation=uses, free text, kind!=op"},
		{Code: canon(hint.Explain, "<node>"), Note: "one node: its edges, provenance, blast radius"},
		{Code: canon(hint.Path, "<a>", "<b>"), Note: "how two nodes connect"},
		{Code: canon(hint.GraphStats), Note: "god nodes, orphans, doc coverage"},
		{Code: canon(hint.GraphExport, "-o", "json"), Note: "the whole graph"},
	})

	// Magnitude, not an exact count. An exact count moved whenever any node was added
	// anywhere, which churned this file constantly and buried real changes; it also
	// contradicted the header two lines above, which tells the reader to trust `magus
	// query` over this file. Magnitude keeps the one thing worth reading (whether a kind
	// holds ten things or a thousand), while its boundaries are exponentially spaced, so
	// crossings are exponentially rarer than increments. Empty kinds are already omitted
	// upstream, so a row's presence is the "is there anything here" signal.
	kindRows := make([][]string, 0, len(r.Kinds))
	for _, k := range r.Kinds {
		kindRows = append(kindRows, []string{
			k.Kind, kindSize(k), queryCell(canon(hint.Query, "kind="+k.Kind), explorerURL), md.Codes(k.Anchors),
		})
	}
	b.Table([]string{"Kind", "Size", "List them", "Anchors (most connected)"},
		[]md.Align{md.Left, md.Right}, kindRows)

	projectRows := make([][]string, 0, len(r.Projects))
	for _, p := range r.Projects {
		cell := p.Path
		if idx := indexes[p.Path]; idx != "" {
			cell = md.Link(p.Path, path.Join(p.Path, idx))
		}
		projectRows = append(projectRows, []string{
			cell, strconv.Itoa(p.TargetCount), queryCell(canon(hint.Query, "project="+p.Path), explorerURL), md.Codes(p.KeyTargets),
		})
	}
	b.Table([]string{"Project", "Targets", "Scope a query", "Key targets"},
		[]md.Align{md.Left, md.Right}, projectRows)
}

// projectLabel is the heading shown for a project: its path relative to the repo
// root (so a project at the workspace root reads as e.g. `magus`, not the
// ambiguous `.`), falling back to the workspace-relative path outside a repo. The
// bare `.` is never used as a heading — a root project with no better label reads
// as "(workspace root)".
func projectLabel(p types.TargetGraphProject) string {
	return p.Label() // the single "never render '.'" rule now lives on the type
}

// catalogOrder lists a project's targets primary-first: the targets you invoke
// directly (build, test, generate, release, …), then the supporting workers a
// worker being a target with no dependencies of its own that exists only to be
// pulled in by another. Source order is preserved within each group.
func catalogOrder(nodes []types.TargetGraphNode) []types.TargetGraphNode {
	incoming := map[string]bool{}
	for _, n := range nodes {
		for _, d := range n.Dependencies {
			incoming[d] = true
		}
	}
	primary := make([]types.TargetGraphNode, 0, len(nodes))
	var workers []types.TargetGraphNode
	for _, n := range nodes {
		if len(n.Dependencies) == 0 && incoming[n.Name] {
			workers = append(workers, n)
		} else {
			primary = append(primary, n)
		}
	}
	return append(primary, workers...)
}

// WriteTargetGraphDOT emits the target graph as Graphviz DOT, nodes qualified by
// project path so cross-project name clashes stay distinct.
func WriteTargetGraphDOT(w io.Writer, out types.TargetGraphOutput) error {
	return writeDOT(w, targetGraphIR(out))
}

// targetGraphIR maps the target dependency graph onto a dotGraph. Edges point in run
// order, from a dependency to the target that needs it. A dependency the project does
// not declare has no node, so writeDOT drops its edge.
func targetGraphIR(out types.TargetGraphOutput) dotGraph {
	g := dotGraph{Name: "targets"}
	for _, p := range nonEmptyProjects(out) {
		for _, n := range p.Nodes {
			g.Nodes = append(g.Nodes, p.Path+":"+n.Name)
		}
		for _, n := range p.Nodes {
			for _, d := range n.Dependencies {
				g.Edges = append(g.Edges, [2]string{p.Path + ":" + d, p.Path + ":" + n.Name})
			}
		}
	}
	return g
}

// nonEmptyProjects drops projects with no extracted targets (e.g. a not-yet-
// supported engine) so they don't clutter the rendered graph.
func nonEmptyProjects(out types.TargetGraphOutput) []types.TargetGraphProject {
	ps := make([]types.TargetGraphProject, 0, len(out.Projects))
	for _, p := range out.Projects {
		if len(p.Nodes) > 0 {
			ps = append(ps, p)
		}
	}
	return ps
}
