package render

import (
	"bytes"
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/egladman/magus/types"
)

// WriteTargetGraphMarkdown renders a workspace's target graph as a one-stop
// MAGUS.md cheat sheet: a quick-start, then a per-project section where every
// target carries its doc, both invocation forms, the charm example commands, its
// dependencies, and any rendered command or non-default policy — followed by a
// glossary and the Mermaid dependency graph. eval supplies the fully-evaluated
// dispatch plan keyed by evalKey(path, target); when it is nil (e.g. a unit test
// that has only the static graph) the dispatch-derived bits are simply omitted.
// It is engine- and repo-agnostic — `magus describe graph -o markdown` produces
// it for any magus workspace, which is how a project's MAGUS.md is generated and
// drift-checked.
func WriteTargetGraphMarkdown(w io.Writer, out types.TargetGraphOutput, eval map[string]types.EvaluatedTargetEntry) error {
	var b bytes.Buffer // accumulate, then one write — keeps the body free of per-line error checks

	b.WriteString("# Targets\n\n")
	b.WriteString("<!-- Generated by `magus describe graph -o markdown`. Do not edit by hand. -->\n\n")
	b.WriteString("A **target** is a named operation (build, test, lint, …) declared as an `export fun` in a " +
		"project's magusfile. This cheat sheet (the per-target catalog and dependency graph below) is " +
		"extracted statically from the magusfile source, so it stays in lockstep with how the project " +
		"actually builds.\n\n")

	b.WriteString("## Quick start\n\n")
	b.WriteString("```sh\n")
	b.WriteString("magus run <target>            # from inside the project directory\n")
	b.WriteString("magus run <target> <path>     # from anywhere in the workspace\n")
	b.WriteString("magus run <target>:<charm>    # change HOW it runs (e.g. lint:rw)\n")
	b.WriteString("```\n\n")
	b.WriteString("Unfamiliar with a term? See the [Glossary](#glossary).\n\n")

	for _, p := range nonEmptyProjects(out) {
		fmt.Fprintf(&b, "## `%s`\n\n", projectLabel(p))
		if len(p.Cycle) > 0 {
			fmt.Fprintf(&b, "> ⚠️ dependency cycle: %s\n\n", strings.Join(p.Cycle, " → "))
		}
		writeDispatchDefaults(&b, p.Path, projectLabel(p), eval)
		for _, n := range catalogOrder(p.Nodes) {
			writeTargetSection(&b, p.Path, n, eval)
		}
	}

	writeGlossary(&b)

	b.WriteString("## Dependency graph\n\n```mermaid\n")
	if err := WriteTargetGraphMermaid(&b, out); err != nil {
		return err // bytes.Buffer never errors; satisfies the interface
	}
	b.WriteString("```\n")

	_, err := w.Write(b.Bytes())
	return err
}

// evalKey is the lookup key for an evaluated target, joining project path and
// target name on a NUL that can't occur in either.
func evalKey(path, target string) string { return path + "\x00" + target }

// projectLabel is the heading shown for a project: its path relative to the repo
// root (so a project at the workspace root reads as e.g. `magus`, not the
// ambiguous `.`), falling back to the workspace-relative path outside a repo. The
// `magus run <target> <path>` examples still use the workspace-relative Path.
func projectLabel(p types.TargetGraphProject) string {
	if p.RelPath != "" {
		return p.RelPath
	}
	return p.Path
}

// catalogOrder lists a project's targets primary-first: the targets you invoke
// directly (build, test, generate, release, …), then the supporting workers a
// worker being a target with no dependencies of its own that exists only to be
// pulled in by another. Source order is preserved within each group.
func catalogOrder(nodes []types.TargetGraphNode) []types.TargetGraphNode {
	incoming := map[string]bool{}
	for _, n := range nodes {
		for _, d := range n.Deps {
			incoming[d] = true
		}
	}
	primary := make([]types.TargetGraphNode, 0, len(nodes))
	var workers []types.TargetGraphNode
	for _, n := range nodes {
		if len(n.Deps) == 0 && incoming[n.Name] {
			workers = append(workers, n)
		} else {
			primary = append(primary, n)
		}
	}
	return append(primary, workers...)
}

// charmGloss is the one-line "what it does" for the charms magus ships knowledge
// of, so a target's `name:charm` example command reads as documentation. A charm
// not listed here still gets an example line, just with a generic note.
var charmGloss = map[string]string{
	types.CharmReadWrite: "mutate in place instead of checking",
	"container":          "build the container image instead of the host binary",
}

// writeDispatchDefaults emits, once per project, the collapsed block of inputs,
// outputs, and spells that every target in the project shares (they all key off
// the project's base spec). Pulled from any one evaluated target; skipped when no
// evaluated data is available.
func writeDispatchDefaults(b *bytes.Buffer, path, label string, eval map[string]types.EvaluatedTargetEntry) {
	def, ok := projectDefaults(path, eval)
	if !ok {
		return
	}
	b.WriteString("<details>\n")
	fmt.Fprintf(b, "<summary><b>Shared defaults</b>: inputs, outputs &amp; spells shared by every target in <code>%s</code></summary>\n\n", label)
	b.WriteString("```text\n")
	if s := uniqSorted(def.Sources); len(s) > 0 {
		fmt.Fprintf(b, "sources  %s\n", strings.Join(s, ", "))
	}
	if len(def.Outputs) > 0 {
		fmt.Fprintf(b, "outputs  %s\n", strings.Join(def.Outputs, ", "))
	}
	if line := spellsLine(def.Spells); line != "" {
		fmt.Fprintf(b, "spells   %s\n", line)
	}
	b.WriteString("```\n\n</details>\n\n")
}

// cmdLine is one `magus run …` example with its trailing explanatory comment.
type cmdLine struct{ code, note string }

// writeCommandBlock renders a bold label followed by a fenced sh block of the
// given command lines, with their `# note` comments aligned into a column.
func writeCommandBlock(b *bytes.Buffer, label string, lines []cmdLine) {
	width := 0
	for _, l := range lines {
		if len(l.code) > width {
			width = len(l.code)
		}
	}
	fmt.Fprintf(b, "**%s**\n\n```sh\n", label)
	for _, l := range lines {
		fmt.Fprintf(b, "%-*s  # %s\n", width, l.code, l.note)
	}
	b.WriteString("```\n\n")
}

// writeTargetSection renders one target: heading, doc, the base invocation block,
// a separate charm-variant block when the target branches on charms, dependencies,
// and the dispatch-derived extras (rendered command, non-default details) when
// eval carries them.
func writeTargetSection(b *bytes.Buffer, path string, n types.TargetGraphNode, eval map[string]types.EvaluatedTargetEntry) {
	fmt.Fprintf(b, "### `%s`\n\n", n.Name)
	if n.Doc != "" {
		fmt.Fprintf(b, "%s\n\n", n.Doc)
	}

	// The two canonical forms. Charm variants get their own block below so this
	// one (and the Executes command) stay about the plain invocation; "Defaults"
	// pairs with the "Charms" label.
	writeCommandBlock(b, "Defaults", []cmdLine{
		{fmt.Sprintf("magus run %s", n.Name), "from the project directory"},
		{fmt.Sprintf("magus run %s %s", n.Name, path), "from the workspace root"},
	})

	if len(n.Charms) > 0 {
		charmLines := make([]cmdLine, 0, len(n.Charms))
		for _, c := range n.Charms {
			note := charmGloss[c]
			if note == "" {
				note = fmt.Sprintf("apply the %s charm", c)
			}
			charmLines = append(charmLines, cmdLine{fmt.Sprintf("magus run %s:%s", n.Name, c), note})
		}
		writeCommandBlock(b, "Charms", charmLines)
	}

	if len(n.Deps) > 0 {
		b.WriteString("**Depends on:**\n\n")
		for _, d := range n.Deps {
			// Link each dependency to its own section. GitHub derives a heading's
			// anchor by lowercasing and stripping the backticks, so `man-generate`
			// resolves to #man-generate.
			fmt.Fprintf(b, "- [`%s`](#%s)\n", d, strings.ToLower(d))
		}
		b.WriteString("\n")
	}

	e, ok := eval[evalKey(path, n.Name)]
	if !ok {
		return
	}
	if cmds := renderedCommands(e); len(cmds) > 0 {
		b.WriteString("**Executes**\n\n```sh\n")
		for _, c := range cmds {
			b.WriteString(c + "\n")
		}
		b.WriteString("```\n\n")
	}
	if notes := policyNotes(e.Policy); len(notes) > 0 {
		fmt.Fprintf(b, "**Details:** %s\n\n", strings.Join(notes, " · "))
	}
}

// writeGlossary emits the static glossary of magus terms. It is hand-authored
// (not derived from the in-code definitions) so it stays short enough for a cheat
// sheet; keep it in sync with the longer `magus describe <noun>` definitions.
func writeGlossary(b *bytes.Buffer) {
	b.WriteString("## Glossary\n\n")
	for _, g := range []struct{ term, def string }{
		{"Workspace", "the magus root directory that owns a set of projects and shared config; the unit magus operates over."},
		{"Project", "a directory magus recognized as a unit of work (it has a magusfile); the unit of caching, scheduling, and dependency tracking."},
		{"Magusfile", "the `magusfile.bzz` / `magusfile.tl` that declares a project's targets (as `export fun`s) and binds its spells."},
		{"Target", "a named operation (`build`, `test`, …) you invoke with `magus run <target>`; it may compose a spell's tool-native operations and depend on other targets."},
		{"Spell", "a language/runtime adapter (e.g. `go`, `md`) that maps generic targets onto a toolchain's real commands."},
		{"Charm", "an execution modifier attached with `:` (`lint:rw`) that changes _how_ a target runs, not _which_ one; the built-in `rw` flips a check-only target to mutate in place, and `ci` always strips it."},
		{"Module", "a magus stdlib namespace a magusfile imports for host capabilities: filesystem, exec, vcs, and more."},
		{"Buzz", "one of the magusfile languages magus supports (the `.bzz` engine); Teal (`.tl`) is the other."},
	} {
		fmt.Fprintf(b, "- **%s**: %s\n", g.term, g.def)
	}
	b.WriteString("\n")
}

// projectDefaults returns any evaluated target belonging to path; every target in
// a project shares the same base-spec sources, outputs, and spells, so the first
// match speaks for all. The bool is false when eval carries nothing for the path.
func projectDefaults(path string, eval map[string]types.EvaluatedTargetEntry) (types.EvaluatedTargetEntry, bool) {
	for _, e := range eval {
		if e.Project == path {
			return e, true
		}
	}
	return types.EvaluatedTargetEntry{}, false
}

// spellsLine renders the project's spells as a comma-separated list, annotating
// any spell that carries effective claims.
func spellsLine(spells []types.EvaluatedSpellEntry) string {
	parts := make([]string, 0, len(spells))
	for _, s := range spells {
		if len(s.EffectiveClaims) > 0 {
			parts = append(parts, fmt.Sprintf("%s (claims: %s)", s.Name, strings.Join(s.EffectiveClaims, ", ")))
		} else {
			parts = append(parts, s.Name)
		}
	}
	return strings.Join(parts, ", ")
}

// renderedCommands returns the statically-known argv of each spell that resolves
// to one, one command per string. Empty for function-op targets whose body isn't
// a declarative spell op.
func renderedCommands(e types.EvaluatedTargetEntry) []string {
	var out []string
	for _, s := range e.Spells {
		if len(s.Command) > 0 {
			out = append(out, strings.Join(s.Command, " "))
		}
	}
	return out
}

// policyNotes describes the non-default behavioural policy of a target, or nil
// when the policy is unset or all-default.
func policyNotes(p *types.TargetPolicy) []string {
	if p == nil {
		return nil
	}
	var out []string
	if p.CheckClean {
		out = append(out, "check-clean (fails if the tree is dirty afterward)")
	}
	if p.TrackFlake {
		out = append(out, "flake-tracked (retries a flaky failure)")
	}
	if p.NoCache {
		out = append(out, "uncached (always runs)")
	}
	if p.Isolated {
		out = append(out, "isolated (runs alone, no concurrent targets)")
	}
	return out
}

// WriteTargetGraphMermaid emits a magus.depends_on target graph as a Mermaid
// flowchart, rendered top-down. Within a project, worker targets that share a
// trailing `-<segment>` (e.g. `man-generate`, `docs-generate`) are boxed together
// in a stage subgraph; singletons stay loose. The composite that shares the box's
// name (e.g. `generate`) stays outside the box, and an edge into the box lands on
// the box itself rather than on a worker inside it. Nodes are styled by role —
// anchors (nothing depends on them, i.e. the targets you invoke), leaves (no
// deps), and the composites in between. With more than one project each is wrapped
// in its own subgraph and node ids are prefixed, so a `build` in two projects
// stays distinct. It is the one Mermaid emitter for the target graph: `magus
// describe graph -o mermaid` and the markdown doc both route through it.
func WriteTargetGraphMermaid(w io.Writer, out types.TargetGraphOutput) error {
	projects := nonEmptyProjects(out)
	multi := len(projects) > 1

	var b strings.Builder
	b.WriteString("graph TD\n")

	// Collected for the trailing `class` assignments, one bucket per role.
	var anchorIDs, leafIDs, midIDs []string
	edges := false

	for i, p := range projects {
		prefix, base := "", "    "
		if multi {
			prefix, base = fmt.Sprintf("p%d_", i), "        "
			fmt.Fprintf(&b, "    subgraph p%d[%q]\n", i, p.Path)
		}

		// A node is an anchor if nothing in the project depends on it; a leaf if it
		// has no deps of its own; otherwise a composite ("mid").
		known := map[string]bool{}
		for _, n := range p.Nodes {
			known[n.Name] = true
		}
		incoming := map[string]bool{}
		for _, n := range p.Nodes {
			for _, d := range n.Deps {
				if known[d] {
					incoming[d] = true
				}
			}
		}
		emit := func(n types.TargetGraphNode, indent string) {
			id := prefix + mermaidID(n.Name)
			fmt.Fprintf(&b, "%s%s(%q)\n", indent, id, n.Name)
			switch {
			case !incoming[n.Name]:
				anchorIDs = append(anchorIDs, id)
			case len(n.Deps) == 0:
				leafIDs = append(leafIDs, id)
			default:
				midIDs = append(midIDs, id)
			}
		}

		stageOf, stageOrder := stageGroups(p.Nodes)
		for _, stage := range stageOrder {
			fmt.Fprintf(&b, "%ssubgraph %sstage_%s[%q]\n", base, prefix, mermaidID(stage), stage)
			for _, n := range p.Nodes {
				if stageOf[n.Name] == stage {
					emit(n, base+"    ")
				}
			}
			fmt.Fprintf(&b, "%send\n", base)
		}
		for _, n := range p.Nodes {
			if stageOf[n.Name] == "" {
				emit(n, base)
			}
		}

		// endpoint maps a target to the id an edge should touch: a node sitting in a
		// stage box resolves to the box itself, so an edge lands on the box rather
		// than burying itself among the workers inside.
		endpoint := func(name string) string {
			if s := stageOf[name]; s != "" {
				return prefix + "stage_" + mermaidID(s)
			}
			return prefix + mermaidID(name)
		}
		seen := map[string]bool{}
		for _, n := range p.Nodes {
			src := endpoint(n.Name)
			for _, d := range n.Deps {
				dst := endpoint(d)
				if src == dst {
					continue // both ends collapse to the same stage box: nothing to draw
				}
				if key := src + "\x00" + dst; !seen[key] {
					seen[key] = true
					fmt.Fprintf(&b, "%s%s --> %s\n", base, src, dst)
					edges = true
				}
			}
		}

		if multi {
			b.WriteString("    end\n")
		}
	}

	if len(projects) == 0 || !edges {
		b.WriteString("    %% no dependency edges\n")
	}

	// Role styling. Fills carry an explicit text color so they read on both the
	// light and dark Mermaid themes GitHub picks per viewer.
	b.WriteString("    classDef anchor fill:#2563eb,color:#ffffff,stroke:#1e40af,stroke-width:2px\n")
	b.WriteString("    classDef mid fill:#e2e8f0,color:#0f172a,stroke:#94a3b8\n")
	b.WriteString("    classDef leaf fill:#dcfce7,color:#14532d,stroke:#86efac\n")
	for _, c := range []struct {
		name string
		ids  []string
	}{{"anchor", anchorIDs}, {"mid", midIDs}, {"leaf", leafIDs}} {
		if len(c.ids) > 0 {
			fmt.Fprintf(&b, "    class %s %s\n", strings.Join(uniqSorted(c.ids), ","), c.name)
		}
	}

	_, err := io.WriteString(w, b.String())
	return err
}

// stageGroups buckets a project's *worker* targets by their trailing `-<segment>`
// (e.g. `man-generate`, `docs-generate`), returning a name→stage map (empty stage
// means ungrouped) and the stage names sorted. A segment forms a stage only when
// two or more workers share it, so a lone `release` or `watch` stays loose. The
// bare composite that shares the segment name (e.g. `generate`, which depends on
// the `*-generate` workers) is deliberately left out of its own box: the box reads
// as the steps that target runs, and an edge to it lands on the box instead of a
// `generate` node nested inside a `generate` subgraph.
func stageGroups(nodes []types.TargetGraphNode) (map[string]string, []string) {
	workers := map[string]int{} // segment -> count of members that are not the bare composite
	segment := map[string]string{}
	for _, n := range nodes {
		s := lastSegment(n.Name)
		segment[n.Name] = s
		if n.Name != s {
			workers[s]++
		}
	}
	stageOf := map[string]string{}
	seen := map[string]bool{}
	var order []string
	for _, n := range nodes {
		s := segment[n.Name]
		if n.Name == s || workers[s] < 2 {
			continue // the composite itself, or a segment without enough workers, stays loose
		}
		stageOf[n.Name] = s
		if !seen[s] {
			seen[s] = true
			order = append(order, s)
		}
	}
	slices.Sort(order)
	return stageOf, order
}

// lastSegment returns the text after the final '-', or the whole name if none.
func lastSegment(name string) string {
	if i := strings.LastIndexByte(name, '-'); i >= 0 {
		return name[i+1:]
	}
	return name
}

// uniqSorted returns s sorted with duplicates removed.
func uniqSorted(s []string) []string {
	slices.Sort(s)
	return slices.Compact(s)
}

// WriteTargetGraphDOT emits the same target graph as Graphviz DOT, with nodes
// qualified by project path so cross-project name clashes stay distinct.
func WriteTargetGraphDOT(w io.Writer, out types.TargetGraphOutput) error {
	if _, err := fmt.Fprintln(w, "digraph targets {"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "  rankdir=LR;"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "  node [shape=box, style=rounded];"); err != nil {
		return err
	}
	for _, p := range nonEmptyProjects(out) {
		for _, n := range p.Nodes {
			qualified := p.Path + ":" + n.Name
			if _, err := fmt.Fprintf(w, "  %q;\n", qualified); err != nil {
				return err
			}
			for _, d := range n.Deps {
				if _, err := fmt.Fprintf(w, "  %q -> %q;\n", qualified, p.Path+":"+d); err != nil {
					return err
				}
			}
		}
	}
	_, err := fmt.Fprintln(w, "}")
	return err
}

// nonEmptyProjects drops projects with no extracted targets (e.g. a not-yet-
// supported engine) so they don't clutter the rendered graph.
func nonEmptyProjects(out types.TargetGraphOutput) []types.TargetGraphProject {
	ps := make([]types.TargetGraphProject, 0, len(out.Projects))
	for _, p := range out.Projects {
		if len(p.Nodes) > 0 {
			ps = append(ps, p)
		}
	}
	return ps
}
