package render

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"slices"
	"strconv"
	"strings"

	"github.com/egladman/magus/internal/render/md"
	"github.com/egladman/magus/types"
)

// glossaryDocURL is the canonical, hosted magus glossary. MAGUS.md links out to it
// instead of embedding its own copy, so the term definitions have a single source
// of truth on the docs site.
const glossaryDocURL = "https://eli.gladman.cc/magus/glossary/"

// fragmentCap is a conservative per-project ceiling for deep-link fragments.
// Safari caps URLs near 80 KB and older Firefox near 64 KB; targets graphs are
// much smaller than a full knowledge graph, but we skip silently rather than
// emitting a link that won't open in constrained browsers.
const fragmentCap = 200 * 1024

// encodeDataFragment gzip-compresses then base64url-encodes (no padding) a value
// for use in a #data= URL fragment. The browser reverses it with
// DecompressionStream('gzip'). gzip header fields are left at their zero values
// to guarantee byte-stable output across calls.
func encodeDataFragment(v any) (string, error) {
	raw, err := json.Marshal(v)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	zw, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if err != nil {
		return "", err
	}
	if _, err := zw.Write(raw); err != nil {
		return "", err
	}
	if err := zw.Close(); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf.Bytes()), nil
}

// queryLink returns a Markdown inline-code span for query when explorerURL is
// empty, or a Markdown link whose text is the inline-code span and whose target
// is explorerURL + "#q=" + url-encoded query, so clicking the cell opens the
// Graph Explorer pre-seeded with that query.
func queryLink(query, explorerURL string) string {
	if explorerURL == "" {
		return md.Code(query)
	}
	return md.Link(md.Code(query), explorerURL+"#q="+url.QueryEscape(query))
}

// WriteTargetGraphMarkdown renders a workspace's target graph as a one-stop
// MAGUS.md cheat sheet: a quick-start, then a per-project section where every
// project section opens with that project's own Mermaid dependency graph, then
// every target carries its doc, both invocation forms, the charm example commands,
// its dependencies, and any rendered command or non-default policy. Term
// definitions live on the hosted docs (glossaryDocURL), not in this output.
// eval supplies the fully-evaluated
// dispatch plan keyed by EvalKey(path, target); when it is nil (e.g. a unit test
// that has only the static graph) the dispatch-derived bits are simply omitted.
// It is engine- and repo-agnostic — `magus describe graph -o markdown` produces
// it for any magus workspace, which is how a project's MAGUS.md is generated and
// drift-checked. Markdown is target-graph-only (it backs MAGUS.md); the project
// dependency graph offers only Mermaid/DOT (WriteGraphMermaid / WriteGraphDOT).
func WriteTargetGraphMarkdown(w io.Writer, out types.TargetGraphOutput, eval map[string]types.EvaluatedTargetEntry, routing *types.KnowledgeRouting, explorerURL string) error {
	var b md.Builder

	b.Heading(1, "Targets")
	b.Comment("Generated by `magus describe graph -o markdown`. Do not edit by hand.")
	b.Paragraph("A **target** is a named operation (build, test, lint, …) declared as an `export fun` in a " +
		"project's magusfile. This cheat sheet (the per-target catalog and run-order graph below) is " +
		"extracted statically from the magusfile source, so it stays in lockstep with how the project " +
		"actually builds.")

	b.Heading(2, "Quick start")
	b.AlignedCodeBlock("sh", []md.CodeLine{
		{Code: "magus run <target>", Note: "from inside the project directory"},
		{Code: "magus run <target> <path>", Note: "from anywhere in the workspace"},
		{Code: "magus run <target>:<charm>", Note: "change HOW it runs (e.g. lint:rw)"},
	})
	b.Paragraph("Unfamiliar with a term? See the " + md.Link("Glossary", glossaryDocURL) + ".")

	// Prefer a picture: a link to the hosted Graph Explorer preloaded with this
	// repo's committed graph.json (emitted only when that link resolves).
	if explorerURL != "" {
		b.Paragraph("Prefer a picture? Explore this graph in the " + md.Link("Graph Explorer", explorerURL) +
			" - an interactive, force-directed view of this repo's committed graph.json (it renders in your browser; nothing is uploaded).")
	}

	if routing != nil {
		writeRouting(&b, *routing, explorerURL)
	}

	projects := nonEmptyProjects(out)
	if len(projects) > 0 {
		if err := writeLegend(&b); err != nil {
			return err // the builder never errors; satisfies the emitter interface
		}
	}
	for _, p := range projects {
		b.Heading(2, "Project: "+projectLabel(p))
		if len(p.Cycle) > 0 {
			b.Paragraph("> ⚠️ dependency cycle: " + strings.Join(p.Cycle, " → "))
		}
		writeDispatchDefaults(&b, p.Path, projectLabel(p), eval)
		if err := writeProjectGraph(&b, p); err != nil {
			return err // the builder never errors; satisfies the emitter interface
		}
		if err := writeToolchainGraph(&b, p); err != nil {
			return err // the builder never errors; satisfies the emitter interface
		}
		if explorerURL != "" {
			singleOut := types.TargetGraphOutput{
				Definition: out.Definition,
				Projects:   []types.TargetGraphProject{p},
			}
			if frag, err := encodeDataFragment(singleOut); err == nil && len(frag) <= fragmentCap {
				link := md.Link("Explore this project's graph interactively", strings.TrimRight(explorerURL, "/")+"/#data="+frag)
				b.Paragraph(link)
			}
			// If encoding fails or the fragment exceeds the cap, skip silently.
		}
		for _, n := range catalogOrder(p.Nodes) {
			writeTargetSection(&b, p.Path, n, eval)
		}
	}

	_, err := b.WriteTo(w)
	return err
}

// writeRouting emits the "query first" section from the knowledge graph: the
// retrieval verbs, a per-kind entry table, and per-project rows. It routes the
// reader's next action to a magus query (counts + the query to run + a few
// high-degree anchor nodes); it never dumps graph data, so it stays diff-stable
// across routine edits. Generated per-repo and drift-gated like the rest of MAGUS.md.
// When explorerURL is non-empty, the query-string cells are emitted as Markdown
// links that open the Graph Explorer pre-seeded with that query (#q=...).
func writeRouting(b *md.Builder, r types.KnowledgeRouting, explorerURL string) {
	b.Heading(2, "Query first")
	b.Paragraphf("This workspace has a knowledge graph of **%d nodes** and **%d edges** "+
		"(schema v%d). Query it instead of grepping:", r.NodeCount, r.EdgeCount, r.SchemaVersion)
	b.AlignedCodeBlock("sh", []md.CodeLine{
		{Code: `magus query "<terms>"`, Note: "kind:spell, project:pkg/foo, relation:uses, free text, -negation"},
		{Code: "magus explain <node>", Note: "one node: its edges, provenance, blast radius"},
		{Code: "magus path <a> <b>", Note: "how two nodes connect"},
		{Code: "magus graph stats", Note: "god nodes, orphans, doc coverage (MCP: magus_stats)"},
		{Code: "magus graph export -o json", Note: "the whole graph (MCP: magus_query, magus_explain, magus_path)"},
	})

	kindRows := make([][]string, 0, len(r.Kinds))
	for _, k := range r.Kinds {
		kindRows = append(kindRows, []string{
			k.Kind, strconv.Itoa(k.Count), queryLink("magus query kind:"+k.Kind, explorerURL), md.Codes(k.Anchors),
		})
	}
	b.Table([]string{"Kind", "Count", "List them", "Anchors (most connected)"},
		[]md.Align{md.Left, md.Right}, kindRows)

	projectRows := make([][]string, 0, len(r.Projects))
	for _, p := range r.Projects {
		projectRows = append(projectRows, []string{
			p.Path, strconv.Itoa(p.TargetCount), queryLink("magus query project:"+p.Path, explorerURL), md.Codes(p.KeyTargets),
		})
	}
	b.Table([]string{"Project", "Targets", "Scope a query", "Key targets"},
		[]md.Align{md.Left, md.Right}, projectRows)
}

// EvalKey is the lookup key for an evaluated target, joining project path and
// target name on a NUL that can't occur in either.
func EvalKey(path, target string) string { return path + "\x00" + target }

// projectLabel is the heading shown for a project: its path relative to the repo
// root (so a project at the workspace root reads as e.g. `magus`, not the
// ambiguous `.`), falling back to the workspace-relative path outside a repo. The
// `magus run <target> <path>` examples still use the workspace-relative Path. The
// bare `.` is never used as a heading — a root project with no better label reads
// as "(workspace root)".
func projectLabel(p types.TargetGraphProject) string {
	// Prefer the repo-relative path (describe pre-computes it, collapsing the root to
	// the workspace dir name); fall back to the workspace path. types.ProjectLabel is
	// the shared "never render '.'/''" rule. Dir is unknown here, so a bare root falls
	// back to "(workspace root)".
	if p.RelPath != "" && p.RelPath != "." {
		return p.RelPath
	}
	return types.ProjectLabel(p.Path, "")
}

// catalogOrder lists a project's targets primary-first: the targets you invoke
// directly (build, test, generate, release, …), then the supporting workers a
// worker being a target with no dependencies of its own that exists only to be
// pulled in by another. Source order is preserved within each group.
func catalogOrder(nodes []types.TargetGraphNode) []types.TargetGraphNode {
	incoming := map[string]bool{}
	for _, n := range nodes {
		for _, d := range n.Dependencies {
			incoming[d] = true
		}
	}
	primary := make([]types.TargetGraphNode, 0, len(nodes))
	var workers []types.TargetGraphNode
	for _, n := range nodes {
		if len(n.Dependencies) == 0 && incoming[n.Name] {
			workers = append(workers, n)
		} else {
			primary = append(primary, n)
		}
	}
	return append(primary, workers...)
}

// charmGloss is the one-line "what it does" for the charms magus ships knowledge
// of, so a target's `name:charm` example command reads as documentation. A charm
// not listed here still gets an example line, just with a generic note.
var charmGloss = map[string]string{
	types.CharmReadWrite: "mutate in place instead of checking",
	"container":          "build the container image instead of the host binary",
}

// writeDispatchDefaults emits, once per project, the collapsed block of inputs,
// outputs, and spells that every target in the project shares (they all key off
// the project's base spec). Pulled from any one evaluated target; skipped when no
// evaluated data is available.
func writeDispatchDefaults(b *md.Builder, path, label string, eval map[string]types.EvaluatedTargetEntry) {
	def, ok := projectDefaults(path, eval)
	if !ok {
		return
	}
	summary := fmt.Sprintf("<b>Shared defaults</b>: inputs, outputs &amp; spells shared by every target in <code>%s</code>", label)
	b.Details(summary, func(b *md.Builder) {
		var lines []string
		if s := uniqSorted(def.Sources); len(s) > 0 {
			lines = append(lines, "sources  "+strings.Join(s, ", "))
		}
		if len(def.Outputs) > 0 {
			lines = append(lines, "outputs  "+strings.Join(def.Outputs, ", "))
		}
		if line := spellsLine(def.Spells); line != "" {
			lines = append(lines, "spells   "+line)
		}
		b.CodeBlock("text", lines...)
	})
}

// targetRoleClasses style target nodes by role; externalClass styles a
// cross-project dependency node. Shared by the per-project graphs and the legend
// so the key always matches what it documents.
var targetRoleClasses = []renderClass{
	{Name: "anchor", Style: "fill:#2563eb,color:#ffffff,stroke:#1e40af,stroke-width:2px"},
	{Name: "target", Style: "fill:#e2e8f0,color:#0f172a,stroke:#94a3b8"},
}

var externalClass = renderClass{Name: "external", Style: "fill:#fef9c3,color:#713f12,stroke:#ca8a04,stroke-dasharray:5 3"}

// writeLegend emits a one-off Mermaid key for the per-project graphs below: the
// role colors and the external-project shape, plus a note for the two conventions
// a legend node can't show on its own (the spell box and the dotted cross-project
// arrow).
func writeLegend(b *md.Builder) error {
	b.Heading(2, "Reading the graphs")
	g := renderGraph{Direction: "LR"}
	g.Groups = []renderGroup{{ID: "legend", Label: "Legend"}}
	g.Nodes = []renderNode{
		{ID: "lg_anchor", Label: "Top-level target", Shape: shapeRounded, Classes: []string{"anchor"}, Group: "legend"},
		{ID: "lg_target", Label: "Target", Shape: shapeRounded, Classes: []string{"target"}, Group: "legend"},
		{ID: "lg_ext", Label: "Other project", Shape: shapeSubroutine, Classes: []string{"external"}, Group: "legend"},
		{ID: "lg_spell", Label: "Spell", Shape: shapeHexagon, Classes: []string{"spell"}, Group: "legend"},
	}
	g.Classes = append(slices.Clone(targetRoleClasses), externalClass, spellClass)
	if err := b.Fenced("mermaid", func(w io.Writer) error { return writeMermaid(w, g) }); err != nil {
		return err
	}
	b.List(
		"Every rounded box is a **target** you can `magus run`. **Blue** is a top-level "+
			"target (nothing else depends on it — a typical entry point); **gray** ones are pulled in as "+
			"dependencies.",
		"Arrows show **run order**: a target's dependencies run before it, so the graph flows "+
			"left → right (e.g. `preflight` runs first, `ci` last).",
		"A dotted arrow marks a **cross-project dependency** (the other project's target runs first).",
		"Each project's **Toolchain** graph (top-down) shows which **spell** each target drives.",
	)
	return nil
}

// writeProjectGraph emits the project's own Mermaid run-order graph (LR) under a
// bold label, inline at the top of its section: its targets, coloured by role, edges
// in run order (a dependency points at the target that needs it), and a dotted edge
// from each [[project:target]] it depends on across project boundaries (declared via
// project imports). A target's spells live in writeToolchainGraph, not here.
func writeProjectGraph(b *md.Builder, p types.TargetGraphProject) error {
	b.Paragraph(md.Bold("Run order"))
	g := targetGraphIR(types.TargetGraphOutput{Projects: []types.TargetGraphProject{p}})
	addEntryPointCluster(&g, p)
	addCrossTargetDependencies(&g, p)
	return b.Fenced("mermaid", func(w io.Writer) error { return writeMermaid(w, g) })
}

// addEntryPointCluster groups a project's entry-point targets (the ones nothing
// depends on) into one *invisible* subgraph — transparent fill and stroke, blank
// label — so dagre keeps them together in the layout without drawing a box. No-op
// for fewer than two entry points (nothing to cluster). The grouping carries no
// styling of its own; the nodes keep their role colors.
func addEntryPointCluster(g *renderGraph, p types.TargetGraphProject) {
	anchors := anchorNames(p.Nodes)
	if len(anchors) < 2 {
		return
	}
	anchorIDs := make(map[string]bool, len(anchors))
	for name := range anchors {
		anchorIDs[mermaidID(name)] = true // per-project graph is single-project: no id prefix
	}
	const clusterID = "entry_cluster"
	moved := 0
	for i := range g.Nodes {
		if anchorIDs[g.Nodes[i].ID] && g.Nodes[i].Group == "" {
			g.Nodes[i].Group = clusterID
			moved++
		}
	}
	if moved < 2 {
		return
	}
	g.Groups = append(g.Groups, renderGroup{ID: clusterID, Label: " ", Style: "fill:transparent,stroke:transparent"})
}

// anchorNames returns the targets nothing else in the project depends on — the
// entry points you invoke directly.
func anchorNames(nodes []types.TargetGraphNode) map[string]bool {
	incoming := map[string]bool{}
	for _, n := range nodes {
		for _, d := range n.Dependencies {
			incoming[d] = true
		}
	}
	anchors := make(map[string]bool)
	for _, n := range nodes {
		if !incoming[n.Name] {
			anchors[n.Name] = true
		}
	}
	return anchors
}

// spellClass styles a spell node in the Toolchain graph (and its legend entry).
var spellClass = renderClass{Name: "spell", Style: "fill:#ede9fe,color:#4c1d95,stroke:#a78bfa"}

// writeToolchainGraph emits a project's Toolchain graph: a top-down (TB) Mermaid
// chart drawing each spell-driving target to the spell it drives, with the tool-
// native operations on the edge. It is a deliberately separate graph from the LR
// dependency graph above — spells are a different relationship, and Mermaid can't
// reliably mix flow directions within one diagram. Skipped when no target in the
// project drives a spell.
func writeToolchainGraph(b *md.Builder, p types.TargetGraphProject) error {
	hasSpell := false
	for _, n := range p.Nodes {
		if len(n.Spells) > 0 {
			hasSpell = true
			break
		}
	}
	if !hasSpell {
		return nil
	}

	b.Paragraph(md.Bold("Toolchain"))
	b.Paragraph("Which spell each target drives; edge labels are the tool-native operations.")
	g := renderGraph{Direction: "TB"}
	spellSeen := map[string]bool{}
	for _, n := range p.Nodes {
		if len(n.Spells) == 0 {
			continue
		}
		tid := "t_" + mermaidID(n.Name)
		g.Nodes = append(g.Nodes, renderNode{ID: tid, Label: n.Name, Shape: shapeRounded})
		for _, s := range n.Spells {
			sid := "sp_" + mermaidID(s.Spell)
			if !spellSeen[s.Spell] {
				spellSeen[s.Spell] = true
				g.Nodes = append(g.Nodes, renderNode{ID: sid, Label: s.Spell, Shape: shapeHexagon, Classes: []string{"spell"}})
			}
			g.Edges = append(g.Edges, renderEdge{From: tid, To: sid, Label: strings.Join(s.Ops, ", ")})
		}
	}
	g.Classes = []renderClass{spellClass}
	return b.Fenced("mermaid", func(w io.Writer) error { return writeMermaid(w, g) })
}

// addCrossTargetDependencies draws p's target-level cross-project dependencies
// (node.CrossDependencies, from project imports): a dotted "needs" edge from the
// specific target to an external [[project:target]] node, deduped. This is the only
// cross-project representation — project-level depends_on is an affected/scheduling
// concern that isn't drawn (a magusfile that wants the edge in the graph declares it
// at the target via a project import). No-op when p has no cross-target deps.
func addCrossTargetDependencies(g *renderGraph, p types.TargetGraphProject) {
	extSeen := map[string]bool{}
	for _, n := range p.Nodes {
		to := mermaidID(n.Name)
		for _, ref := range n.CrossDependencies {
			id := "xt_" + mermaidID(ref.Project) + "_" + mermaidID(ref.Target)
			if !extSeen[id] {
				extSeen[id] = true
				g.Nodes = append(g.Nodes, renderNode{ID: id, Label: ref.Project + ":" + ref.Target, Shape: shapeSubroutine, Classes: []string{"external"}})
			}
			// Run order: the other project's target runs first, so it points in. The
			// dotted style (keyed in the legend) marks it as a cross-project edge.
			g.Edges = append(g.Edges, renderEdge{From: id, To: to, Dashed: true})
		}
	}
	if len(extSeen) > 0 {
		g.Classes = append(g.Classes, externalClass)
	}
}

// writeCommandBlock renders a bold label followed by a fenced sh block of the
// given command lines, with their `# note` comments aligned into a column.
func writeCommandBlock(b *md.Builder, label string, lines []md.CodeLine) {
	b.Paragraph(md.Bold(label))
	b.AlignedCodeBlock("sh", lines)
}

// writeTargetSection renders one target: heading, doc, the base invocation block,
// a separate charm-variant block when the target branches on charms, dependencies,
// and the dispatch-derived extras (rendered command, non-default details) when
// eval carries them.
func writeTargetSection(b *md.Builder, path string, n types.TargetGraphNode, eval map[string]types.EvaluatedTargetEntry) {
	b.Heading(3, md.Code(n.Name))
	if n.Doc != "" {
		b.Paragraph(n.Doc)
	}

	// One canonical invocation, runnable from the workspace root and unambiguous:
	// the root project needs no path (it *is* the workspace root); a nested project
	// names its path so a copy-paste from the repo root hits the right project, not
	// the cwd one. The shorter in-the-project-directory form (and this path form)
	// are documented once in Quick start, so per-target blocks don't repeat both.
	// Charm variants get their own block below.
	run := fmt.Sprintf("magus run %s", n.Name)
	if path != "." && path != "" {
		run = fmt.Sprintf("magus run %s %s", n.Name, path)
	}
	writeCommandBlock(b, "Defaults", []md.CodeLine{
		{Code: run, Note: "from the workspace root"},
	})

	if len(n.Charms) > 0 {
		charmLines := make([]md.CodeLine, 0, len(n.Charms))
		for _, c := range n.Charms {
			note := charmGloss[c]
			if note == "" {
				note = fmt.Sprintf("apply the %s charm", c)
			}
			charmLines = append(charmLines, md.CodeLine{Code: fmt.Sprintf("magus run %s:%s", n.Name, c), Note: note})
		}
		writeCommandBlock(b, "Charms", charmLines)
	}

	if len(n.Dependencies) > 0 {
		b.Paragraph(md.Bold("Depends on:"))
		deps := make([]string, 0, len(n.Dependencies))
		for _, d := range n.Dependencies {
			// Link each dependency to its own section. GitHub derives a heading's
			// anchor by lowercasing and stripping the backticks, so `man-generate`
			// resolves to #man-generate.
			deps = append(deps, md.Link(md.Code(d), "#"+strings.ToLower(d)))
		}
		b.List(deps...)
	}

	// Note: a target's spells are not restated here — they ride in its graph node
	// (as per-spell boxes inside the target's subgraph), which is the section's
	// authoritative view of the toolchain a target drives. A prose block would only
	// duplicate that, the way `**Depends on:**` does not (it earns its place with
	// anchor links spells lack).

	e, ok := eval[EvalKey(path, n.Name)]
	if !ok {
		return
	}
	if cmds := renderedCommands(e); len(cmds) > 0 {
		b.Paragraph(md.Bold("Executes"))
		b.CodeBlock("sh", cmds...)
	}
	if notes := policyNotes(e.Policy); len(notes) > 0 {
		b.Paragraph(md.Bold("Details:") + " " + strings.Join(notes, " · "))
	}
}

// projectDefaults returns the evaluated target that stands in for path's shared
// defaults. Every target in a project keys off the same base spec, so any of them
// carries the same sources, outputs, and spells. We pick the one with the
// lexicographically-smallest target name rather than ranging the map and taking
// whatever comes first: Go randomizes map iteration order, so "first match" makes
// the rendered defaults block nondeterministic the moment that invariant is even
// slightly off. The bool is false when eval carries nothing for the path.
func projectDefaults(path string, eval map[string]types.EvaluatedTargetEntry) (types.EvaluatedTargetEntry, bool) {
	var best types.EvaluatedTargetEntry
	found := false
	for _, e := range eval {
		if e.Project != path {
			continue
		}
		if !found || e.Target < best.Target {
			best, found = e, true
		}
	}
	return best, found
}

// spellsLine renders the project's spells as a comma-separated list, annotating
// any spell that carries effective claims.
func spellsLine(spells []types.EvaluatedSpellEntry) string {
	parts := make([]string, 0, len(spells))
	for _, s := range spells {
		if len(s.EffectiveClaims) > 0 {
			parts = append(parts, fmt.Sprintf("%s (claims: %s)", s.Name, strings.Join(s.EffectiveClaims, ", ")))
		} else {
			parts = append(parts, s.Name)
		}
	}
	return strings.Join(parts, ", ")
}

// renderedCommands returns the statically-known argv of each spell that resolves
// to one, one command per string. Empty for function-op targets whose body isn't
// a declarative spell op.
func renderedCommands(e types.EvaluatedTargetEntry) []string {
	var out []string
	for _, s := range e.Spells {
		if len(s.Command) > 0 {
			out = append(out, strings.Join(s.Command, " "))
		}
	}
	return out
}

// policyNotes describes the non-default behavioural policy of a target, or nil
// when the policy is unset or all-default.
func policyNotes(p *types.Target) []string {
	if p == nil {
		return nil
	}
	var out []string
	if p.FailOnDrift {
		out = append(out, "fail-on-drift (fails if the tree is dirty afterward)")
	}
	if p.RetryOnFlake {
		out = append(out, "flake-tracked (retries a flaky failure)")
	}
	if p.SkipCache {
		out = append(out, "uncached (always runs)")
	}
	if p.Exclusive {
		out = append(out, "exclusive (runs alone, no concurrent targets)")
	}
	return out
}

// WriteTargetGraphMermaid emits a target dependency graph as a Mermaid flowchart.
// It is the one Mermaid emitter for the target graph: `magus describe graph -o
// mermaid` and the markdown doc both route through it. See targetGraphIR for the
// stage-boxing and role-styling rules.
func WriteTargetGraphMermaid(w io.Writer, out types.TargetGraphOutput) error {
	return writeMermaid(w, targetGraphIR(out))
}

// targetGraphIR maps the target dependency graph onto the shared renderGraph. With
// more than one project, each is a subgraph and its node IDs are prefixed (so a
// `build` in two projects stays distinct). Worker targets sharing a trailing
// `-<segment>` (e.g. `man-generate`, `docs-generate`) are boxed into a collapsing
// stage subgraph, so an edge lands on the box rather than a worker inside it; the
// bare composite (`generate`) stays loose. Nodes are classed by role: top-level
// targets (nothing depends on them) versus plain targets pulled in as dependencies.
// Edges point in run order — a dependency to the target that needs it.
func targetGraphIR(out types.TargetGraphOutput) renderGraph {
	projects := nonEmptyProjects(out)
	multi := len(projects) > 1
	// LR so the graph reads left-to-right like a pipeline. The extra rank/node
	// spacing gives dagre room to route around the per-target spell boxes (GitHub
	// has no ELK engine to lean on). DOT ignores these layout hints.
	g := renderGraph{DOTName: "targets", Direction: "LR", NodeSpacing: 50, RankSpacing: 80}

	// projGroupOf maps a project path to its wrapper-subgraph id, filled as each
	// project is emitted below; the cross-project edge pass (after the loop) reads
	// the completed map so a dependency on a later-listed project still resolves.
	projGroupOf := make(map[string]string, len(projects))

	for i, p := range projects {
		prefix, projGroup := "", ""
		if multi {
			prefix = fmt.Sprintf("p%d_", i)
			projGroup = fmt.Sprintf("p%d", i)
			projGroupOf[p.Path] = projGroup
			g.Groups = append(g.Groups, renderGroup{ID: projGroup, Label: p.Path})
		}

		known := make(map[string]bool, len(p.Nodes))
		for _, n := range p.Nodes {
			known[n.Name] = true
		}
		incoming := map[string]bool{}
		for _, n := range p.Nodes {
			for _, d := range n.Dependencies {
				if known[d] {
					incoming[d] = true
				}
			}
		}

		stageOf, stageOrder := stageGroups(p.Nodes)
		for _, stage := range stageOrder {
			g.Groups = append(g.Groups, renderGroup{
				ID:       prefix + "stage_" + mermaidID(stage),
				Label:    stage,
				Parent:   projGroup,
				Collapse: true,
			})
		}

		for _, n := range p.Nodes {
			group := projGroup
			if s := stageOf[n.Name]; s != "" {
				group = prefix + "stage_" + mermaidID(s)
			}
			// Every target is a single node coloured by role; the spells it drives
			// live in the project's separate Toolchain graph (writeToolchainGraph), not
			// boxed inside this one. Two roles only: a top-level target (nothing depends
			// on it — a typical entry point) versus a plain target pulled in as a
			// dependency. Both are runnable; the split is a hint, not a rule.
			role := "target"
			if !incoming[n.Name] {
				role = "anchor"
			}
			g.Nodes = append(g.Nodes, renderNode{
				ID:      prefix + mermaidID(n.Name),
				DOTID:   p.Path + ":" + n.Name,
				Label:   n.Name,
				Shape:   shapeRounded,
				Classes: []string{role},
				Group:   group,
			})
		}
		// Edges point in run order, not dependency order: an arrow from a target's
		// dependency to the target itself, so the graph reads "what runs first" left
		// to right (preflight → … → ci), the inverse of the "depends on" relation.
		for _, n := range p.Nodes {
			to := prefix + mermaidID(n.Name)
			for _, d := range n.Dependencies {
				g.Edges = append(g.Edges, renderEdge{From: prefix + mermaidID(d), To: to})
			}
		}
	}

	// Cross-project edges, in run order: a project a depends on runs first, so its
	// box points at the project that needs it. Endpoints are the wrapper-subgraph
	// ids; an edge from a project that contributed no nodes (dropped) is skipped.
	if multi {
		for _, p := range projects {
			to := projGroupOf[p.Path]
			for _, dep := range p.DependsOn {
				if from, ok := projGroupOf[dep]; ok {
					g.Edges = append(g.Edges, renderEdge{From: from, To: to})
				}
			}
		}
	}

	g.Classes = slices.Clone(targetRoleClasses)
	return g
}

// stageGroups buckets a project's *worker* targets into a collapsing stage
// subgraph named for their shared trailing `-<segment>` (e.g. `man-generate`,
// `docs-generate` → a `generate` box). A worker joins stage `seg` only when a
// composite target named `seg` exists *and directly depends on it* — the box reads
// as "the steps `seg` runs", so a same-suffix target the composite does not run
// (e.g. a standalone `pgo-generate`) stays loose rather than landing in the box.
// A stage needs two or more such workers; a lone one (or a unique suffix like
// `release`) stays loose. The composite itself is left out of its own box so an
// edge lands on the box, not a `generate` node nested in a `generate` subgraph.
func stageGroups(nodes []types.TargetGraphNode) (map[string]string, []string) {
	present := make(map[string]bool, len(nodes))
	deps := make(map[string]map[string]bool, len(nodes))
	for _, n := range nodes {
		present[n.Name] = true
		set := make(map[string]bool, len(n.Dependencies))
		for _, d := range n.Dependencies {
			set[d] = true
		}
		deps[n.Name] = set
	}

	members := map[string][]string{} // segment -> workers the composite depends on
	for _, n := range nodes {
		seg := lastSegment(n.Name)
		if n.Name == seg || !present[seg] || !deps[seg][n.Name] {
			continue
		}
		members[seg] = append(members[seg], n.Name)
	}

	stageOf := map[string]string{}
	var order []string
	for seg, ms := range members {
		if len(ms) < 2 {
			continue // a lone boxed worker doesn't earn a subgraph
		}
		order = append(order, seg)
		for _, m := range ms {
			stageOf[m] = seg
		}
	}
	slices.Sort(order)
	return stageOf, order
}

// lastSegment returns the text after the final '-', or the whole name if none.
func lastSegment(name string) string {
	if i := strings.LastIndexByte(name, '-'); i >= 0 {
		return name[i+1:]
	}
	return name
}

// uniqSorted returns s sorted with duplicates removed.
func uniqSorted(s []string) []string {
	slices.Sort(s)
	return slices.Compact(s)
}

// WriteTargetGraphDOT emits the target graph as Graphviz DOT, nodes qualified by
// project path so cross-project name clashes stay distinct.
func WriteTargetGraphDOT(w io.Writer, out types.TargetGraphOutput) error {
	return writeDOT(w, targetGraphIR(out))
}

// nonEmptyProjects drops projects with no extracted targets (e.g. a not-yet-
// supported engine) so they don't clutter the rendered graph.
func nonEmptyProjects(out types.TargetGraphOutput) []types.TargetGraphProject {
	ps := make([]types.TargetGraphProject, 0, len(out.Projects))
	for _, p := range out.Projects {
		if len(p.Nodes) > 0 {
			ps = append(ps, p)
		}
	}
	return ps
}
