// Code generated by magus-utils enums. DO NOT EDIT.

package spells

// Values lists the PatchOpKind values a caller may choose, excluding the zero value.
func (v PatchOpKind) Values() []string {
	return []string{"add", "remove", "replace", "move", "copy", "test"}
}

// Valid reports whether v is a declared PatchOpKind. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
func (v PatchOpKind) Valid() bool {
	if v == "" {
		return true
	}
	for _, s := range v.Values() {
		if string(v) == s {
			return true
		}
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v PatchOpKind) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the VersionComponent values a caller may choose, excluding the zero value.
func (v VersionComponent) Values() []string { return []string{"major", "minor", "patch"} }

// Valid reports whether v is a declared VersionComponent. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
func (v VersionComponent) Valid() bool {
	if v == "" {
		return true
	}
	for _, s := range v.Values() {
		if string(v) == s {
			return true
		}
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v VersionComponent) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}
