// Code generated by magus-utils enums. DO NOT EDIT.

package spells

// Values lists the PatchOpKind values a caller may choose, excluding the zero value.
func (v PatchOpKind) Values() []string {
	return []string{"add", "remove", "replace", "move", "copy", "test"}
}

// Valid reports whether v is a declared PatchOpKind. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v PatchOpKind) Valid() bool {
	switch v {
	case "", "add", "remove", "replace", "move", "copy", "test":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v PatchOpKind) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the VersionComponent values a caller may choose, excluding the zero value.
func (v VersionComponent) Values() []string { return []string{"major", "minor", "patch"} }

// Valid reports whether v is a declared VersionComponent. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v VersionComponent) Valid() bool {
	switch v {
	case "", "major", "minor", "patch":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v VersionComponent) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}

// Values lists the DiagnosticFormat values a caller may choose, excluding the zero value.
func (v DiagnosticFormat) Values() []string { return []string{"gnu"} }

// Valid reports whether v is a declared DiagnosticFormat. The zero value is valid: it means the
// field was not set, which callers distinguish from a wrong value.
//
// A switch rather than a scan over Values: Values allocates a fresh slice per call so
// its result can never be mutated by a caller, which is the right trade for a helper
// that builds an error message and the wrong one for a predicate.
func (v DiagnosticFormat) Valid() bool {
	switch v {
	case "", "gnu":
		return true
	}
	return false
}

// String renders v for an error message: the value, or "unset" when empty.
func (v DiagnosticFormat) String() string {
	if v == "" {
		return "unset"
	}
	return string(v)
}
